[WIP] New turrets
cataclysmbnteam/Cataclysm-BN pull request #149
Opened 2020-10-27 18:16 UTC by Firestorm01X2

New turrets

#### Summary
SUMMARY: Content "New turrets"

#### Purpose of change
Current interation of turrest very unbalanced and deadly.

#### Describe the solution
Remove 
mon_turret_rifle
mon_crows_m240
mon_turret_bmg

Create
1) Light 9mm turrets
2) Medium 5.56 turret
3) Sniper 7.62 turret.

Balance turrets and place spawns.

#### Describe alternatives you've considered

#### Testing
1) Observe new turrets.

#### Additional context
None

2020-10-28 19:48 UTC, Firestorm01X2 commented
Ready for review.

2020-10-28 20:12 UTC, Coolthulhu commented on data/json/items/corpses/inactive_bots.json
> +      "skill2": "computer"
Crap, I wish I merged that skill vector thing earlier...
It will need to be changed to `"skills": ["electronics","computer"]`, to be compatible with the syntax that Aftershock will be using.
I'll try to merge that change ASAP.

2020-10-28 20:16 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
That range is tiny. Can it be increased with that gun?
It can have great accuracy, it's damage output should be limited by burst size, not misses.

2020-10-28 20:19 UTC, Coolthulhu commented on data/json/monsters/obsolete.json
> +        "gun_type": "m249",
Might be a good idea to change its gun to something inherently single fire. If there is an adequate gun.

2020-10-28 20:21 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +        "gun_type": "m249_turret_fake",
Would be better to find an inherently single fire gun for this.

2020-10-28 20:21 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "gun_type": "m249_turret_fake",
There is a problem. Player will get that gun after turret dissambly. So considering this I've put fake LMGs for single fire.

2020-10-28 20:22 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "gun_type": "m249_turret_fake",
Espically it is beter to avoid sniper rifles since it comes with scopes.

2020-10-28 20:22 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 30, "DEFAULT" ] ],
That range is poor. It's single fire so it can have at least that 36, like the turret it replaces.

2020-10-28 20:23 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 45, "DEFAULT" ] ],
That's not very long range. It should be 60.

2020-10-28 20:23 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
Yest it tiny. Becasue it is 9mm range for mp5.

2020-10-28 20:24 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +        "gun_type": "m240_turret_fake",
Why does it need a fake gun type? Why can't it use the gun used to craft it?

2020-10-28 20:25 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "gun_type": "m240_turret_fake",
Because LMGs is only has burst fire.

2020-10-28 20:26 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "gun_type": "m240_turret_fake",
> Why can't it use the gun used to craft it?

It it is not a problem- I wil do it. But it can be gifted assault rifle.

2020-10-28 20:27 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 45, "DEFAULT" ] ],
> That's not very long range. It should be 60.

Then it will shoot you as long as it reach its vision range. It is 50 tiles for now. Well +5 tiles is not a big deal. But it gives player less time to react to threat.

2020-10-28 20:29 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 30, "DEFAULT" ] ],
+6 tiles is not a big deal. Ok.

2020-10-28 21:35 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "gun_type": "m240_turret_fake",
Done. Used m14ebr.

2020-10-28 21:36 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 45, "DEFAULT" ] ],
Done. 60 tiles. Vision range still 50 tiles. Audibacle waring set to 60 tiles.

2020-10-28 21:36 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 30, "DEFAULT" ] ],
Done. 36 tiles

2020-10-28 21:37 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "gun_type": "m249_turret_fake",
Fakes removed. Done,

2020-10-28 21:37 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
Can't do. 9mm range limitation. Still current range suitable for light turret role- indoor mostly.

2020-10-28 21:39 UTC, Firestorm01X2 commented on data/json/items/corpses/inactive_bots.json
> +      "skill2": "computer"
No problem. No rush there. I'll merge it from upload once ready.

2020-10-28 21:54 UTC, Firestorm01X2 commented on data/json/items/corpses/inactive_bots.json
> +      "skill2": "computer"
Thank you! Done.

2020-10-28 21:54 UTC, Firestorm01X2 commented
Ready for review again.

2020-10-29 06:10 UTC, Coolthulhu commented on data/json/mapgen/bunker.json
> +        { "monster": "mon_turret_light", "x": 14, "y": 14 }
It's a military bunker, it should have the rifle turrets.

2020-10-29 06:11 UTC, Coolthulhu commented on data/json/mapgen/missile_silo.json
> +      "monster": { "S": { "monster": "mon_turret_searchlight" }, "T": { "monster": "mon_turret_light" } }
Searchlights imply that it's out in the open. The 14 tile range turret won't work.

2020-10-29 06:12 UTC, Coolthulhu commented on data/json/monstergroups/robots.json
> +    "monsters": [ { "monster": "mon_turret_light", "freq": 50, "cost_multiplier": 2 } ]
The old group has rifle/bmg, so dangerous stuff. Here you added the light turret twice, which is too safe.

2020-10-29 06:17 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
That's heavily limiting - at 14 tiles, the player can "snipe" it with a longbow, yet the turret spawns in the open.
I couldn't find a good gun to use here (all high-range 9mm are single fire), so this warrants a fake item.

2020-10-29 06:20 UTC, Coolthulhu commented on src/map_extras.cpp
> +            m.add_spawn( mon_turret_medium, 1, { p, abs_sub.z } );
It had bmg before, so it should probably spawn with higher tiers - long range and medium.

2020-10-29 06:25 UTC, Coolthulhu commented
* What is the burst size of the turrets? Should be 4+ for 9mm (at 22 dmg, it needs 4-5 hits on same unarmored bp to kill) and 2-3 for 5.56 (2 hits on unarmored bp will kill it). 4 rifle shots is pushing it, but still tolerable.
* Obsolete items need to use the new syntax (`skills` instead of `skill1/2`) or to be removed and replaced by migration entries. Travis complains about unread fields and core should never have those.

2020-10-29 08:20 UTC, Firestorm01X2 commented on src/map_extras.cpp
> +            m.add_spawn( mon_turret_medium, 1, { p, abs_sub.z } );
It is roadblock. Imagine player driving car. Most likely he will not have had time to react to stop car for 50 tiles.

2020-10-29 08:38 UTC, Firestorm01X2 commented on src/map_extras.cpp
> +            m.add_spawn( mon_turret_medium, 1, { p, abs_sub.z } );
Also int that case there is non zero chance to spawn 2 longrange turrests. I suspect that it may lead to instant death then dricing car or motorcicle.

2020-10-29 08:40 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
What range to use then?

2020-10-29 08:49 UTC, Firestorm01X2 commented on data/json/mapgen/bunker.json
> +        { "monster": "mon_turret_light", "x": 14, "y": 14 }
Done for outside turrets,

2020-10-29 08:53 UTC, Firestorm01X2 commented on data/json/monstergroups/robots.json
> +    "monsters": [ { "monster": "mon_turret_light", "freq": 50, "cost_multiplier": 2 } ]
Replace on turret to light to medium.

2020-10-29 09:08 UTC, Firestorm01X2 commented on data/json/mapgen/missile_silo.json
> +      "monster": { "S": { "monster": "mon_turret_searchlight" }, "T": { "monster": "mon_turret_light" } }
Done.

2020-10-29 09:38 UTC, Coolthulhu commented on src/map_extras.cpp
> +            m.add_spawn( mon_turret_medium, 1, { p, abs_sub.z } );
Same could happen with medium turrets.
Car would shield the player well enough. Motorcycle is suicide anyway, because the player will get shot while driving full speed towards the roadblock and so won't be able to escape - the only solution here is "don't drive bikes at night". Until we figure out some other warning.
How are the turrets positioned? Parallel to the road or perpendicular? If parallel, the player will get attacked by one turret first, then another, making it relatively safe. If perpendicular, both will fire at once, which could be an instant kill in a motorcycle, but again - motorcycle at night is currently suicidal.

2020-10-29 09:47 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
36 for single shot, 20 for burst.
If it's inaccurate at that range, try bumping its skills and perception. It should hit at least ~30% of the time on max range.

2020-10-29 09:48 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
I've pushed range of light turret to 20. Burst range to 10. I guess it is borrderline sane limit for close range turret.

2020-10-29 09:50 UTC, Firestorm01X2 commented on src/map_extras.cpp
> +            m.add_spawn( mon_turret_medium, 1, { p, abs_sub.z } );
Probably resolved since light turret's range was buffed?

2020-10-29 09:51 UTC, Firestorm01X2 commented
>     * What is the burst size of the turrets? Should be 4+ for 9mm (at 22 dmg, it needs 4-5 hits on same unarmored bp to kill) and 2-3 for 5.56 (2 hits on unarmored bp will kill it). 4 rifle shots is pushing it, but still tolerable.

For light turrret it is 4 shots. Other turrest for now semi-auto only.

>Obsolete items need to use the new syntax (skills instead of skill1/2) or to be removed and replaced by migration entries. Travis complains about unread fields and core should never have those.

Done

2020-10-29 11:05 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
Oh I see. So even more range

2020-10-29 12:32 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
Pushed max range for light turret for 32. Burst [0,16]. It is borderline range for 9mm carbines. 34- max for Cx4. I am using KelTec-SUB 2000 for light turret now. I hope it is enough.

2020-10-29 12:34 UTC, Firestorm01X2 commented on src/map_extras.cpp
> +            m.add_spawn( mon_turret_medium, 1, { p, abs_sub.z } );
Done.

2020-10-29 12:49 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +        "ranges": [ [ 0, 6, "AUTO" ], [ 7, 14, "DEFAULT" ] ],
Probably resolved.

2020-10-29 13:02 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +    "description": "The General Atomics TX-5 Sentinel, a medium, automated milspec 5.56mm gun turret.  Designed to efficiently take down enemy personnel with modern body armor at medium ranges.",
> a medium, automated milspec 5.56mm gun turret

Lots of adjectives.
Would be better to split it up.
Say

> ...Sentinel, an automated turret fitted with a 5.56mm gun.

Also, I think range should be singular here.
The "personnel with body armor" sounds like it's missing something. "personnel protected by body armor"?

2020-10-29 13:04 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +    "description": "The General Atomics TX-1 Guardian, a light, automated 9mm gun turret.  Hight quality targetting system allows it to engage targets even at medium ranges.",
"Hight" - typo.
Range should probably be singular.
I'm not sure how many commas should be in the first sentence, it may be a good idea to rewrite it so that it doesn't have that "9mm gun turret".
"automated turret equipped with a 9mm gun"?

2020-10-29 13:06 UTC, Coolthulhu commented on data/json/monsters/turrets.json
> +    "description": "The General Atomics TX-7 Sniper, a long range, automated milspec 7.62mm gun turret.  Designed as counter sniper turret.  Its advanced target recognition system and 7.62mm gun allo
> Designed as `a` counter sniper turret

Range should probably be singular.
As with other turrets, it should probably not have so many adjectives right after each other.

2020-10-29 13:59 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +    "description": "The General Atomics TX-5 Sentinel, a medium, automated milspec 5.56mm gun turret.  Designed to efficiently take down enemy personnel with modern body armor at medium ranges.",
Done.

2020-10-29 14:00 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +    "description": "The General Atomics TX-7 Sniper, a long range, automated milspec 7.62mm gun turret.  Designed as counter sniper turret.  Its advanced target recognition system and 7.62mm gun allo
Done

2020-10-29 14:00 UTC, Firestorm01X2 commented on data/json/monsters/turrets.json
> +    "description": "The General Atomics TX-1 Guardian, a light, automated 9mm gun turret.  Hight quality targetting system allows it to engage targets even at medium ranges.",
Done

2020-10-29 14:00 UTC, Firestorm01X2 commented
Ready again.

2020-10-29 14:25 UTC, Firestorm01X2 commented
I am just thinking about ammo count. I've reduced it a lot. It is ok?

2020-10-29 16:44 UTC, Coolthulhu commented
Alright, now I see why there were fakes for all turrets:
They need that a tag that gives them internal magazines, otherwise they drop physical magazines on death...

Also, light and medium turrets need to have high `fake_str`, because they very quickly lose accuracy during burst.

Finally, needs a rebase. Don't know what could have caused it conflicts, but apparently something did.

2020-10-29 19:04 UTC, Firestorm01X2 commented
After some thinking and testing I've decided to increase ammo count for turrets. Problem is that player set turrets will use same starting ammo when placed. For player it will be quite inconvenient and confusing.

2020-10-30 15:56 UTC, Coolthulhu requested changes

2020-10-30 15:56 UTC, Coolthulhu commented on data/json/effects.json
> +    "scaling_mods": { "str_mod": [ -0.005 ], "dex_mod": [ -0.005 ], "int_mod": [ -0.005 ], "per_mod": [ -0.005 ] },
Needs a rebase.

2020-10-30 15:56 UTC, Coolthulhu commented on data/json/items/generic.json
> -    "id": "broken_turret_rifle",
Some mods still use the broken turrets. You'll need to modify the mods too.

2020-10-30 15:56 UTC, Coolthulhu commented on data/json/items/obsolete.json
> +    "id": "bot_turret",
Also used by mods

2020-10-30 15:56 UTC, Coolthulhu commented on data/json/monsters/obsolete.json
> +    "id": "mon_turret_rifle",
Monsters are also referenced in mods.

2020-10-30 19:38 UTC, Firestorm01X2 commented on data/json/items/generic.json
> -    "id": "broken_turret_rifle",
"type": "GENERIC",
    "id": "broken_turret",

Is still in data\json\items\generic.json
This thing was not obsolated. Even new turret use it in copy-from.

2020-10-30 20:40 UTC, Firestorm01X2 commented
Ok. I've checked mods. Whitelisted ones laods fine after ediditng.
Some blacklisted throws unreleated mapgen errors.

2020-10-30 20:45 UTC, Firestorm01X2 commented on data/json/items/obsolete.json
> +    "id": "bot_turret",
Ok. That was confusing. 
Note that I've ignored looks_like to avoid dropping tiles. Also modualr turets uses weird copy_from stratagy.

But at least it loads after my changes.

2020-10-30 20:48 UTC, Firestorm01X2 commented on data/json/monsters/obsolete.json
> +    "id": "mon_turret_rifle",
Done also. It loads after changes.

2020-10-30 20:48 UTC, Firestorm01X2 commented on data/json/items/generic.json
> -    "id": "broken_turret_rifle",
So, Resolved.

2020-10-31 10:37 UTC, Firestorm01X2 commented on data/json/items/obsolete.json
> +    "id": "bot_turret",
Done

2020-10-31 11:14 UTC, Coolthulhu approved these changes

2020-10-31 12:45 UTC, merged

2020-10-31 12:46 UTC, Coolthulhu commented
Whew, that sure turned out to be bigger than it looked at first.
I have few minor nitpicks, but it's good for now.

Some mods still reference the inactive turret items, but have them on blacklists (???). Would be better to replace them with the new turrets.