Rework Start
cataclysmbnteam/Cataclysm-BN pull request #1619
Opened 2022-06-12 20:56 UTC by KheirFerrum

#### Summary

SUMMARY: Infrastructure "Change regeneration modifiers into a JsonObject instead of an array."

#### Purpose of change

Suggested by @Coolthulhu to allow for easier read/write and to add scaling modifiers for effect intensities.

#### Describe the solution

Turns regeneration modifier into a vector<struct>.

Temporarily adds a print message proceeding regeneration in order to know how much is actually being regenerated.

#### Describe alternatives you've considered

- Just extend the array to contain 3 variables instead of 2.
Considered to not be particularly user friendly for reading/writing.

#### Testing

- [ ] Test that debug monster when burned has modifier adjusted accordingly.
- [ ] Test that debug monster when corroded has modifier adjusted accordingly.

#### Additional context

Currently for whatever reason the game won't actually load the regeneration modifiers, hence draft pull.

2022-06-12 21:20 UTC, AngelicosPhosphoros requested changes

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/mtype.h
> +struct regen_mod {
I would rather call it `regen_modifier`.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/mtype.h
> +    regen_mod( const efftype_id &id, float &bm, float &sf ) :
This doesn't needed: there is aggregate initialization for structures:
```cpp
// Declare struct like that
struct A{
   T0 f0; 
   T1 f1;
   T2 f2;
};

// Than user can initialize it like that:
A my_new_var = A {
    my_eff_id, t1_val, t2_val
};
```

Just need to declare in second place in right order but your constructor doesn't prevent it anyway.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/mtype.h
> +    float base_mult;
Better set defaults right here: `float base_mult = 1.0;`
This way we could avoid undefined behaviour if someone instantiate our struct like `regen_mod my_cool_regen_mod;` then reads uninitialized value of field.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/mtype.h
> +        std::vector<regen_mod> regeneration_modifiers;
You probably should not change to vector here.
Just change second argument:
`std::map<efftype_id, regen_mod> regeneration_modifiers;`

Maybe you also can remove `efftype_id` from struct but I am not sure.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +        erase_if( regeneration_modifiers, [&]( const regen_mod & elem ) { return elem.eff_id == effect; } );
You would be able to avoid changine code here if you don't change map to vector.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +    float scaling_mod = ( inner.has_float( "scaling_mod" ) ) ? inner.get_float( "scaling_mod" ) : 0;
Better to use const everywhere by default e.g. `const float base_mod = inner.get_float("base_mod");`

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +    regeneration_modifiers.emplace_back( effect, base_mod, scaling_mod );
I would rather split that into 2 things:
```cpp
const regen_mod modifier {effect, base_mod, scaling_mod};
regeneration_modifiers.push_back(modifier);
```

Or if you preserve `map`:
```cpp
const regen_mod modifier {effect, base_mod, scaling_mod};
regeneration_modifiers.emplace(modifier.eff_id, modifier);
```

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +    if( !jo.has_object( member ) ) {
In your JSONs you are still have array here. It was array of **other** arrays of 2 items in each, now you have an array of objects. So you shoud keep here old array check.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +    for( const JsonValue entry : jo.get_object( member ) ) {
Same here: `get_array` because in `regeneration_modifiers` is an array in JSONs.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +            add_regeneration_modifier( entry.get_object(), src );
This is only lines you should change here.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +            entry.throw_error( "object element is not an object " );
`array element is not an object`.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/monstergenerator.cpp
> +        erase_if( regeneration_modifiers, [&]( const regen_mod & elem ) { return elem.eff_id == effect; } );
As I say, you don't really need to change map to vector.

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/mtype.h
> +    efftype_id eff_id;
`effect_id`?

2022-06-12 21:20 UTC, AngelicosPhosphoros commented on src/mtype.h
> +    float base_mult;
Also, `base_multiplier`.

2022-06-13 07:54 UTC, AngelicosPhosphoros commented on src/monster.cpp
> +                                   ( e.get_intensity() - 1 ) * regeneration_modifier.second.scale_modifier;
You don't really need to call `get_effect` here if there monster has not that effect.
Maybe better to write it like that?
```cpp
for (const auto& it: type->regeneration_modifiers){
   const efftype_id& effect_id = it.first;
   const regen_modifier& regeneration_modifier = it.second;
   if (has_effect(effect_id)){
      const effect& e = get_effect(effect_id);
      regeneration_amount *= 1.00 + regeneration_modifier .base_modifier +
                                   ( e.get_intensity() - 1 ) * regeneration_modifier .scale_modifier;
   }
}
```

2022-06-13 07:54 UTC, AngelicosPhosphoros commented on src/mtype.h
> +    const float base_modifier = 0.00;
nit: const fields rarely useful. It is more important for variables and function arguments.

2022-06-13 07:54 UTC, AngelicosPhosphoros commented on src/mtype.h
> +    regen_modifier( float &bm, float &sf ) :
As I said earlier, you don't need constructor here. Your code should compile if you delete it.
See, it compiles: https://godbolt.org/z/7sEYE9bGP

2022-06-13 11:46 UTC, Coolthulhu commented on src/monster.cpp
> +                                   ( e.get_intensity() - 1 ) * regeneration_modifier.second.scale_modifier;
You can also call a `get_effect` on non-existent effect, which will return a reference to a sentinel that is guaranteed to evaluate to `false` when cast to `bool`.
```C++
const effect& e = get_effect(effect_id);
if( e ) {
  ...
}
```

2022-06-13 11:47 UTC, Coolthulhu commented on src/mtype.h
> +    const float base_modifier = 0.00;
Still helps with readability IMO.

2022-06-13 15:43 UTC, AngelicosPhosphoros commented on src/monster.cpp
> +        add_msg( m_debug, _( "Regen: %s" ), healed_amount );
Do we really need translations for debug messages? `_( xxxx )` translates xxxx into target language.

2022-06-20 22:00 UTC, Coolthulhu commented on src/monstergenerator.cpp
> +    float scaling_mod = ( inner.has_float( "scaling_mod" ) ) ? inner.get_float( "scaling_mod" ) : 0 ;
`get_float` has an overload with a fallback, used like this:
```C++
inner.get_float( "x", 0.0f );
```

2022-06-21 08:07 UTC, Coolthulhu commented
I don't get why is Mac version of Clang complaining. Try adding an explicit `operator=` maybe?

Also, a user on discord had heal msgs being printed for unseen critters. I checked the current version and it looks like the heal msg is printed regardless of whether you can see the monster or not. Could bundle a fix for this with this PR, since it should be just one extra `&& get_player_character().sees(mon)` check in an `if`.

2022-06-22 00:00 UTC, KheirFerrum commented
> I don't get why is Mac version of Clang complaining. Try adding an explicit `operator=` maybe?
> 
> Also, a user on discord had heal msgs being printed for unseen critters. I checked the current version and it looks like the heal msg is printed regardless of whether you can see the monster or not. Could bundle a fix for this with this PR, since it should be just one extra `&& get_player_character().sees(mon)` check in an `if`.

I'm not sure how to do the `operator=`. I'll try to fix the heal message right now.

2022-06-28 19:32 UTC, Coolthulhu commented on src/mtype.h
> +    const float scale_modifier;
I think it's those `const`s that are making the mac compiler complain.
It's a semi-blind guess, but worth a shot, I think.

```
src/mtype.h:208:8: note: in instantiation of member function 'std::__1::map<string_id<effect_type>, regen_modifier, std::__1::less<string_id<effect_type> >, std::__1::allocator<std::__1::pair<const string_id<effect_type>, regen_modifier> > >::operator=' requested here
struct mtype {
```

It looks like the compiler wants to use `operator=` on the `regen_modifier`. But since it's made of `const`s, it fails.
While it's nice to have `const`s everywhere, it's worth sacrificing them to Apple overlords this time.

2022-06-30 18:11 UTC, Coolthulhu commented on src/monstergenerator.cpp
> +                              0.0f ) : 0.0f ;
Should also use the fallback overload thing.

2022-06-30 18:19 UTC, Coolthulhu commented on src/monstergenerator.cpp
> +                              0.0f ) : 0.0f ;
Alright, I pushed a commit to fix it.

2022-06-30 19:31 UTC, merged