Make Bionic Guns work
cataclysmbnteam/Cataclysm-BN pull request #1705
Opened 2022-07-07 19:58 UTC by KheirFerrum

#### Summary

SUMMARY: Bugfixes "Makes BIONIC_GUN flag usable again."

#### Purpose of change

Deals with an issue found in #1227 where bionic guns were not firing and instead being used as melee weapons.

#### Describe the solution

Adds `bio.powered = true` and `bio.powered = false` to the BIONIC_GUN portion of `check_or_use_weapon_cbm()` and the `discharge_cbm_weapon` code respectively. For some reason this was causing NPCs not to toggle their ranged CBM weapons

#### Describe alternatives you've considered

- Try some way to make NPCs activate it like PCs do.
Would probably be the best method, but assumes such a method of activation is coded in the game. Will need a closer look at the code.

#### Testing

Installed Bionic Finger Laser into a friendly NPC, spawned debug monster, checked that they shot the thing with the equipped (and very ugly with tileset) bio_laser_finger. Gave them a machete and tested again to make sure their weapon wasn't swallowed by the void when swapped.

#### Additional context

Still some issues with comparing weapons, NPCs won't use the bionic gun even if they've run out of ammo for their gun.

2023-03-22 09:03 UTC, KheirFerrum commented
Toggled CBM reload not yet implemented, not sure _how_ to implement honestly, since again the item doesn't exist unless the NPC activates it. I could have an extra int like magazine size for bionics so it doesn't have to instantiate the item to check how much ammo _can_ be held in it.

2023-04-09 09:07 UTC, Coolthulhu commented on data/json/bionics.json
> +    "flags": [ "BIONIC_TOGGLED", "BIONIC_WEAPON", "BIONIC_NPC_USABLE" ]
I don't like having it require a flag. Are not all bionic weapon/gun items going to be usable?

2023-04-09 09:18 UTC, Coolthulhu commented on src/bionics.cpp
> +        } else if( g->u.sees( pos() ) ) {
`get_player_character()` is preferred over `g->u` in new code.

2023-04-09 09:20 UTC, Coolthulhu commented on src/character.cpp
> +    clear_npc_ai_info_cache( "reloadable cbms" );
Not a new problem here, but when it comes to caches with limited "types" of content, it's good to have them more "typed" where possible.
In order of good to bad:
* Enum or field in class (depends on application)
* Named, static string
* Inline string

2023-04-09 09:26 UTC, Coolthulhu commented on src/item.h
> +        int shots_remaining( units::energy power = 0_J ) const;
Does this operate exclusively on public members? If yes, it would be nice to move it to a function in appropriate namespace rather than a method.

2023-04-09 09:27 UTC, Coolthulhu commented on src/npc.h
> +        std::vector<std::pair<int, item>> find_reloadable_cbms();
Those really don't look like they need to be NPC exclusive methods.

2023-04-09 09:33 UTC, Coolthulhu commented on src/npc.h
> +        int cbm_active_index = -1;
It's OK for this to be an index, but it would be better if we could somehow reference an actual entry by something else.

2023-04-09 12:35 UTC, scarf005 requested changes

2023-04-09 12:35 UTC, scarf005 commented on src/item.cpp
> +}
all the member functions used from `item` classes (get_gun_ups_drain, ammo_required, ammo_remaining) are public members. this means these functions can be called from other functions, not just from inside item class. in other words, it could have been rewritten as for example,
```c++
static auto shots_remaining( const &item it, units::energy power ) -> int
{
    const auto ups_drain = it.get_gun_ups_drain();
    const auto ammo_remaining = ammo_remaining();
    const auto ammo_required = ammo_required();
    const auto energy_drain = units::from_kilojoule( ups_drain );

    if( ammo_required() > 0 && get_gun_ups_drain() > 0 ) {
        return std::min( ammo_remaining, power / energy_drain );
    } else if( ups_drain > 0 ) {
        return power / energy_drain;
    } else if( ammo_required > 0 ) {
        return ammo_remaining;
    } else {
        return 10;
    }
    return 0;
}
```
it's often a better idea to make functions like these non-member. let's make an analogy to cat class. we could have made `doublename` a member function that returns 
```c++
std::string cat::doublename() {
    return name + name;
}
const auto doubled_cat_name = cat.doublename();
```
however, it could have been
```
std::string doublename( const std::string& name ) {
    return name + name;
}
const auto doubled_cat_name = doublename( cat.aname );
```
since doubling cat's name is not really what only a cat can do.

reducing number of member functions are important because otherwise it morphs into ['god object'](https://en.wikipedia.org/wiki/God_object), which is very hard to manage (which is 99% of CBN classes).

also see: 
- https://en.cppreference.com/w/cpp/language/access
- https://en.wikipedia.org/wiki/Single-responsibility_principle

2023-04-09 16:37 UTC, KheirFerrum commented on data/json/bionics.json
> +    "flags": [ "BIONIC_TOGGLED", "BIONIC_WEAPON", "BIONIC_NPC_USABLE" ]
My biggest concern is that this might cause NPCs to pick an item that they have no business using like rockets and similarly destructive weaponry. I could remove this though and define it using the `fake_item`'s firing modes.

2023-04-09 16:44 UTC, KheirFerrum commented on src/npc.h
> +        int cbm_active_index = -1;
Would a pointer work?

2023-04-10 22:20 UTC, KheirFerrum commented on src/npc.h
> +        std::vector<std::pair<int, item>> find_reloadable_cbms();
deactivate_weapon_cbm() and find_reloadable_cbms() were successfully converted I think, but check_or_use_weapon_cbm needs to read and alter cbm_active_index and cbm_toggled_index alongside cbm_fake_active which are all private members of the npc class, so I'm not sure how to do that.

2023-04-10 23:36 UTC, KheirFerrum commented
Note to self: `shots_remaining()` is hacky and needs to be overhauled by making CBMs with `BIONIC_GUNS` read their cost directly from the gun, this would allow me to stop using this weird system where `shots_remaining()` needs to be fed the limiting energy factor. An issue with this right now is that `USES_BIONIC_POWER` as a flag is currently only supported by tools.

2023-04-13 15:04 UTC, scarf005 requested changes
i had difficulty understanding this PR, and i was worried that i might miss technical details which may be critical. i recommend having @Coolthulhu review it again, as they are more familiar with the codebase than i am.

a small suggestion: could you write doxygen docstrings in the headers you've added to help us better understand the changes?

meanwhile, i have requested some changes to enhance the readability of the C++ code.

my apologies for not being able to provide more assistance.

2023-04-14 19:12 UTC, KheirFerrum commented on src/bionics.cpp
> +        if( bio.info().has_flag( flag_BIONIC_WEAPON ) ) {
It just looks like a lot of added lines, I'll simplify it somewhat.

2023-04-20 14:05 UTC, Coolthulhu commented on src/character.h
> +};
The ALL_CAPS are good for legacy enums, but new ones are fine with low_caps. The `::` gives enough context.

2023-04-20 14:06 UTC, Coolthulhu commented on src/character.h
> +        std::optional<double> get_npc_ai_info_cache( const npc_ai_info key ) const;
`const` is not needed for primitive values, like enums. It's mostly useful with references.

2023-04-20 14:14 UTC, scarf005 commented on src/character.h
> +        std::optional<double> get_npc_ai_info_cache( const npc_ai_info key ) const;
i prefer all parameters to be immutable by default, but I guess it boils down to personal preferences.

2023-04-20 17:16 UTC, KheirFerrum commented on src/character.h
> +        mutable std::map<npc_ai_info, double> npc_ai_info_cache;
Did this, but couldn't figure out how to properly initialize array with negative values, as a result I've done some tweaking and made weapon_value return a minimum of 1.0 so it gets checked properly.

2023-04-23 06:25 UTC, scarf005 requested changes

2023-04-23 06:25 UTC, scarf005 commented on src/character.h
> +        mutable std::array<double, npc_ai_info::num_npc_ai_info> npc_ai_info_cache = { 0 };
```suggestion
        mutable std::array<double, npc_ai_info::num_npc_ai_info> npc_ai_info_cache;
```
use array's `fill()` member function to initialize the values. the fill function should be put at the end of Character class' constructor function.

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/a9c2272f6356f490c24c54535e5cb4b9c705d81b/src/character.cpp#L400


[**see example in godbolt**][godbolt]
[c++reference](https://en.cppreference.com/w/cpp/container/array/fill)

[godbolt]: https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:11,positionColumn:2,positionLineNumber:11,selectionStartColumn:2,selectionStartLineNumber:11,startColumn:2,startLineNumber:11),source:'%23include+%3Carray%3E%0A%23include+%3Ciostream%3E%0A%0Aauto+main()+-%3E+int+%7B%0A++++std::array%3Cdouble,+3%3E+cache%3B%0A++++cache.fill(-1)%3B%0A%0A++++for+(+auto+item+:+cache+)+%7B%0A++++++++std::cout+%3C%3C+item+%3C%3C+%22%5Cn%22%3B%0A++++%7D%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:g102,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B17',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+10.2+(Editor+%231)',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+10.2+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

2023-04-23 06:25 UTC, scarf005 commented on src/item_functions.cpp
> +    return 0;
```suggestion
    }
    // Effectively infinite ammo.
    return 10;
```
`return 0;` is a dead code and will never be used.

2023-04-25 18:04 UTC, KheirFerrum commented on src/item_functions.cpp
> +    return 0;
No, this is me not understanding if else correctly, one moment.

2023-04-26 05:14 UTC, scarf005 requested changes
![Cataclysm: Bright Nights - cbn-experimental-2023-04-19-1517-36-g851a5f15e960_01](https://user-images.githubusercontent.com/54838975/234475428-8b279fad-ee2b-4cc2-9a60-fec9cbdec830.png)
![image](https://user-images.githubusercontent.com/54838975/234475346-9e667058-5fd6-4cfc-8de4-cfaaf6e7d913.png)

segmentation fault when reading `cbm_weapon_index` from pre-PR saves. could you check on them?

2023-04-27 10:48 UTC, scarf005 reviewed
i'm struggling to make npc with bionic shotgun CBM installed actually fire shotshells. it'd be appreciated if you could provide an example of testing the PR.

2023-04-27 14:07 UTC, chaosvolt commented
Are you able to get it working with finger lasers or other standard bionic guns? If so it might be something to do with differences in behavior between bionic ranged weapons that draw solely from bionic power vs the ones that need to be loaded.

2023-04-27 14:12 UTC, chaosvolt commented
Ah, the "I want you to use this item" option? Yeah, picking that always makes them assume you want them to wield or wear the item being given. For giving ammo you have to use "let's trade" instead.

2023-04-27 15:57 UTC, KheirFerrum commented
> yes. i was able to make NPC fire their finger laser, but was unable to give them shotshell (they refuse because npcs think given ammo as 'weapons'), thus failed to test them.

Don't use "I want you to use this" but instead "I want you to hold on to this further down".

2023-05-01 12:31 UTC, scarf005 approved these changes
## Active Bionic Weapon test

https://user-images.githubusercontent.com/54838975/235450638-9a58d17c-1206-4ad9-b907-2f6c17448add.mp4

## Toggled Bionic Weapon test

### Shotgun arm test (2 rounds)

https://user-images.githubusercontent.com/54838975/235450643-78b56989-dd16-4c59-a0ab-8fceb9624b3b.mp4

### Shotgun arm test (10 rounds)

https://user-images.githubusercontent.com/54838975/235450646-7238325e-92fb-4f4b-880a-9cbb8515e060.mp4

## Bionic Weapon selection test

### NPC will activate only the Monomolecular Blade 

https://user-images.githubusercontent.com/54838975/235450649-b3436fd9-1d57-4a7c-b651-014d255d9f3d.mp4

### NPC will only activate the shotgun

https://user-images.githubusercontent.com/54838975/235450651-554fe185-1629-480e-bac0-75da7260d631.mp4

also bug confirmed

## Reload/NPC AI fixes

### M4A1 fires then reload magazine

https://user-images.githubusercontent.com/54838975/235451283-afc74c93-6191-4b0d-88b8-38a278cf9870.mp4

#### Infinite loop found:
![image](https://user-images.githubusercontent.com/54838975/235451601-aa595260-77ba-488b-86a5-f825149ded94.png)

if npc has both weapon and bionic weapon, and wielded weapon gets empty, they will forever switch between weapon and bionic weapon. in the above video, i had to uninstall all the bionics to break the loop (and use m4a1). it may be related to the known noted error.

### Shotguns fire once then reload once

https://user-images.githubuserconten
t.com/54838975/235451168-8f382c4e-9ac9-4159-920f-5bb8edd220f5.mp4

---
approving despite having bug, as 
1. it looks like a complex bug to solve
2. it may be related to aforementioned known bug
3. other than that, all tests work

2023-05-01 12:31 UTC, merged