add bungalows 21 and 22
cataclysmbnteam/Cataclysm-BN pull request #2445
Opened 2023-03-19 22:03 UTC by LilShiningMan

#### Summary

#### Purpose of change

increase house spawn variety

#### Describe the solution

#### Describe alternatives you've considered

#### Testing
linted and spawned in-game

#### Additional context
![bungalow21 g](https://user-images.githubusercontent.com/56778776/226212370-579a15c6-090a-49b2-b454-70f24af2123c.png)
![bungalow21 r](https://user-images.githubusercontent.com/56778776/226212371-f7febb77-49d6-4d64-ad88-746e8942a053.png)
![bungalow22 g](https://user-images.githubusercontent.com/56778776/226212373-69d99368-bc4d-4b61-b371-3493c17bde28.png)
![bungalow22r](https://user-images.githubusercontent.com/56778776/226212376-b10cd840-8b4c-4017-a8d7-658579700fba.png)

2023-03-20 07:45 UTC, Firestorm01X2 commented
![изображение](https://user-images.githubusercontent.com/17512620/226276810-56d82416-49cf-4a5f-8f57-35de2fbe2043.png)
You have conflicts in PR. It must be resolved before PR can be accepted.

Additionally I recommend to update your orging repository from time to time.

2023-03-21 01:19 UTC, scarf005 requested changes

2023-03-21 01:19 UTC, scarf005 commented on data/json/overmap/multitile_city_buildings.json
> +  },
## Why a merge conflict is happening?
- PR has 4 changes: bungalows(B) 19, 20, 21, 22. 
- main branch already have B19, B20 merged via #2433 

So to git, this PR tries to overwrite B19, B20. So git asks the person whether to overwrite or not (so you don't overwrite important things). this is called **Merge Conflict**.

## How do i fix it?

github has a [doc for resolving conflict](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) via online editor.

If you're comfortable with git, i'll recommend completely removing B19 and B20 from json then git amend and force push.

2023-03-21 01:36 UTC, scarf005 approved these changes
I've used [github web merge conflict editor](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to fix the conflicts. 

|   21(1F)    |   21(2F)    |
| :---------: | :---------: |
| ![][21(1f)] | ![][21(2f)] |
|   22(1F)    |   22(2F)    |
| ![][22(1f)] | ![][22(2f)] |

overrall, looks nice. also, may i ask which tool do you use to write buildings?

[21(2f)]: https://user-images.githubusercontent.com/54838975/226499441-4967e8b5-0cfc-46fb-a1d3-1a15421eac6b.png
[21(1f)]: https://user-images.githubusercontent.com/54838975/226499447-03282d88-1c3f-42c4-a3f5-bc3d544171eb.png
[22(1f)]: https://user-images.githubusercontent.com/54838975/226499449-30a1d068-247e-419d-a140-f3a42a473700.png
[22(2f)]: https://user-images.githubusercontent.com/54838975/226499450-60f12bbe-6fdb-4823-a5b8-3f1a4a3715ac.png

2023-03-21 02:45 UTC, LilShiningMan commented
> @LilShiningMan If you have any questions about resolving merge conflicts -feel free to ask.

Thanks Firestorm. I'm usually pretty good at updating my repository before making PRs, but obviously didn't this time. Github hates me, so if I need additional help I'll let you know.

==========

> I've used [github web merge conflict editor](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to fix the conflicts.
> 21(1F) 	21(2F)

> overrall, looks nice. also, may i ask which tool do you use to write buildings?

great, thanks scarf, didn't even know about that tool so I'll keep that in mind.  

As for what tools I use, I made my own with spreadsheets years ago -- it works for me, and I know them really well and can make maps pretty quickly, but if I were starting from scratch I'd probably start using the [Hostile Architect tool](https://discourse.cataclysmdda.org/t/hostile-architect-location-builder-tool-extra-locations-mod/26351). If you're interested, you can check out the thread -- I have some comments on there where I have screenshots of the spreadsheets I made.

2023-03-21 03:33 UTC, LilShiningMan commented on data/json/mapgen/house/bungalow21.json
> +        "...%o≠     |$ |,,,,,,,#.",
oops. This was previously merged in CDDA, and there was a toybox there. I don't think that exists in BN, so I've taken it out

2023-03-21 14:12 UTC, scarf005 approved these changes
tests pass and all looks good.

2023-03-21 14:13 UTC, merged