Only run lint workflow when relevent files are modified
cataclysmbnteam/Cataclysm-BN pull request #2473
Opened 2023-03-24 12:56 UTC by scarf005

#### Summary

SUMMARY: Infrastructure "Only run lint workflow when relevent files are modified"

#### Purpose of change

- astyle doesn't needs to be ran on pure json changes.
- style-json doesn't needs to be ran on pure src changes.

#### Describe the solution

add [`paths` filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) for lint workflows.

#### Describe alternatives you've considered

skip build matrix could be skipped for json only changes

2023-03-24 23:45 UTC, scarf005 commented
that's true, but adding `paths` option would make the process faster for unrelated files.

2023-03-25 08:58 UTC, olanti-p requested changes
Ok. I don't know how this will react with the duplicate skip action, guess we'll have to see.

2023-03-25 08:58 UTC, olanti-p commented on .github/workflows/astyle.yml
> +    paths: ["**.cpp", "**.hpp", "**.h", "**.c"]
These workflows check not only the `*.cpp`/`*h` files, but also the various build files that define _how_ these `*.cpp`/`*.h` are compiled.
Example from line 17 of this file:
```
paths: '[".github/workflows/astyle.yml", "Makefile", ".astylerc", "**.cpp", "**.h", "**.c"]'
```
Please add those here.

2023-03-25 08:58 UTC, olanti-p commented on .github/workflows/clang-tidy.yml
> +    paths: ["**.cpp", "**.hpp", "**.h", "**.c"]
Same for this.

2023-03-25 09:47 UTC, scarf005 commented
@olanti-p fixed by using same filters as skip_check.

2023-03-25 10:14 UTC, olanti-p approved these changes
Looks good.
While testing I've found a case where the clang-tidy workflow is erroneously skipped. It's an existing one and wasn't introduced by this PR, but should be easy to fix.

2023-03-25 10:14 UTC, olanti-p commented on .github/workflows/clang-tidy.yml
> +    paths: [ "**.cpp", "**.h", "**.c", "**/CMakeLists.txt", "**/Makefile", "**.hpp", "**.cmake", "tools/clang-tidy-plugin/**" ]
These, and the skip_check, should also have `.github/workflows/clang-tidy.yml`

2023-03-25 10:18 UTC, scarf005 commented on .github/workflows/clang-tidy.yml
> +    paths: [ "**.cpp", "**.h", "**.c", "**/CMakeLists.txt", "**/Makefile", "**.hpp", "**.cmake", "tools/clang-tidy-plugin/**" ]
ok, added them in [512e4c5](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2473/commits/512e4c5f64081cd4cc63fb65de7a82a56f86e6bb)

2023-03-25 10:36 UTC, olanti-p commented on .github/workflows/clang-tidy.yml
> +    paths: ["**.cpp", "**.hpp", "**.h", "**.c"]
Oh, right, `.clang-tidy` is also needed, and it's also missing from both workflow's `paths` and `skip_check`.

2023-03-25 10:43 UTC, olanti-p commented on .github/workflows/clang-tidy.yml
> +    paths: ["**.cpp", "**.hpp", "**.h", "**.c"]
> would it suffice

Some of the tidy config is in `./CMakeLists.txt`, and also in `build-scripts/` now that I look further.
Ideally all of that should be added, in case someone in the future modifies the files, but tidy wouldn't run and properly test the changes.

2023-03-25 11:58 UTC, scarf005 commented on .github/workflows/clang-tidy.yml
> +    paths: ["**.cpp", "**.hpp", "**.h", "**.c"]
added in [a858863](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2473/commits/a8588630231fdaaad651614c20d46bc22df0fb3a).

2023-03-25 13:24 UTC, olanti-p commented
Let's merge this before anything else comes up :)

2023-03-25 13:24 UTC, merged