Add Priority field to Body Parts. Rework Repair Nanobots and NPC first aid action.
cataclysmbnteam/Cataclysm-BN pull request #2482
Opened 2023-03-25 19:58 UTC by KheirFerrum

#### Summary

SUMMARY: Balance "Add Priority field to Body Parts. Rework Repair Nanobots and NPC first aid action."

#### Purpose of change

When I first did a pass over the Repair Nanobots in #1508, I had no idea what I was doing with C++. Now that I sort of do I can fix up some things and make the Repair Nanobots work closer to my vision.

Also, Repair Nanobots not working on broken limbs was a bit weird, so I'm going to make it repair your broken limbs (as long as they've been splinted, or you have Lizard Regeneration)

#### Describe the solution

Add `"essential"` field to body parts. Currently only for Head and Torso. If these body parts reach 0 HP, you die.

Swap `react_cost` on Repair Nanobots for `trigger_cost` to more accurately reflect what it does. Undo the hacks I did to make `react_cost` work for my purposes last time.

Bleeding has been un-RNG'd, and will now prioritize essential body parts first.

Change trigger for HP/mending to once every minute. Both will now increment all wounded/mending parts by 1HP or 1% each, provided you have enough calories and enough bionic energy. If you do not, the system will prioritize injuries first (injured essential parts considered 10 HP more injured than other parts), then broken limbs.

#### Describe alternatives you've considered

Placing mending changes in `character::mend()`
- Feels a bit harder to track since I don't know the order of operation. 

#### Testing

Spawned character, installed nanobots, gave enough power for a single limb, checked that when torso and arm were both similarly injured, torso was healed first, even when both were under 10 HP. Checked that when given enough power for all limbs all limbs were only healed 1 HP.

Broke one of their arms, checked that without a splint it would not heal from the Nanobots. Checked that when I put on the split it incremented by 1% every minute.

#### Additional context

2023-04-03 14:33 UTC, scarf005 requested changes
overall it's an welcome addition. could you refactor the code a bit before merging?

2023-04-03 14:33 UTC, scarf005 commented on src/bionics.cpp
1. could you extract some repetive parts into static function or lambdas? 
2. mentioned in #2535, it'd be more clear to use std::max_element over std::sort.

2023-04-03 14:33 UTC, scarf005 commented on src/character.cpp
> +    return dead;
```suggestion
    const auto all_bps = get_all_body_parts( true );

    return std::any_of( all_bps.begin(), all_bps.end(), [this]( const bodypart_id & bp ) {
        return bp->essential && get_part_hp_cur( bp ) <= 0;
    } );
```
using [std::any_of](https://en.cppreference.com/w/cpp/algorithm/all_any_none_of) could simplify the code here.

2023-04-03 14:33 UTC, scarf005 commented on src/iuse_actor.cpp
> +                damage += part.get_id()->essential * 10;
could you explain what does this line does?

2023-04-03 14:33 UTC, scarf005 commented on src/bionics.cpp
> +                    }
i think using ranged for loop with break statement would make the code more concise.

2023-04-03 14:33 UTC, scarf005 commented on src/bionics.cpp
> +                           get_power_level() >= bio.info().power_trigger && i < static_cast<int>( damaged_hp_parts.size() ) ) {
this condition could be extracted into a lambda to simplify checks, such as

```c++
const auto can_use_bionic = [this, &bio]() -> bool { 
    const bool is_kcal_sufficient = get_stored_kcal() >= 0.85f * max_stored_kcal() + 5;
    const bool is_power_sufficient = get_power_level() >= bio.info().power_trigger;
    return is_kcal_sufficient && is_power_sufficient;
};
```
so it could be used in places like
```c++
for( const bodypart_id &bp : damaged_hp_parts ) {
    if( !can_use_bionic() ) {
        break;
    }
    heal( bp, 1 );
    mod_power_level( -bio.info().power_trigger );
    mod_stored_kcal( -5 );
}
```

2023-04-03 14:33 UTC, scarf005 commented on src/bionics.cpp
> +                    if( hp_cur > 0 && hp_cur < get_part_hp_max( bp ) ) {
is it neccesary to check for `hp_cur > 0` here?

2023-04-03 14:33 UTC, scarf005 commented on src/bionics.cpp
> +        std::vector<bodypart_id> mending_bp_parts;
i think optaining `bleeding_bp_parts`, `damaged_hp_parts`, and `mending_bp_parts` vector should be done in separate function.

2023-04-03 14:45 UTC, KheirFerrum commented on src/iuse_actor.cpp
> +                damage += part.get_id()->essential * 10;
Damage here is the calculation for priority. Essential is either 1 or 0, this makes it so that parts with the essential flag are treated as 10 points more damaged.

2023-04-03 14:47 UTC, KheirFerrum commented on src/bionics.cpp
> +                    if( hp_cur > 0 && hp_cur < get_part_hp_max( bp ) ) {
Yes. hp_cur == 0 indicates that the limb is broken, normal healing does not work on broken limbs, those require splints or lizard regen.

2023-04-03 14:51 UTC, KheirFerrum commented on src/bionics.cpp
> +        std::vector<bodypart_id> mending_bp_parts;
I think it sort of is? bleeding_bp_parts is updated every 30 turns while damaged_hp_parts and mending_hp_parts are updated every 1 minute. Unless you mean some character specific vector that is updated every turn, which would likely be a bit costly.

2023-04-03 14:52 UTC, KheirFerrum commented on src/bionics.cpp
Don't we want to sort in this scenario since we're going down the list rather than pulling a single limb? Except for bleeding parts.

2023-04-03 22:46 UTC, scarf005 commented on src/bionics.cpp
> +                    if( hp_cur > 0 && hp_cur < get_part_hp_max( bp ) ) {
i think the `hp_cur > 0` should be done using more explicit method like `bool is_limb_broken( const bodypart_id &limb ) const` in `character.h`.

2023-04-03 22:48 UTC, KheirFerrum commented on src/bionics.cpp
> +                    if( hp_cur > 0 && hp_cur < get_part_hp_max( bp ) ) {
Sounds good.

2023-04-03 22:51 UTC, scarf005 commented on src/bionics.cpp
> +        std::vector<bodypart_id> mending_bp_parts;
i mean, the vectors could be initialiazed from separate private member function, for example

```
std::vector<bodypart_id> get_bleeding_bp_parts() const
```

2023-04-09 14:14 UTC, KheirFerrum commented on src/iuse_actor.cpp
> +                damage += part.get_id()->essential * 10;
Placed constant into heal actor.

2023-04-09 15:03 UTC, scarf005 requested changes

2023-04-09 15:03 UTC, scarf005 commented on src/bionics.cpp
> +                        }
```suggestion
                        if( !can_use_bionic() ) {
                            return;
                        }
                        effect &eff = get_effect( effect_mending, bpid->token );
                        eff.mod_duration( eff.get_max_duration() / 100 );
                        mod_power_level( -bio.info().power_trigger );
                        mod_stored_kcal( -bio.info().kcal_trigger );
```
wouldn't it be simpler to [not nest it?](https://www.youtube.com/watch?v=CFRhGnuXG-4)

2023-04-09 15:05 UTC, KheirFerrum commented on src/iuse_actor.cpp
> +                damage += part.get_id()->essential * 10;
Does this work?

2023-04-09 15:07 UTC, scarf005 commented on src/iuse_actor.cpp
> +                damage += part.get_id()->essential * 10;
i guess so, the damage calculation probably needs rework anyway.

2023-04-17 12:27 UTC, scarf005 approved these changes

2023-04-17 12:27 UTC, scarf005 commented on src/bionics.cpp
> +                };
this could be moved next to `threshold_kcal` to reduce nesting.

2023-04-17 12:27 UTC, scarf005 commented on src/bionics.cpp
> +                        return ( get_part_hp_cur( a ) - a->essential * 10 ) < ( get_part_hp_cur( b ) - b->essential * 10 );
a comment with brief explanation on these priorities would be nice.

2023-04-17 12:27 UTC, scarf005 commented on src/creature.cpp
> +    }
```suggestion
    if( got_outer == effects->end() ) {
        return {};
    }
    auto effect_map = got_outer->second;
    std::vector<const effect *> ret;
    for( const auto &[ _, effect ] : got_outer->second ) {
        ret.push_back( &effect );
    }
```
1. early return is preferred. the brace means it's returning [default initialized (empty) vector.](https://stackoverflow.com/a/39487231/13503626)
2. [pair unpacking](https://en.cppreference.com/w/cpp/language/structured_binding) is preferred for better readability.

2023-04-18 21:07 UTC, KheirFerrum commented on src/creature.cpp
> +    }
Personally find this somewhat less comprehensible than the original, but I don't know code.

2023-04-18 22:52 UTC, scarf005 commented on src/creature.cpp
> +    }
maybe it's personal preference, but i suck at comprehending what's `pr` and what's `pr->second`, to the point a spend a few minutes searching through the code what do they mean. i'd rather like them to have explicit name.

2023-04-18 22:55 UTC, KheirFerrum commented on src/creature.cpp
> +    }
I'll get used to it I'm sure.

2023-04-19 00:15 UTC, scarf005 requested changes
![Cataclysm: Bright Nights - cbn-experimental-2023-04-09-1611-16-g053987bd7303_03](https://user-images.githubusercontent.com/54838975/232931060-a1829c11-04f4-470a-aa61-f321ba99a0bb.png)
set both torso and arm's health to 10
confirmed essential part (torso) gets healed first
![Cataclysm: Bright Nights - cbn-experimental-2023-04-09-1611-16-g053987bd7303_04](https://user-images.githubusercontent.com/54838975/232931067-d38c39e8-068e-4cb2-94ea-41918b75e83a.png)
broke an arm, confirmed it does not heal without splints
![Cataclysm: Bright Nights - cbn-experimental-2023-04-09-1611-16-g053987bd7303_05](https://user-images.githubusercontent.com/54838975/232931069-63b59982-0809-4bfe-96df-4cef389feb60.png)
wore splints with CBM turned off, confirmed it does not heal within minutes
![Cataclysm: Bright Nights - cbn-experimental-2023-04-09-1611-16-g053987bd7303_06](https://user-images.githubusercontent.com/54838975/232931072-1df4383a-cd05-41a6-97a9-96e11d80f8c1.png)
wore splints with CBM turned on, confirmed it heals in minute basis. however, i think it should be more explicitly described how it interacts with splints and broken arms.

2023-04-19 00:15 UTC, scarf005 commented on data/json/bionics.json
> +    "description": "Inside your body is a fleet of tiny dormant robots.  While activated they will reduce the intensity of one bleed effect every 30 seconds, and heal all injured body parts by 1 HP (
```suggestion
    "description": "Inside your body is a fleet of tiny dormant robots.  While activated they will reduce the intensity of one bleed effect every 30 seconds, and heal all injured body parts by 1 HP (or broken limbs by 1% if you've put on splints) every minute if you have 3 kJ bionic power and 5 kcal per body part.  If you don't have enough, they will prioritize based on the resources you have.",
```

2023-04-19 00:15 UTC, scarf005 commented on data/json/items/bionics.json
> +    "description": "A fleet of tiny dormant robots.  While activated they will reduce the intensity of one bleed effect every 30 seconds, and heal all injured body parts by 1 HP (or broken limbs by 1
```suggestion
    "description": "A fleet of tiny dormant robots.  While activated they will reduce the intensity of one bleed effect every 30 seconds, and heal all injured body parts by 1 HP (or broken limbs by 1% if you've put on splints) every minute if you have 3 kJ bionic power and 5 kcal per body part.  If you don't have enough, they will prioritize based on the resources you have.",
```

2023-04-19 00:44 UTC, scarf005 approved these changes

2023-04-19 00:44 UTC, merged