Expand message log window to full height
cataclysmbnteam/Cataclysm-BN pull request #2511
Opened 2023-03-31 07:30 UTC by scarf005

#### Summary

SUMMARY: Interface "Expand message log window to full height"

#### Purpose of change

- fixes #2508

#### Describe the solution

made the message dialog use full terminal height (aka `TERMY`)

#### Describe alternatives you've considered

*pain*

#### Testing

![image](https://user-images.githubusercontent.com/54838975/229053013-25dfce4b-dee3-4e9e-a4b6-a89d433060e0.png)

2023-03-31 23:20 UTC, scarf005 commented
spent 3 hours and inputs.h is a pain, i guess toggleable panel could be done in another PR

2023-03-31 23:35 UTC, olanti-p commented
Why would you be looking in `input.h`?

The message window lives entirely in `messages.cpp`, and already defines a bunch of hotkeys. You just have to find the place where it creates its own local `input_context`, see how it defines and then queries actions, and replicate that for your new key.
JSON side of hotkeys lives in `data/raw/`, you can grep for any message window's action id and `input_context` category to see which exact hotkeys correspond to defined actions, and add a new one.

2023-03-31 23:38 UTC, scarf005 commented
...oh wait it was `Messages::dialog::input`

2023-04-03 23:29 UTC, scarf005 commented
@olanti-p, i'm having difficulty toggling then refreshing the window. could you check [b00b5c0](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2511/commits/b00b5c04788380f3b139e1e67d0679e797da3029)? it contains my (failed) attempt to refresh the messages screen.

2023-04-04 10:29 UTC, scarf005 commented
...wait again, nevermind. had a nap and fixed it.

2023-04-04 14:06 UTC, olanti-p commented on src/messages.cpp
> +
This is _way_ over-engineered for a single `wide_display ? std::min( TERMX, static_cast<int>( FULL_SCREEN_WIDTH * 1.5 ) ) : FULL_SCREEN_WIDTH` check, but whatever.

If it's intended to be reusable, it needs to be moved into some related header, not be buried in a random `.cpp` file.

2023-04-04 14:16 UTC, olanti-p commented on src/messages.cpp
> +    ui.mark_resize();
iirc calling this from within `on_resize` callbackis a no-op

2023-04-04 14:18 UTC, scarf005 commented on src/messages.cpp
> +    ui.mark_resize();
i forgot to mention, i just removed them in [cataclysmbnteam/Cataclysm-BN@`85d6367` (#2511)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2511/commits/85d6367175086270f949fa2461113264bbcb1371)

2023-04-04 14:50 UTC, olanti-p commented on src/input.cpp
> +        { PATH_INFO::keybindings_messages(),      false },
Why come up with a new solution when we already have a function for this?

2023-04-04 14:53 UTC, scarf005 commented on src/input.cpp
> +        { PATH_INFO::keybindings_messages(),      false },
uuh, could you help me figure out how to load json files recursively? because i'm having hard time how the data loader does this

2023-04-04 14:58 UTC, olanti-p commented
When I wrote
> would it be possible to make it toggleable?

I was referring to the window height, and to make it expandable, not expanded-by-default. On the screenshot, it's very hard to make out the text or follow what time the messages refer to because of the enormous height.
It's actually tolerable on the more common 1920x1080, so that's a matter of taste I guess.

2023-04-04 15:05 UTC, scarf005 commented
> I was referring to the window height, and to make it expandable, not expanded-by-default.

...oh, i thought you meant about the width. could you clarify how should i change the behavior?
1. expandable width and height.
2. expandable height only.

2023-04-04 23:06 UTC, scarf005 commented
@olanti-p ready to review. now message logs are default collapsed down per your request, and their width and height can be both widened via `w` and `h` shortcut.

2023-04-06 20:23 UTC, olanti-p requested changes
Works nicely. Could you also add a hint for users somewhere?

You could extend the existing hint in `Messages::dialog::show()` e.g. from
```
_( "< Press %s to filter, %s to reset >" )
```
to 
```
_( "< Press %s to filter, %s to reset, %s or %s to adjust size >" )
```

2023-04-06 20:23 UTC, olanti-p commented on data/raw/keybindings/messages.json
> +    "name": "Toggle full height display for messages",
These are local to the message window, they don't need to be so verbose
```suggestion
    "name": "Toggle wide display",
    "bindings": [ { "input_method": "keyboard", "key": "w" } ]
  },
  {
    "id": "TOGGLE_FULL_HEIGHT_DISPLAY",
    "type": "keybinding",
    "category": "MESSAGE_LOG",
    "name": "Toggle full height display",
```

2023-04-06 20:23 UTC, olanti-p commented on src/messages.cpp
> +
That's a good idea to make these persistent, but to avoid them getting reset on restart they should be saved in persistent UI storage (see `uistatedata` in `uistate.h`).

2023-04-06 20:23 UTC, olanti-p commented on src/messages.cpp
> +    w_fh_height = help_text.size() + static_cast<unsigned long>( border_width ) * 2;
1. That `unsigned long` should've been `size_t`. They are not  interchangable since we're dealing with cross-platform code, both types depend on OS and bitness and not always have same size (e.g. Win x64 has 8-byte `size_t` and 4-byte `unsigned long`)
2. Calculating in `int` is preferred in the codebase
3. The value gets implicitly cast back to `int` in this case, so we might as well deal in `int`s 
```suggestion
    w_fh_height = static_cast<int>( help_text.size() ) + border_width * 2;
```

2023-04-06 20:23 UTC, olanti-p commented on src/messages.cpp
>          init( ui );
`set_size` is also called from `init`

2023-04-06 20:23 UTC, olanti-p commented on src/options.cpp
> -#include <locale>
Why remove? It's needed for `std::locale` used here.

2023-04-06 20:39 UTC, scarf005 commented on src/options.cpp
> -#include <locale>
it's duplicate include from line 3.

2023-04-07 16:38 UTC, olanti-p commented on src/uistate.h
> +        bool full_height_display = false;
And here, on the contrary, it should have verbose name because uistate is used by the entire codebase, and there are dozens of UIs in game, so it's unclear which UI this `wide_display` refers to. Something like:
```suggestion
        // Wide and tall display for messages window
        bool msg_window_wide_display = false;
        bool msg_window_full_height_display = false;
```

2023-04-09 05:28 UTC, olanti-p approved these changes

2023-04-09 07:05 UTC, merged