Stop NPCs from using arms to pseudo-block.
cataclysmbnteam/Cataclysm-BN pull request #2535
Opened 2023-04-01 18:59 UTC by KheirFerrum

#### Summary

SUMMARY: Bugfixes "Stop NPCs from using arms to pseudo-block."

#### Purpose of change

#1883 Cancelled the blocking action when NPCs had no arms, but stopped it too late, where `bp_hit` had already been updated to one of the limbs.

As a consequence, NPCs would also always block every single hit to their bodies with their arms even when they should get hit elsewhere.

#### Describe the solution

Rewrites limb selection so `bp_hit` is only updated when there is a viable limb to attack.

#### Describe alternatives you've considered

#### Testing

Spawn NPC, get a baton, reduce their arm HP to half and wail on them until limb breaks (checking that we always use the highest HP limb to block when possible) Check that once arms were broken blocking messages ceased and damage could land on other body parts (damage should still fall on other body parts in between, hence reducing arm HP to half, so we're more likely to break the limbs before any other part)

#### Additional context

2023-04-02 01:26 UTC, scarf005 requested changes

2023-04-02 01:26 UTC, scarf005 commented on src/melee.cpp
> +            block_parts.push_back( bodypart_id( "leg_r" ) );
```suggestion
            block_parts.emplace_back( bodypart_id( "leg_l" ) );
            block_parts.emplace_back( bodypart_id( "leg_r" ) );
```
it's probably be a good idea to use [emplace_back](https://stackoverflow.com/questions/4303513/push-back-vs-emplace-back) where possible.

2023-04-02 01:26 UTC, scarf005 commented on src/melee.cpp
> +            block_parts.push_back( bodypart_id( "arm_r" ) );
```suggestion
            block_parts.emplace_back( bodypart_id( "arm_l" ) );
            block_parts.emplace_back( bodypart_id( "arm_r" ) );
```
same here.

2023-04-02 01:26 UTC, scarf005 commented on src/melee.cpp
>          }
```suggestion
        const auto part_hp_cmp = [this]( const bodypart_id & lhs, const bodypart_id & rhs ) {
            return get_part_hp_cur( lhs ) < get_part_hp_cur( rhs );
        };
        auto healthiest = std::max_element( block_parts.begin(), block_parts.end(), part_hp_cmp );
        if( healthiest == block_parts.end() ) {
            // We have no parts with HP to block with.
            return false;
        }
        bp_hit = *healthiest;
```
it's a small vector but using [max_element](https://en.cppreference.com/w/cpp/algorithm/max_element) would deliver the intent better here.

2023-04-02 01:27 UTC, KheirFerrum commented on src/melee.cpp
>          }
Was wondering if there was a better way to do this.

2023-04-02 01:28 UTC, scarf005 commented on src/melee.cpp
> +            // We have no parts with HP to block with.
```suggestion
            // We have no parts with HP to block with.
            blocks_left = 0;
```
...oops, forgot to add this here.

2023-04-02 01:30 UTC, scarf005 approved these changes
wish damge log showed which part got hit, but each damage seems to hurt other limbs now.

2023-04-02 01:40 UTC, KheirFerrum commented
> wish damge log showed which part got hit, but each damage seems to hurt other limbs now.

We could code that to be fair. `dealt_dam` has a `bp_hit` field that tracks the body part hit. We'd just have to figure out how it displays for monsters and animals that don't have body parts.

2023-04-02 01:45 UTC, KheirFerrum commented on src/melee.cpp
>          }
Something weird about this implementation. The prior implementation had hits still strike other NPC body parts, this one still focuses on the blockable parts.

2023-04-03 11:25 UTC, scarf005 commented
damage log code is even more spaghettier than i ever thought...

2023-04-03 11:25 UTC, merged