refactor: fahrenheit to celsius in codebase
cataclysmbnteam/Cataclysm-BN pull request #2570
Opened 2023-04-05 02:57 UTC by scarf005

- refactor: constexpr for `TOOL_LIFT_FACTOR` and `JACK_LIMIT`
- feat: add long double override for celsius literal
- refactor: use celsius on namespace `termperatures`
- refactor: `average_annual_termperature` to `units::temperature`

#### Summary

SUMMARY: Infrastructure "[Briefly describe the change in these quotation marks]"

Do not enter the square brackets [].  Category must be one of these:

- Features
- Content
- Interface
- Mods
- Balance
- Bugfixes
- Performance
- Infrastructure
- Build
- I18N

For more on the meaning of each category, see:
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/master/doc/CHANGELOG_GUIDELINES.md

If approved and merged, your summary will be added to the project changelog:
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/master/data/changelog.txt
-->

#### Purpose of change

- fixes #2569 

#### Describe the solution

- use `_c` user defined literal to use celsius everywhere.

#### Describe alternatives you've considered

#### Testing

#### Additional context

2023-04-05 16:16 UTC, LiteralMushroom commented
ok but if temperature displays anywhere in game (I don't know if it does or not) let people choose to see it in Fahrenheit

2023-04-05 16:20 UTC, chaosvolt commented
> ok but if temperature displays anywhere in game (I don't know if it does or not) let people choose to see it in Fahrenheit

Already a thing, if you have a thermometer it will show the ambient temp, and interface settings allow you to pick what unit it'll show as. PR's focus is on changing what unit it works with under the hood, which is then converted for display.

2023-04-05 16:27 UTC, Coolthulhu commented on src/character.cpp
> +        100 * weather.get_water_temperature( pos() ).value();
Would be better if you used explicit `units::to_millidegree_celsius` and then divided that by 10.

2023-04-05 16:29 UTC, Coolthulhu commented on src/suffer.cpp
> +void Character::apply_wetness_morale( const units::temperature &celsius_temperature )
No need for `celsius` in name now.

2023-04-05 16:29 UTC, Coolthulhu commented on src/suffer.cpp
> +    int temperature = units::celsius_to_fahrenheit( celsius_temperature.value() );
Avoid `.value()` where possible. Also, `units::to_fahrenheit`.

2023-04-05 16:32 UTC, Coolthulhu commented on tests/player_test.cpp
> +        get_weather().temperature = units::from_fahrenheit( i );
The tests will need to be rebuilt anyway, since the values will differ. Conversion to Fahrenheit would cause rounding, so you could change it to just `i * 500_mC` instead.

2023-04-05 16:36 UTC, Coolthulhu commented on src/gamemode_defense.cpp
> +    get_weather().temperature = SPRING_TEMPERATURE;
Not caused here or anything like that, but nowadays our "effective spring temperature" is taken from json. In the future, this should be something like `get_weather().recalculate()`.

2023-04-06 15:18 UTC, scarf005 commented on tests/player_test.cpp
> +        get_weather().temperature = units::from_fahrenheit( i );
got
```
In template: static assertion failed due to requirement 'quantity_details<temperature_in_millidegree_celsius_tag>::integral_constant<bool, false>::value': Units with multiple scales with different zero should not be multiplied/divided/etc.  directly.
```
used easy workaround `units::from_millidegree_celsius( i * 500 )`.

2023-04-06 15:22 UTC, scarf005 commented on src/gamemode_defense.cpp
> +    get_weather().temperature = SPRING_TEMPERATURE;
could you point out the part where weather_manager loads spring temperature from JSON? i couldn't find `serialize` or `deserialize` member function in `weather_manager` class.

2023-07-15 17:40 UTC, Coolthulhu commented
I'm having test failures due to one off rounding in the `rot_test.cpp`:
```
../tests/rot_test.cpp:52: FAILED:
  REQUIRE( weather.get_temperature( tripoint_zero ) == Approx( 65 ) )
with expansion:
  64 == Approx( 65.0 )
```

There is some conflict in `character.h` now.

2023-07-16 06:12 UTC, scarf005 commented
Two tests still fail, not sure if it's just acculmulated errors from conversion or something worse

```
/home/scarf/repo/cata/Cataclysm/tests/iteminfo_test.cpp:43: FAILED:
  CHECK( info == reference )
with expansion:
  "--
  * This food is <color_c_yellow>perishable</color>, and at room temperature
  has an estimated nominal shelf life of <color_c_cyan>1 day</color>.
  * Current storage conditions <color_c_yellow>partially</color> protect this
  item from rot.  It will stay fresh at least <color_c_cyan>3 days</color>.
  * This food looks as <color_c_green>fresh</color> as it can be.
  "
  ==
  "--
  * This food is <color_c_yellow>perishable</color>, and at room temperature
  has an estimated nominal shelf life of <color_c_cyan>1 day</color>.
  * Current storage conditions <color_c_yellow>partially</color> protect this
  item from rot.  It will stay fresh at least <color_c_cyan>4 days</color>.
  * This food looks as <color_c_green>fresh</color> as it can be.
  "
with messages:
  escape_newlines( info ) := "--\n
  * This food is <color_c_yellow>perishable</color>, and at room temperature
  has an estimated nominal shelf life of <color_c_cyan>1 day</color>.\n
  * Current storage conditions <color_c_yellow>partially</color> protect this
  item from rot.  It will stay fresh at least <color_c_cyan>3 days</color>.\n
  * This food looks as <color_c_green>fresh</color> as it can be.\n
  "
  escape_newlines( reference ) := "--\n
  * This food is <color_c_yellow>perishable</color>, and at room temperature
  has an estimated nominal shelf life of <color_c_cyan>1 day</color>.\n
  * Current storage conditions <color_c_yellow>partially</color> protect this
  item from rot.  It will stay fresh at least <color_c_cyan>4 days</color>.\n
  * This food looks as <color_c_green>fresh</color> as it can be.\n
  "
```
```
-------------------------------------------------------------------------------
Rate of rotting
  Passage of time
-------------------------------------------------------------------------------
/home/scarf/repo/cata/Cataclysm/tests/rot_test.cpp:32
...............................................................................

/home/scarf/repo/cata/Cataclysm/tests/rot_test.cpp:72: FAILED:
  CHECK( to_turns<int>( normal_item.get_rot() ) == Approx( to_turns<int>( 20_minutes ) ).epsilon( 0.01 ) )
with expansion:
  1,149 (0x47d) == Approx( 1,200.0 )
with message:
  Initial turn: 60
```

2023-08-01 17:51 UTC, Coolthulhu commented
```
/home/scarf/repo/cata/Cataclysm/tests/rot_test.cpp:72: FAILED:
  CHECK( to_turns<int>( normal_item.get_rot() ) == Approx( to_turns<int>( 20_minutes ) ).epsilon( 0.01 ) )
with expansion:
  1,149 (0x47d) == Approx( 1,200.0 )
```

This is a pretty serious discrepancy.

2023-08-27 07:11 UTC, scarf005 commented
https://github.com/scarf005/Cataclysm-BN/blob/a1081ecec77b583beb18451eef070b8b6e4ecbe6/src/game_constants.h#L92-L96

I think this is due to temperature `cold` and `fridge` getting 'hotter':

- fridge: ~2.7C -> 3C
- cold: ~4.4C -> 5C

2023-08-29 00:31 UTC, scarf005 commented
chose dumb solution by 
1. lower fridge temp to 2C
2. hardcode rot values (it was only 43)

2023-09-01 21:23 UTC, olanti-p requested changes

2023-09-01 21:23 UTC, olanti-p commented on src/weather.cpp
> +    if( you.is_wearing_power_armor( &has_helmet ) && ( has_helmet || !one_in( 2 ) ) ) {
This condition looks cursed...

2023-09-01 21:23 UTC, olanti-p commented on src/item.cpp
>   */
Outdated comment:
1. There's no "calculation" going on anymore, it's plain hardcoded lookup table
2. References removed functions
3. Comments describing changes in a PR or commit should stay in PR body or commit message, people stumbling on it in the future won't understand how it's relevant to how the code works

2023-09-01 21:23 UTC, olanti-p commented on src/item.cpp
> +{
Does this need a anonymous namespace?

2023-09-02 02:19 UTC, scarf005 commented on src/weather.cpp
> +    if( you.is_wearing_power_armor( &has_helmet ) && ( has_helmet || !one_in( 2 ) ) ) {
it indeed is, however it's quite convoluted, would be better made a separate PR
also i have a feeling power armors should be JSONized in the future

2023-09-02 02:27 UTC, scarf005 commented on src/item.cpp
> +{
- it was [recommended by clang-tidy](https://releases.llvm.org/16.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/misc/use-anonymous-namespace.html)
- makes meaning of `static` more clear as now it only means static lifetime, not 'only visible to same translation unit'
- better readability (subjective)

2023-09-17 19:10 UTC, olanti-p requested changes

2023-09-17 19:10 UTC, olanti-p commented on src/weather.cpp
> +    const int temp = ( location.z < 0 ? units::to_fahrenheit( temperatures::annual_average ) :
Looks like that comment was outdated even before the PR, should be removed.

2023-09-21 13:32 UTC, olanti-p approved these changes

2023-09-21 13:43 UTC, merged