Enable AoE cone for shotgun shot ammo
cataclysmbnteam/Cataclysm-BN pull request #2619
Opened 2023-04-11 17:44 UTC by Firestorm01X2

#### Summary
SUMMARY: Features "Enable AoE cone for shotgun shot ammo"

#### Purpose of change
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1118
AoE featue was implemented almost 2 years ago but only for birdshot. It is time to actually give feature a try.

#### Describe the solution
Add AoE effect for shot-like shells.
I've had to add to abstract type of ammo simply because "delete" does not work for "shape".
Max range of cone should loosely match previous range. Dragon breath, however has range 8 instead of 6 to make cone look better.

#### Describe alternatives you've considered
Forget about feature with risk of regression and forgetting the feature.

#### Testing
1) Test various type of  shot-like shotgun ammo
2) It should use cone of fire.

#### Additional context
Forget about feature with risk of regression and forgetting the feature.

2023-04-11 20:51 UTC, scarf005 reviewed
looks great! quick questions:
1. would it be possible to implement delete for shapes? if so, would it be better than using abstract?
2. could you add screenshot/video for firing each affected ammos?

2023-04-12 09:09 UTC, scarf005 reviewed
can't review rn, but the numbers look good. will review after playtesting at home.

2023-04-13 10:40 UTC, scarf005 requested changes
following buckshots are missing AOE:
- 20x66mm buckshot
- 20x66mm buckshot, handmade

all flechettes are missing AOE except these three:
- flechette shell
- flechette shell, black powder
- flechette shell, reloaded

could you also handle these cases?

2023-04-13 10:40 UTC, scarf005 commented on data/json/items/ammo/shot.json
> +    "id": "shot_abstract",
this field should be made [`"abstract"`](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/doc/JSON_INHERITANCE.md) to prevent it from spawning.

2023-05-01 17:59 UTC, Firestorm01X2 commented
> * would it be possible to implement delete for shapes? if so, would it be better than using abstract?

Done


> * could you add screenshot/video for firing each affected ammos?

Thats looks like overkill. Instead I've provided saves for quicker testing

2023-05-02 09:02 UTC, scarf005 approved these changes
LGTM. i've also marked 20x66_shot_abstract as abstract, and added aoe cone for blunderbus shots as well.

![Cataclysm: Bright Nights - cbn-experimental-2023-05-01-1231_01](https://user-images.githubusercontent.com/54838975/235624806-a6222507-1fd1-4d79-a431-5ecfbca9bc51.png)
blunderbuss flechette (half angle: 10, length: 12)
![Cataclysm: Bright Nights - cbn-experimental-2023-05-01-1231_02](https://user-images.githubusercontent.com/54838975/235624816-d93d026f-dd42-4aef-91c4-71755cc429e9.png)
blunderbuss shot (half angle: 18, length: 10)

https://user-images.githubusercontent.com/54838975/235624785-44b5dce8-fa06-4a99-8b1b-50daa76f45d1.mp4
fun with shotshells

2023-05-02 09:22 UTC, merged