Let Slings and Staff Slings Use Rocks and Pebble Ammo Types, Plus New Sling Bullet Ammo
cataclysmbnteam/Cataclysm-BN pull request #2709
Opened 2023-04-26 03:59 UTC by yay855

#### Summary

SUMMARY: Content "Changed sling and staff sling to be capable of using both rocks and pebbles as ammo, as well as added in new 'sling bullet' and 'small sling bullet' ammo as a higher-end lead ammo for slings and staff slings."

#### Purpose of change

Slings have been used to huck larger rocks historically, and staff slings are just a sling on the end of a staff. Furthermore, lead sling bullets are historically accurate and would serve as a nice alternative to ball bearings.

#### Describe the solution

It's a minor change to two items, two new items, and two new recipes.

#### Describe alternatives you've considered

You could keep the staff sling and sling as using rocks and pebbles respectively, but it's kind of a strange distinction to begin with.

#### Testing

I've made sure there are no json errors and it seems fairly balanced in terms of stats and crafting.

2023-04-26 05:55 UTC, chaosvolt commented on data/json/items/ammo.json
> +    "description": "A ball of lead roughly the size of a baseball. Traditionally thrown from a sling, and hits a lot harder than any old rock.",
```suggestion
    "description": "A ball of lead roughly the size of a baseball.  Traditionally thrown from a sling, and hits a lot harder than any old rock.",
```

2023-04-26 05:56 UTC, chaosvolt commented on data/json/items/ammo.json
> +    "description": "A small ball of lead traditionally thrown from a sling. It hits a lot harder than any old pebble.",
```suggestion
    "description": "A small ball of lead traditionally thrown from a sling.  It hits a lot harder than any old pebble.",
```

2023-04-26 05:57 UTC, chaosvolt commented on data/json/recipes/ammo/other.json
> +    "time": "1 h",
Both these recipes can probably be made more granular, divided up to make 1 charge at a time for proportionately less time and material cost.

2023-04-26 06:05 UTC, yay855 commented on data/json/recipes/ammo/other.json
> +    "time": "1 h",
I intended to keep it at the same standard for ball bearings where you made a bunch at once, but that's probably a good idea.

2023-04-26 07:28 UTC, scarf005 requested changes

2023-04-26 07:31 UTC, yay855 commented
Sheesh. I keep screwing this stuff up. I appreciate the help, guys.

2023-04-27 01:31 UTC, chaosvolt commented on data/json/items/ammo.json
> +    "weight": "28 g",
50 units of lead per charge of `sling_bullet` would be 150 grams. Even then that's pretty light compared to regular rocks being 657 grams. But then again that's way over a whole pound, so honestly going for a value in the neighborhood of 150 grams and 50 ml would be good enough to match the lead item's density without having to tweak the recipe any further.

2023-04-27 01:36 UTC, chaosvolt commented on data/json/items/ammo.json
> +    "weight": "12 g",
Similar deal with the other item, recipe uses 150 grams of lead to make 6 shots, so would make sense to use 25 grams as weight. Possibly dragging `count` down to only 30, so a stack of 250 ml weights 750 grams (again making it consistent with lead itself).

2023-04-27 02:07 UTC, chaosvolt approved these changes
Bug reported in previous review got fixed so dunno why it's still showing as changes requested, guess I can mark it as dismissed or whatever's needed to clear it.

1. Load-tested JSON changes in compiled test build.
2. Spawned in pebbles, rocks, and both sizes of sling bullet.
3. Spawned a sling and staff sling, confirmed that both can load all four ammo items.

Ranges also match that of pebbles and rocks, but honestly it's already weird that pebbles and rocks also have the exact same range so I feel like that's a completely separate issue anyway. Looks good to me.

2023-04-27 02:10 UTC, scarf005 approved these changes
![image](https://user-images.githubusercontent.com/54838975/234741898-3a58952b-dd8e-4cb9-a696-9b47b8ffbbab.png)

hecc, i _was_ going to approve it but was carried away doing other things while automated tests were running. i also approve this change. balance can be always addressed later, and new contents are good.

2023-04-27 02:11 UTC, chaosvolt commented
No worries. Will merge once it shows all green just in case I missed anything then, so long as lightning continues to fuck off and not affect my power or net. >:C

2023-04-27 02:14 UTC, merged

2023-04-27 02:48 UTC, scarf005 commented
oh hecc, forgot to mention without `"looks_like"` field they will use ASCII tiles
nevermind, i'll add a followup PR