Unarmed weapons expansion
cataclysmbnteam/Cataclysm-BN pull request #2715
Opened 2023-04-27 03:38 UTC by yay855

#### Summary

SUMMARY: [Features] "Expanded number of readily available to craft unarmed weapons"

#### Purpose of change

The list of unarmed weapons in the early and mid game is sadly quite small. These are some items I made for my mod and which I've decided to try and port to mainline, as well as making some of the vanilla ones autolearn.

#### Describe the solution

It's a series of unarmed weapons, each serving a different purpose for combat relative to the punch dagger- the sai is lower damage but higher defense, the spiked boxing gloves are good for earlygame, and the katar has higher damage but is larger and swings slower. I've also made some of the vanilla items easier to craft, since they're really not that complicated and shouldn't require a book to know how to make them. Furthermore, the razorbar katar and cestus are both relatively simple weapons to make and shouldn't require a book to know how to make them.

#### Describe alternatives you've considered

The main issue is that I want to balance the stats right, and I'm not quite sure how to do it better than this. Advice would be appreciated.

#### Testing

The new weapons and changed recipes are both from my mod, so I've tested them quite a bit.

2023-04-27 03:43 UTC, chaosvolt commented
Easy enough to lintfix these, can run file contents through this next time you need it: http://dev.narc.ro/cataclysm/format.html

2023-05-03 18:03 UTC, chaosvolt commented on data/json/items/melee/unarmed_weapons.json
> +    "price": 4500,
```suggestion
    "price": "45 USD",
     "price_postapoc": "450 cent",
```
String prices aren't really mandatory, just included it in the process of adding a suggestion for fixing lack of barter value.

2023-05-03 18:04 UTC, chaosvolt commented on data/json/items/melee/unarmed_weapons.json
> +    "price_postapoc": 500,
```suggestion
    "price": "500 USD",
    "price_postapoc": "5 USD",
```

2023-05-03 18:05 UTC, chaosvolt commented on data/json/items/melee/unarmed_weapons.json
> +    "price": "220 USD",
```suggestion
    "price": "220 USD",
    "price_postapoc": "4 USD",
```

2023-05-04 07:20 UTC, chaosvolt requested changes

2023-05-04 07:20 UTC, chaosvolt commented on data/json/items/melee/unarmed_weapons.json
> +    "price_postapoc": "5 USD",
```suggestion
    "name": { "str": "katar" },
    "copy-from": "knuckle_katar",
    "description": "A steel brace with a metal blade at the end, designed to allow the user to stab and slash with the same motions as a punch.",
    "material": [ "steel" ],
    "volume": "750 ml",
    "cutting": 20,
    "price": "500 USD",
```
Just realized this doesn't have a weight attached, setting it to copy from the razor katar will alllow re-using the symbol, color, post-apoc price, and weight along with gaining its baseline bash damage (likely for the best since its damage over the punch dagger's total is only 4 points) and blocking technique.

2023-05-04 15:31 UTC, chaosvolt submitted a review, later dismissed

2023-05-05 03:23 UTC, scarf005 requested changes
looks good, some of my nitpicks:
1. there's an recipe for spiked boxing gloves yet no recipe for regular boxing gloves. this could be solved by
- adding recipe for gloves
- changing recipe for spiked boxing gloves as `boxing glove + 8 nails`

2. sai and katar takes too much metal to craft.

|            | tanto | katar | sai  |
| ---------- | ----- | ----- | ---- |
| weight     | 560g  | 1150g | 775g |
| fab. lv    | 7     | 7     | 6    |
| steel lump | 1     | 3     | 2    |

could you decrease metal requirement from `3 -> 2` for katar and `2 -> 1` for sai?

other than that, i think it's a great addition.
![Cataclysm: Bright Nights - cbn-experimental-2023-05-04-0526-8-g718e52ebae4_12](https://user-images.githubusercontent.com/54838975/236371419-e3f96aea-1337-413f-9b51-cec7e83ccef3.png)
~~sai looks super weird on ground tho~~

2023-05-05 03:35 UTC, chaosvolt commented
Sai is clearly being screwed up by the graphical overmap tile for the sai telecom areas it seems. Easy fix would be changing the weapon's ID a lil. Also side note, the katar's weight is currently same as the makeshift one so it could be changed in any particular direction desired, the previous tweak suggested was just a quickfix to it being weightless and missing some properties.

2023-05-11 04:43 UTC, scarf005 approved these changes

2023-05-11 04:43 UTC, merged