Updates to low-tier wooden weapons
cataclysmbnteam/Cataclysm-BN pull request #2885
Opened 2023-05-26 10:17 UTC by chaosvolt

#### Summary

SUMMARY: Balance "Rebalance 2-by-sword and nail sword, add long pointy stick"

#### Purpose of change

Per some discussion in the BN discord.

#### Describe the solution

1. Moved the 2-by-sword and nail sword into the sword file, as it's a bit weird having the sword-like objects divided up like this, plus they're getting some related stat changes that will make their damage weight less towards bashing.
2. Changed the 2-by-sword's damage from 12/1 to 4/10, and gave it stabbing damage instead of cutting. Rationale being to balance it relative to the comparably easy to make pointy stick (where it skews slightly less damaging but with faster attacks) as well as give it a bit more to contrast with the cudgel. Stab damage is because you're more likely to be thrusting with the sharpened tip.
3. Likewise, changed the nail sword to 4/14 damage. Much like the barbed wire and nail bats, idea here is it has close enough weight to retain the same bashing damage, but gains more stab damage from swinging an "edge" made of nails. Also changed name from nord to nail sword for more consistency when searching the crafting menu, fixed up the description a bit, and set it so it doesn't magically gain an extra point of to-hit over the similar 2-by-sword and crude sword.
4. Per suggestion, removed the `DURABLE` flag from cudgels. You're taking a not-durable piece of wood and carving it down to a singlestick without any reinforcement or other treatment.
5. Added item and recipe definitions for long pointy sticks. It was also remarked that having a super no-frills reach weapon with lower effectiveness than the proper fire-hardened wooden spear might be good. Weight/volume based off the difference between heavy stick and wooden stick, extrapolated to the long stick, while stats give it the same stabbing damage as the pointy stick but a bit more bashing damage. This makes its total damage higher than the wooden spear, but its damage per turn is overall worse since it's much heavier and it gains no to-hit bonus.

#### Describe alternatives you've considered

1. Some form of trench club may also be a viable addition.
2. Also, going the fuck back to sleep and not doing late-night contributions on the laptop.

#### Testing

Checked affected files for syntax and lint errors.

#### Additional context

I think DDA might have a long pointy stick item too but didn't double-check.

2023-05-27 00:20 UTC, scarf005 reviewed
could you use markdown table to describe stat changes?

2023-05-27 00:49 UTC, chaosvolt commented
> could you use markdown table to describe stat changes?

Item | Bash | Cut/Stab Damage | To-Hit
--- | --- | --- | ---
2-By-Sword | 12 **-> 4** | 1 **-> 10** | +1
Nail Sword | 12 **-> 4** | 4 **-> 14** | +2 **-> +1**
Crude Sword | 6 | 14 | +1

2023-05-29 11:45 UTC, scarf005 commented on data/json/items/melee/swords_and_blades.json
> +    "weight": "648 g",
hecc

2023-05-29 11:53 UTC, scarf005 requested changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2fe7b977-d4ea-4772-964d-e2f96193a8fe)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/333131f8-ae18-4d7f-b50a-831594dd90a7)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/ba807d59-81b3-4e99-aef3-a22dcd56d841)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/73b0e997-39ec-4a22-bb3f-dab31d3b75fa)

while i'm okay with the changes, i'm not sure if `"flags": [ "STAB" ]` is intentional. if so, it needs to be documented.

2023-05-29 11:53 UTC, scarf005 commented on data/json/items/melee/swords_and_blades.json
> +    "delete": { "flags": [ "STAB" ] }
```suggestion
    "qualities": [ [ "BUTCHER", -50 ] ]
```
`STAB` flag is not in neither documentation nor in `sword_wood`. i think this line is added as a mistake?

2023-05-29 11:53 UTC, scarf005 commented on data/json/items/melee/swords_and_blades.json
> +    "weight": "648 g",
```suggestion
    "weight": "650 g",
```
i get that 4g(nail) * 12 = 48g but maybe it could be rounded to be more visually pleasing

2023-05-29 15:36 UTC, chaosvolt commented on data/json/items/melee/swords_and_blades.json
> +    "delete": { "flags": [ "STAB" ] }
> Changed the 2-by-sword's damage from 12/1 to 4/10, and gave it stabbing damage instead of cutting. 

Double-check again, `sword_wood` was given the stag flag and its description emphasizes the whole "it's pointy" thing. See also why its stats are specially balanced with the pointy stick in mind.

2023-05-29 16:05 UTC, scarf005 approved these changes

2023-05-30 02:14 UTC, merged