Use bismuth in recipes, related ammo fixes
cataclysmbnteam/Cataclysm-BN pull request #2952
Opened 2023-06-10 05:11 UTC by chaosvolt

#### Summary

SUMMARY: Balance "Allow using bismuth in some recipes, related ammo fixes"

#### Purpose of change

I noticed that bismuth was fairly lacking in recipe use, when its use as a lead substitute for bullets is fairly common.

#### Describe the solution

1. Added bismuth to `ammo_bullet` crafting requirement, requiring 3 units (total 6 weight) per 1 unit (5 weight) of lead.
2. Added bismuth to `weights` crafting requirement, requiring 8 units (total 16 weight) per 5 units (15 weight) of lead.
3. Added bismuth to sling bullet recipes, requiring 125 units per 50 units of lead (actually matching in weight for once).
4. Fixed recipe for blackpowder .45-70 requiring some extra lead on top of calling for `ammo_bullet` already, despite being basically the cowboy load but with blackpowder.
5. Misc: Fixed some weirdness where for some reason the item entry for blackpowder .45-70 was in the uncraft file instead of where it belongs.

#### Describe alternatives you've considered

Not doing this for bullets because most of the items still rely on uncrafts instead of reversible recipes, meaning this can technically transmute bismuth into lead (at some loss of mass) if you intentionally craft handloads then take them apart for whatever reason.

#### Testing

Checked affected files for syntax and lint errors.

#### Additional context

2023-06-14 07:26 UTC, RoyalFox2140 requested changes
We should perhaps expand the scope with the comment I left about copper, zinc and steel as alternatives to lead.

2023-06-14 20:56 UTC, RoyalFox2140 commented on data/json/recipes/ammo/other.json
https://youtu.be/3Njddshr3n8?t=339 I mean if we went full realism aluminum can work with a lot of effort.

2023-06-14 23:55 UTC, chaosvolt commented on data/json/recipes/ammo/other.json
Whichever works, yeah. Will have to tinker with adding more materials when I get home.

2023-06-20 00:57 UTC, scarf005 commented
@RoyalFox2140 maybe we could do it in multiple PRs, i.e
1. allow bismuth
2. allow others?

2023-06-20 00:59 UTC, chaosvolt commented
Oh right, hadn't gotten the chance to tinker with adding more. I figure bismuth is probably a good no-brainer start for now, others later perhaps. Plus one complication is the whole transmutation-of-bismuth-into-lead thing due to uncrafts, this would get more noticeable and more weird the more metals are allowed...

2023-06-22 20:32 UTC, scarf005 approved these changes

2023-06-23 06:31 UTC, merged