build: migrate clang-tidy to LLVM 16
cataclysmbnteam/Cataclysm-BN pull request #3028
Opened 2023-07-22 12:07 UTC by scarf005

#### Summary

SUMMARY: Infrastructure "DDA Port: migrate clang-tidy plugin to LLVM 16"

#### Purpose of change

Make it easier to get custom clang-tidy plugin easier on local environment.

#### Describe the solution

ported following PRs: 

- https://github.com/CleverRaven/Cataclysm-DDA/pull/65381
- https://github.com/CleverRaven/Cataclysm-DDA/pull/56506

all credits to: @BrettDong @jbytheway @Qrox 

#### Describe alternatives you've considered

RIIR

#### Testing

checked that local build passes.
will do a manual one after i rebuild all the files (plugin won't load due to llvm version mismatch)

2023-07-22 13:56 UTC, Qrox commented
You might want to also apply CleverRaven/Cataclysm-DDA#66315 and CleverRaven/Cataclysm-DDA#66538 which are follow-ups to CleverRaven/Cataclysm-DDA#65806.

2023-07-22 15:29 UTC, scarf005 commented
thank you! will try tomorrow

2023-07-25 20:35 UTC, olanti-p requested changes
Some checks definitely need to be disabled. The tidy runner seems to be timing out because of the sheer amount of new warnings.

2023-07-25 20:35 UTC, olanti-p commented on build-scripts/build.sh
> +        compiledb -n make
`compiledb` shouldn't be needed anymore, see #2474

2023-07-25 20:35 UTC, olanti-p commented on .github/workflows/clang-tidy.yml
> +    - '.github/workflows/clang-tidy.yml'
Why remove `tools/clang-tidy-plugin/` and others?

2023-07-25 20:35 UTC, olanti-p commented on .github/workflows/clang-tidy.yml
> +          paths: '[ "**.cpp", "**.h", "**.c", "**/CMakeLists.txt", "**/Makefile", "**.hpp", "**.cmake", "build-scripts/clang-tidy.sh", "build-scripts/clang-tidy-wrapper.sh", "build-scripts/get_affect
Same here

2023-07-25 20:35 UTC, olanti-p commented on build-scripts/clang-tidy.sh
> +compiledb -n make
Same here, at line 33 cmake is invoked with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/HeaderGuardCheck.cpp
> +        if( pathExists( TopDir + "/.travis.yml" ) || pathExists( TopDir + "/CMakeCache.txt" ) ) {
We don't have travis anymore, this part should be reverted

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/JsonTranslationInputCheck.cpp
> +                                        "_", "translation_argument_identity", "pgettext" )
Why remove? We have `vgettext` and `vpgettext` as alternatives to `n_gettext` and `npgettext`.

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/NoStaticTranslationCheck.cpp
> +                            hasAnyName( "_", "translation_argument_identity", "gettext", "pgettext" )
Same here.

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/TranslateStringLiteralCheck.cpp
> +                                            "pgettext"
Same here.

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/TranslatorCommentsCheck.cpp
> -    );
And here.

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/TranslatorCommentsCheck.cpp
> -    );
And here.

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/test/translator-comments.cpp
> -    vgettext( "bar", "baz", 1 );
And here.

2023-07-25 20:35 UTC, olanti-p commented on tools/clang-tidy-plugin/test/translator-comments.cpp
> -
And here.

2023-08-06 02:17 UTC, scarf005 commented on .github/workflows/clang-tidy.yml
> +    - '.github/workflows/clang-tidy.yml'
must've overwritten accidentally.

2023-08-17 12:53 UTC, scarf005 commented
@olanti-p maybe we could merge the PR, turn off clang-tidy lint action for a week while opening PRs with `clang-tidy --fix` applied? maybe after merging #2216 and #2250?

2023-08-17 14:15 UTC, olanti-p commented
Why disable entire clang-tidy action, if you can just disable the offending lints?

2023-08-17 20:28 UTC, scarf005 commented
tidy was running on every source file, causing timeout.

2023-09-27 15:41 UTC, scarf005 commented
> tidy was running on every source file, causing timeout. that said, i should fix that.

and i can't still figure out how.

2023-10-03 05:18 UTC, scarf005 commented
> and i can't still figure out how.

found out the curprit, fixed in [`516071e` (#3028)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3028/commits/516071e4931c3e7ce0fa1aa91aceadd529874320)

2023-10-03 16:38 UTC, scarf005 commented
temporarily disabled 'check all affected files' for now (three header changed in this PR affects entire .cpp)

2023-10-05 00:49 UTC, olanti-p requested changes
It doesn't seem to work at all now.

2023-10-05 00:54 UTC, scarf005 commented
aww, fixed. do you think it'd be ok to temporarily disable checking all affected source files and only run clang-tidy on changed files?

2023-10-05 03:42 UTC, olanti-p commented
If you mean, disable checking `.cpp`s if they were not changed but include a header that was changed, then no, it won't work this way.

C++ compilers (and clang-tidy checks by extension) need the entire preprocessed file to work with, and preprocessed file is created from `.cpp` and all its `#include`d headers + defines passed to the compiler.

If that "affected files" check was disabled, then one PR could introduce error in header file that's only apparent when analyzing together with relevant .cpp, but CI would accept that, and then some other PR that happens to (correctly) modify that .cpp in a different place would trigger the check and get yelled at for no reason.

2023-10-05 03:49 UTC, olanti-p commented
As I've mentioned before, you should start with fixing and/or disabling the checks added in this PR. If you check the build logs, the new checks spew billions upon billions of repeating errors, so it's quite possible the build times out simply because clang spends most of the time formatting error output.

BN builds 2-3 times faster than DDA, I say it's safe to expect our tidy could also run 2-3 times faster.

2023-10-05 03:51 UTC, scarf005 commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/760c8945-5db1-4c3b-8858-bec3eac116be)

a few days ago i tried disabling all new checks and still stumbled across 360m limit, as `point.h`, `make_static.h`, `translations.h` affected entire codebase. let's try again...

2023-10-07 11:54 UTC, scarf005 commented
every new checks are disabled but it still hits time limit. this time limit hit is specifically caused due to [changes in aforementioned 3 headers](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3028#issuecomment-1747992630). which caused clang-tidy to run checks for every source files.

i think this PR should be merged despite that, as 
- [affected file tracing behavior is kept back](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3028/commits/c12cf758e15191dccb2de4904934f74fdcd79b5e)
- it's planned to open followup PRs with running clang-tidy.

2023-10-07 17:28 UTC, olanti-p commented
I strongly disagree.

Tidy job works fine, while this PR in its current state breaks it completely.

Running tidy locally should not be a priority over running it in CI, because nobody runs it locally except when they're working on some tidy issue, but CI runs it for all C++ changes.

There's no immediate need to upgrade to tidy + LLVM 16, this PR is not a blocker for anything, it should be a self-contained upgrade, not downgrade.

If you claim you've disabled all the new checks and still it times out, takes more than 6 hours to complete, but at the current state of things tidy works and takes less than 2 hours _for the entire run on all files_, where does the >3 times increase come from?

2023-10-18 01:12 UTC, scarf005 commented
keeping it draft until #2250 to reduce cognitive load

2024-10-05 14:38 UTC, closed without merging