Exertion effects now consider tool quality part 2: shovels
cataclysmbnteam/Cataclysm-BN pull request #3042
Opened 2023-07-31 00:40 UTC by chaosvolt

#### Summary

SUMMARY: Balance "Tool quality and other time-saving factors now impact fatigue and other needs penalties from digging"

#### Purpose of change

A belated followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2755 and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2617 that I'd been meaning to do, this sets it so that the fake-exertion effects from digging pits is naturally calculated from time taken to dig, thus making it so that better tools, more strength, better helpers etc all modify how much fatigue, thirst, etc digging inflicts on you.

WIP because I need to also apply this to the other digging-related functions in the relevant file, re-test, then check for astyle, but wanted to make sure the basic method worked first then test something else right quick.

#### Describe the solution

In activity_actor.cpp, set it to define the now-familiar act_exertion int using the total_moves of the assigned digging activity, and have it calculate kcal reduction, thirst increment, and fatigue increment using it. This works in the exact same way as the calculations used in woodcutting since both activities treat 60 minutes as the baseline time.

Main difference is I figured out I can use the total moves of the activity instead of having to recreate chop_moves like I did in the previous PR. This not only saves me some redundant definitions in the finisher function, but also means not having to assign the tool used for the activy to look up later, thus avoiding problems like https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3015 wherein I fucked up and forgot that the NPC version of the activity needs to remember the item used too.

#### Describe alternatives you've considered

1. Backporting this use of `moves_total` to the woodcutting function for yet another PR messing with it.
2. Porting DDA's exertion mechanics but streamlining them to be less awful to work with so I can skip all this nonsense entirely. Even then I'd likely need to hack in some kinda extra bit to make tool qualities matter as I highly doubt DDA makes anything less tiring to do if you have better tools.

#### Testing

1. Compiled and load-tested.
2. Set debug needs mutation on, zeroed out needs, set strength to 10, and spawned in a digging stick
3. Dug a shallow pit, confirmed it took an hour, confirmed it inflicted 10 fatigue afterward as the expected baseline, thirst gain was 5, etc.
4. Repeated test with a stone shovel, fatigue gain was 5 as expected, other needs affected accordingly.
5. Repeated test with a full-on shovel, fatigue gain was 3, other needs affected accordingly.

#### Additional context

2023-07-31 01:52 UTC, scarf005 requested changes

2023-07-31 01:52 UTC, scarf005 commented on src/activity_actor.cpp
> +    int act_exertion = act.moves_total;
```suggestion
    const int act_exertion = act.moves_total;
```
To make the code easier to understand, it'd be great if all variable are declared immutable (const) unless there's a compelling reason to mutate it.

2023-08-15 16:36 UTC, Firestorm01X2 approved these changes
Ready

2023-08-15 16:43 UTC, chaosvolt commented
Pffft, requested change didn't update even after committing the code suggestion in it.

2023-08-25 18:00 UTC, olanti-p commented on src/activity_actor.cpp
> +    who.mod_fatigue( std::max( 1, act_exertion / to_moves<int>( 6_minutes ) ) );
NPC assistants are no longer considered. Intentional?

2023-08-25 19:20 UTC, chaosvolt commented on src/activity_actor.cpp
> +    who.mod_fatigue( std::max( 1, act_exertion / to_moves<int>( 6_minutes ) ) );
Exertion effects scale with the time taken to complete the activity, and helpers already reduce that in: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/src/iuse.cpp#L2725

2023-09-17 03:36 UTC, scarf005 approved these changes

2023-09-17 15:22 UTC, merged