docs: docs style guide + contribution guide reorganization
cataclysmbnteam/Cataclysm-BN pull request #3250
Opened 2023-09-24 09:55 UTC by scarf005

## Summary

SUMMARY: Infrastructure "Added style guide for writing new docs, reorganized contribution guide"

## Purpose of change

- fix #3215 

## Describe the solution

- organized `contributing` section into 4
- fixed `scripts/front_matter.ts` adding extra newlines
- rewrote `issues.md` to better fit BN
- reordered image files as it was hard to access images from other langs in current location

## Testing

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/f99fffd2-988a-47bc-9950-eb327bf833e3)

2023-09-29 18:12 UTC, olanti-p requested changes
Title card for contributing to docs gives 404
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/60584843/147d300d-939f-4d1e-b4af-f0d24eb72ad3)

2023-10-01 01:57 UTC, scarf005 commented on .github/labeler.yml
>    - docs/**/*
remnant of initial docs page PR when it began on `docs/`. removed.

2023-10-01 02:00 UTC, scarf005 commented on doc/src/content/docs/en/contribute/explanation/docs_style.md
> +:::caution Avoid this :::
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/9f413fe3-6da6-432a-b8fd-7d1a5ba6ade4)

an example, but poorly demonstrated. reworded a bit.

2023-10-01 02:06 UTC, scarf005 commented on doc/src/content/docs/en/contribute/explanation/pr_style.md
> +somewhere in the description:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/302bc7c2-665c-4b56-90aa-60d8099ce95d)

done.

2023-11-13 17:24 UTC, chaosvolt reviewed
The only real feedback I can offer here is I still dislike how painful it is to find a given md file in the docs folder manually, which isn't relevant to this PR since I should've spotted that and remarked on it when it was first restructured.

2024-04-03 13:32 UTC, scarf005 commented
> The only real feedback I can offer here is I still dislike how painful it is to find a given md file in the docs folder manually, which isn't relevant to this PR since I should've spotted that and remarked on it when it was first restructured.

after 4 months now i get how painful the docs layout have become. Closing as I'm thinking of overhauling the site with structure which is better than `doc/src/content/docs/en/contribute/changelog_guidelines.md`.

2024-04-03 13:32 UTC, closed without merging