build: tracy integration
cataclysmbnteam/Cataclysm-BN pull request #3253
Opened 2023-09-24 11:27 UTC by scarf005

## Summary

SUMMARY: Build "CMake integration for tracy"

## Purpose of change

![](https://media.discordapp.net/attachments/830916451517857894/1152175474085199872/image.png?width=1099&height=625)

add an easy way to sample and profile BN executable by using [tracy](https://github.com/wolfpld/tracy)

## Describe the solution

updated cmakefiles to integrate tracy client.

## Describe alternatives you've considered

using other profilers, but they all seem to be either
- slow (callgrind) and needs tweaking
- closed source and not free
- must have to alter source code to insert symbols

## Testing

TODO

## Additional context

- [ ] write docs on how to build tracy frontend

2023-09-29 15:03 UTC, olanti-p requested changes
I tried to follow the instructions, and it didn't work
```sh
git clone https://github.com/wolfpld/tracy.git
cd tracy
make -j 10 -C profiler/build/unix LEGACY=1 release
<...> Some arcane errors related to freetype
```
After some digging through tracy docs, it turned out I needed to install additional libraries first, and freetype had nothing to do with the issue.

Now that it compiled, I run tracy executable, click "connect", run the game and... nothing happens? Or am i supposed to do something else?

Also, doesn't it need source code modifications to work, or is there some way to collect samples without it (maybe at the cost of precision)?

2024-03-30 10:32 UTC, olanti-p commented on src/CMakeLists.txt
> +        target_link_libraries(cataclysm-tiles PUBLIC TracyClient)
```suggestion
        target_link_libraries(cataclysm-tiles-common PUBLIC TracyClient)
```

2024-03-30 10:32 UTC, olanti-p commented on src/CMakeLists.txt
> +        target_include_directories(cataclysm-tiles-common SYSTEM PUBLIC ${tracy_SOURCE_DIR}/public)
Needs define to work
```suggestion
        target_include_directories(cataclysm-tiles-common SYSTEM PUBLIC ${tracy_SOURCE_DIR}/public)
        target_compile_definitions(cataclysm-tiles-common PUBLIC USE_TRACY)
```

2024-03-30 10:32 UTC, olanti-p commented on src/CMakeLists.txt
> +        target_include_directories(cataclysm-common SYSTEM PUBLIC ${tracy_SOURCE_DIR}/public)
```suggestion
        target_include_directories(cataclysm-common SYSTEM PUBLIC ${tracy_SOURCE_DIR}/public)
        target_compile_definitions(cataclysm-common PUBLIC USE_TRACY)
```

2024-03-30 10:32 UTC, olanti-p commented on tools/clang-tidy-plugin/CMakeLists.txt
> +        DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
?

2024-03-30 10:32 UTC, olanti-p commented on CMakeLists.txt
> +    target_compile_options(TracyClient PRIVATE "-Wno-everything")
msvc doen't have such flag
```suggestion
    if(NOT MSVC)
        target_compile_options(TracyClient PRIVATE "-Wno-everything")
    endif()
```

2024-03-30 10:32 UTC, olanti-p commented on CMakeLists.txt
> +        GIT_TAG master
This needs to be a fixed release, e.g. https://github.com/wolfpld/tracy/releases/tag/v0.10
1. According to their docs, it's best to use same version on both client and server, and you wouldn't want to recompile the server each time CMake re-fetches the dependencies
2. There are no precompiled Windows binaries for master branch, and master is incompatible with latest 0.10 release

2024-03-30 10:32 UTC, olanti-p commented on CMakeLists.txt
> +    add_compile_definitions(TRACY_ENABLE TRACY_ON_DEMAND)
To my limited CMake knowledge, this kind of thing should be done as
```
set_target_properties(TracyClient PROPERTIES TRACY_ENABLE ON TRACY_ON_DEMAND ON)
```
After `FetchContent_MakeAvailable(tracy)`, because `add_compile_definitions` goes around package options mechanism.

2024-03-30 10:49 UTC, scarf005 commented on tools/clang-tidy-plugin/CMakeLists.txt
> +        DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
it fixes policy CMP0135 warning: e77e57d709cbeeae82f6fdbeb3a22cfc903f9350

2024-03-30 10:59 UTC, olanti-p commented on tools/clang-tidy-plugin/CMakeLists.txt
> +        DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
It does, but it's from CMake 3.24 while we use 3.20 - would it even work?

2024-03-30 11:01 UTC, scarf005 commented on tools/clang-tidy-plugin/CMakeLists.txt
> +        DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
...oh, i'll bump the minimum required cmake version then.
ubuntu 22.04 comes with [cmake 3.29 preinstalled](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#tools) so CI should work fine

2024-03-30 11:03 UTC, olanti-p commented on CMakeLists.txt
> +endif ()
Oh, right, it also needs this for msvc build - should probably work on other builds too
```suggestion
    endif()
    if (NOT DYNAMIC_LINKING)
        set_target_properties(TracyClient PROPERTIES TRACY_STATIC ON)
    endif ()
endif ()
```

2024-03-30 11:33 UTC, scarf005 commented on CMakeLists.txt
> +        GIT_TAG master
there's an issue in linux; release build on v0.10 tend to fail with [weird LTO errors](https://github.com/NLnetLabs/unbound/issues/1001) and debug build is very slow.

```
lto-wrapper: warning: using serial compilation of 79 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
mold: error: undefined symbol: tracy::IsaList
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans9.ltrans.o:(tracy::SourceView::RenderAsmLine(tracy::SourceView::AsmLine&, tracy::SourceView::AddrStat const&, tracy::SourceView::AddrStatData const&, tracy::Worker&, unsigned long&, int, int, tracy::View&))
mold: error: undefined symbol: tracy::MicroArchitectureNum
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans16.ltrans.o:(tracy::View::DrawImpl())>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans16.ltrans.o:(tracy::View::DrawImpl())>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans8.ltrans.o:(tracy::SourceView::RenderSymbolAsmView(tracy::SourceView::AddrStatData const&, tracy::Worker&, tracy::View&))>>> referenced 1 more times

mold: error: undefined symbol: tracy::MicroArchitectureData
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans9.ltrans.o:(tracy::SourceView::RenderAsmLine(tracy::SourceView::AsmLine&, tracy::SourceView::AddrStat const&, tracy::SourceView::AddrStatData const&, tracy::Worker&, unsigned long&, int, int, tracy::View&))
mold: error: undefined symbol: tracy::PortList
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans9.ltrans.o:(tracy::SourceView::RenderAsmLine(tracy::SourceView::AsmLine&, tracy::SourceView::AddrStat const&, tracy::SourceView::AddrStatData const&, tracy::Worker&, unsigned long&, int, int, tracy::View&))
mold: error: undefined symbol: tracy::MicroArchitectureList
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans16.ltrans.o:(tracy::View::DrawImpl())>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans16.ltrans.o:(tracy::View::DrawImpl())>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans8.ltrans.o:(tracy::SourceView::RenderSymbolAsmView(tracy::SourceView::AddrStatData const&, tracy::Worker&, tracy::View&))>>> referenced 1 more times

mold: error: undefined symbol: tracy::OpsList
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans7.ltrans.o:(tracy::SourceView::SourceView())
mold: error: undefined symbol: tracy::OpDescList
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans9.ltrans.o:(tracy::SourceView::RenderAsmLine(tracy::SourceView::AsmLine&, tracy::SourceView::AddrStat const&, tracy::SourceView::AddrStatData const&, tracy::Worker&, unsigned long&, int, int, tracy::View&))
mold: error: undefined symbol: tracy::OpsNum
>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans7.ltrans.o:(tracy::SourceView::SourceView())>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans7.ltrans.o:(tracy::SourceView::SourceView())>>> referenced by <artificial>
>>>               /tmp/ccc7pN6R.ltrans7.ltrans.o:(tracy::SourceView::SourceView())
collect2: error: ld returned 1 exit status
make[1]: *** [../../../common/unix.mk:74: Tracy-release] 오류 1
make[1]: 디렉터리 '/home/scarf/opt/tracy/profiler/build/unix' 나감make: *** [Makefile:11: release] 오류 2
make: 디렉터리 '/home/scarf/opt/tracy/profiler/build/unix' 나감
```

also this error https://github.com/wolfpld/tracy/issues/765 is only fixed in [very recent master](https://github.com/wolfpld/tracy/commit/2f8fe4180d14da429eb45d05724f6500de8c5306). maybe we should conditionally link against `v0.10` for windows and recent [master commit](https://github.com/wolfpld/tracy/commit/2f8fe4180d14da429eb45d05724f6500de8c5306) for linux?

2024-03-30 11:53 UTC, scarf005 commented on tools/clang-tidy-plugin/CMakeLists.txt
> +        DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
done in [`2c1d2a0` (#3253)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3253/commits/2c1d2a07dab29ff020ca4d307cd15277ad188f93).

2024-03-30 11:54 UTC, scarf005 commented on CMakeLists.txt
> +        GIT_TAG master
applied in [`97517da` (#3253)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3253/commits/97517daff493b54cc96007564610e0e29bbf8ba5).

2024-03-30 11:54 UTC, scarf005 commented on CMakeLists.txt
> +    add_compile_definitions(TRACY_ENABLE TRACY_ON_DEMAND)
applied in [`5f334dc` (#3253)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3253/commits/5f334dc18ead9d31e8546cbc0b39be06ae0bfa6e).

2024-03-30 14:28 UTC, olanti-p commented on CMakeLists.txt
> +        GIT_TAG master
Oof.
> maybe we should conditionally link against v0.10 for windows and recent [master commit](https://github.com/wolfpld/tracy/commit/2f8fe4180d14da429eb45d05724f6500de8c5306) for linux?

Yeah, sounds reasonable. Maybe note it in documentation somewhere, in case people would like to check out exact same version when building server from source on linux.

2024-03-30 14:55 UTC, scarf005 commented on CMakeLists.txt
> +        GIT_TAG master
updated docs with relevant info in [`6cf4ca5` (#3253)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3253/commits/6cf4ca5afa21fbaa406dabfefac52924363cbca0).

2024-03-30 15:02 UTC, olanti-p approved these changes

2024-03-30 23:18 UTC, merged