feat: show monster immunity in description
cataclysmbnteam/Cataclysm-BN pull request #3254
Opened 2023-09-24 11:35 UTC by scarf005

## Summary

SUMMARY: Interface "Show monster immunity in extended description"

## Purpose of change

expose more info to players, in this PR, immunity

## Describe the solution

- reused `describe_flags` lambda

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/b545f49e93df7f4a42191c9512958f84b1ca32dc/src/damage.h#L23

- made it render as 'posion' and 'smoke' despite being a single m_flag (MF_BIOPROOF), because i couldn't figure out a better way

## Describe alternatives you've considered

name its immunity `biohazard`

## Testing

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/7654141b-9dd2-45e1-acfd-5c53a1d6c716)

1. spawn a zombie master
2. e(x)amine then read (e)xtended description
3. its immunity is shown.

## Additional context

- which would be better? `biohazard` or `smoke` + `poison`?
- should we split this damage type into two?
- are there `smoke` or `poison` damage type?

2023-09-24 16:07 UTC, chaosvolt commented on src/monster.cpp
> +        {m_flag::MF_BIOPROOF, pgettext( "Poision as immunity", "poison" )},
`MF_BIOPROOF` shows up twice here, for smoke and poison.

As for bioproof description in general, I'd be inclined to say `biohazard`  since it's the least clunky way to tie it to what the game labels bio damage in spells:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/727d2171-a7a1-4fb6-b208-32452e19527b)

2023-09-24 22:08 UTC, scarf005 commented on src/monster.cpp
> +        {m_flag::MF_BIOPROOF, pgettext( "Poision as immunity", "poison" )},
makes sense. it was my inital thought as well, will change.

2023-09-24 23:17 UTC, chaosvolt requested changes
1. Compiled and load-tested.
2. Spawned in a mundane zombie, checked its description.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/ab4b5271-5bab-4a0c-aefb-1dda401810ac)
`mon_zombie` does not have any of the relevant flags, so this is clearly incorrect.

2023-09-24 23:19 UTC, scarf005 commented
ah, hecc. not sure why that happens, will investigate later.

2023-09-24 23:20 UTC, chaosvolt commented
Also checked a monster that actually has an immunity, firefighter zed has acidproof and still shows all immunities, so it's not a simple case of the logic being installed backwards it seems...
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/ba149d34-f630-4b4b-8f7d-910e8ed34232)

2023-09-25 12:35 UTC, scarf005 commented
well, should've used `describe_flags` over `describe_properties`.

2023-09-25 22:46 UTC, chaosvolt approved these changes
1. Compiled and load-tested.
2. Spawned in and examine several critters.
3. Basic zombies correctly don't even show the immunity line.
4. Firefighter zeds show immunity to acid.
5. Zombie masters show bio immunity.
6. Robots show immunity to cold and bio-hazard.

2023-09-25 22:46 UTC, merged