Added sandwiches
cataclysmbnteam/Cataclysm-BN pull request #3427
Opened 2023-10-14 19:16 UTC by yay855

## Summary

SUMMARY: [Content] "Added in two new kinds of sandwiches."

## Purpose of change

There are sandwiches ingame, but not any that truly utilize just meat and veggies at the same time other than deluxe sandwiches, which require both cheese and a condiment.

## Describe the solution

Added okay sandwich and dairy-free deluxe sandwich. Okay sandwich is just a deluxe sandwich without the cheese or sauce, dairy-free is what it sounds like.

## Describe alternatives you've considered

It's such a minor addition that I don't think alternatives are really a thing, other than not adding it in.

## Testing

The json works out.

2023-10-14 20:25 UTC, RobbieNeko commented
Not having a good ol' meat and veggies sandwich is indeed weird

2023-10-14 20:27 UTC, RobbieNeko commented
Ah, looks like you gave it too many calories (sometimes) so C++ is throwing a fit

2023-10-14 22:08 UTC, yay855 commented
Oh, okay. I'll reduce the calorie amount, I guess?

2023-10-14 22:17 UTC, RobbieNeko commented
There ya go!

2023-10-14 23:57 UTC, scarf005 commented on data/json/recipes/food/meat.json
> +      ]
could we use requirement list, `"veggy_any"` to simplify this component? (please don't apply this suggestion as a commit, it might mess up with formatting)
```suggestion
        [ [ "veggy_any", 1, "LIST" ] ]
```

2023-10-15 00:02 UTC, RoyalFox2140 requested changes
While the recipe currently works, we need a veggy_cooked ingredient list to avoid giant recipe bloat in the JSON. There's no crafting standard right now that only calls for cooked vegetables and I don't think you would put an entire raw potato in your sandwich.

2023-10-15 00:13 UTC, scarf005 approved these changes
<details><summary>Details</summary>

![Cataclysm: Bright Nights - 6d4ecee92b05_01](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/3cca3fa0-0042-4ce2-9ad2-151e88376f90)
![Cataclysm: Bright Nights - 6d4ecee92b05_02](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/a6dceefd-7701-420c-a948-8a00b53f926c)
![Cataclysm: Bright Nights - 6d4ecee92b05_03](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/bb652f9d-d7f3-4c16-8dfd-108ac6909717)
![Cataclysm: Bright Nights - 6d4ecee92b05_04](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/8a80a311-d15d-4a84-936f-c1ddae7a54cf)

</details> 

changed a bit to use requirement list. LGTM

2023-10-15 01:16 UTC, merged