Fix for hauling issue #3316
cataclysmbnteam/Cataclysm-BN pull request #3465
Opened 2023-10-19 09:19 UTC by CrocodileJonesy

## Summary

Fix for issue #3316, that is largely based on DDA code as well as porting

## Purpose of change

Fixed #3316 with all use cases I can think of

## Describe the solution

Fixes the bug by adding player hauling checks in code where hauling would normally be stopped

## Describe alternatives you've considered

None

## Testing

Tested use cases, I can think of, and all appear to work as intended without effecting anything else
Use cases that fix changes:
- Pressing haul key when only on spilt liquids
- Moving onto fences or obstacles such as windows etc.
- Diving into deep water
- When flung, grabbed, grappled
- Moving hauled items via advanced inventory manager

## Additional context

Testing hauling with obstacles
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/51826149/6287b98e-b8a0-4ae8-9f23-3135bd3fdd75

Testing hauling with spilt liquids
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/51826149/57611016-42a8-40c5-8d4a-c3ea8d866d21

Testing with monsters attacking/interacting with player while hauling
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/51826149/f6095c9e-575c-40bc-87dd-f666032ec68d

2023-10-19 10:43 UTC, scarf005 requested changes

2023-10-19 10:43 UTC, scarf005 commented on src/map.cpp
could we make `map::has_haulable_items` free function (not a member function of map)?
there's serveral benefits to not adding member functions:

1. The function does not modify anything but finds out whether an item is haulable or not in given position. 
2. The function does not require internal knowledge of map as `map::i_at` is public member function.
3. Almost every source file depends on `map.h`. Changing its signature causes significant part of the code to be rebuilt again, which may be time-consuming.

given 1,2 and 3, i think they would be better be contained in separate source file and header, for example `item_hauling.{cpp,h}`.

2023-10-19 11:50 UTC, CrocodileJonesy commented on src/map.cpp
Sure thing, will implement asap

2023-10-20 11:27 UTC, CrocodileJonesy commented on src/map.cpp
Implemented requested changes, moved the hauling code into a separate class and updated references to it

2023-10-20 22:42 UTC, scarf005 commented on src/map.cpp
i'm wondering the reason it's a class rather than free function?

2023-10-21 05:39 UTC, CrocodileJonesy commented on src/map.cpp
Oh, my bad. I appeared to have misread/misunderstood the suggestion, I thought moving into own h/cpp was it's own class. Will make adjustments

2023-10-21 08:40 UTC, scarf005 commented on msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj
would this be neccesary for building in msvc?

2023-10-21 12:19 UTC, CrocodileJonesy commented on msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj
Ah, my bad again, seems VS was just being a bit silly, I reverted the change to the project file

2023-10-21 12:26 UTC, scarf005 approved these changes

2023-10-21 16:53 UTC, merged