perf: make more items stackable
cataclysmbnteam/Cataclysm-BN pull request #3489
Opened 2023-10-23 14:44 UTC by scarf005

## Summary

SUMMARY: Performance "make more items stackable"

## Purpose of change

- resolve #3487

## Describe the solution

1. wrote a script to migrate items to AMMO
2. converted items i could think of

## Describe alternatives you've considered

make everything stackable?

## Testing

haven't tested disassembly and crafting, so weird stuff might happen.

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/8fd48737-2589-44d2-9e68-b1c922dfb08e

interestingly, `use_action` works as before.

## Additional context

context: https://discord.com/channels/830879262763909202/830916329053487124/1166006575664738307

2023-10-23 15:11 UTC, olanti-p commented
`AMMO` is for gun and tool ammo. If you want generic items to be stackable, use `stackable`.

2023-10-23 15:12 UTC, scarf005 commented
ah, will fix the script (tomorrow)

2023-10-23 16:33 UTC, scarf005 commented
```
 DEBUG    : warnings for type disinrag:
invalid stack_size 0 on type using charges


 FUNCTION : void Item_factory::check_definitions() const
 FILE     : /home/scarf/repo/cata/Cataclysm/src/item_factory.cpp
 LINE     : 1526
 VERSION  : BN 9fd976a84ee6
```
oww

2023-10-24 13:41 UTC, olanti-p commented
Test failures seem to be related to the change, no other PR has them.

2023-10-24 20:48 UTC, scarf005 commented
i've reduced rag weight and volume, so vehicle distance travelled test was failing.

2023-10-24 22:06 UTC, chaosvolt commented
Hmm, this is gonna run into the same issue as https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3414 in opening up a lot of potential material duplication exploits. :/

2023-10-24 22:26 UTC, scarf005 commented
probably this indicates we need a saner recipe and uncrafts system, but anyways will rollback rag weights

2023-10-24 22:44 UTC, chaosvolt commented
Either way is fine I guess, the fix PR is kinda slow going since it's absolute hell to work with each item so do whichever works. XD

2023-10-24 22:46 UTC, scarf005 commented
> the fix PR is kinda slow going since it's absolute hell to work with each item

well that sounds painful, let's don't, you deserve better

2023-10-24 22:47 UTC, chaosvolt commented
Eh, items and recipes kinda need a big cleanup either way and have needed it ever since salvage-by-weight was merged, just still unsure which direction it should go in.

2023-10-28 17:59 UTC, Coolthulhu commented on data/json/items/generic.json
> +    "description": "Rag",
A bit short. What's the most common type of description for an abstract?

2023-10-30 02:14 UTC, scarf005 commented
currently vehicle tests fail because apparently item weights are calculated differently for stacks.

2023-12-25 03:40 UTC, chaosvolt commented
Side note: just in case, test if having rags be stackable affects them being usable for raw materials, both for sewing repairs and for modifying with clothing_mods (now that we have a vanilla clothing mod that uses rags). I recall in the past running in an issue where I tried to use a stacking item as the material for a tailor's kit mod (was either bones or rocks) and it always said it didn't have any available.

2023-12-25 04:06 UTC, scarf005 commented on data/json/items/generic.json
> +    "description": "Rag",
renamed to `rag_abstract`.

2023-12-25 04:06 UTC, scarf005 commented
found the curprit, it was `glass_sheet`.

2023-12-25 04:09 UTC, scarf005 commented
a hecc, count by charges don't work with sewing kit
i'll make them check by their charges

2023-12-25 04:11 UTC, chaosvolt commented
RIP. Did it only affect using them as reagents to add `clothing_mod`s or did it also affect using them for item repair?

2023-12-25 04:14 UTC, scarf005 commented
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/7143dfd4038c3b15c356b080ed21e394dc402124/src/visitable.cpp#L1109-L1115

haven't tested but probably both as `visitable<T>::amount_of` doesn't seem to take charges into account

2023-12-25 05:03 UTC, chaosvolt requested changes
1. Compiled and load-tested.
2. Took down some curtains and disassembled the sheet, got 20 rags as expected.
3. Cut up the other rags, message is a lil weird (see below) but yield was as expected, and amount spawned matches what it said spawned.
4. Uncrafted the long string into short strings then thread, correctly got 300 thread out of it.
5. Repeated on another curtain and hauled the two piles of items together, items stack up correctly.
6. Made a french maid dress, it correctly used the 30 rags it said it should.
7. Reinforced some items, it consumes rags as expected.
6. Checked via yeeting remaining rags away that a sheet says it takes 2 rags per repair operation, destroyed another sheet and confirmed it takes the stated number of rags when sewing.
7. Enlarge-ified my shirt, it correctly consumed 2 rags.
8. Constructed and deconstructed a wire fence, it correctly takes 2, and yields 2 wires.
9. Bolt-cut the wire fence too, yields 2 wires as expected.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/2b14897a-8bd5-4a4e-ba6d-8d04c32eba7b)

10. And the bad bit: Bloodied myself up and used a rag, it generates a blood-stained rag but doesn't consume the rag.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/ec29e8f1-11bf-4a5b-9eb9-6d39653767a3)

2023-12-25 05:18 UTC, chaosvolt requested changes
Bonus WTF: splintered woods seem to not work right for fuel in a firewood source.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/7eef7ae6-9e5e-452e-b660-beca37aec69d)
Except sometimes they do? what in the goddamn
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/2cf89710-d3dd-44b0-95a9-c3d701eb67f8)

2023-12-25 06:21 UTC, scarf005 commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/034b635e-0006-4779-bc47-c476128fd309)

> Bonus WTF: splintered woods seem to not work right for fuel in a firewood source.

strange, i cannot reproduce this one.

2023-12-25 08:06 UTC, chaosvolt commented
Tested it again and I still don't understand the firewood source behavior. What I did, in order:
1. Created new world.
2. Took down a curtain.
3. Used the stick to smash a bunch of benches and some lockers.
4. Made a brazier, piled all the wood in a spot next to it.
5. Defined a firewood source from the construction menu, on the pile I made.
6. Examined the brazier and lit a fire, it immediately worked first time.
7. Moved the planks off the pile, removed the firewood source, and re-added it again to the pile that now has just splintered woods on a freshly-constructed firewood source.

I have a save from right this moment of it having not worked:
[Offerman.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13764969/Offerman.zip)

After I saved I try the brazier, it works. I quit without saving, load save, try again and this time it doesn't work. So whatever the hell this is, it's literally random if it works or not. I figured maybe it was a wind effect because my earlier test was outside and it was just being a shit and not printing a message about wind causing fires to not work or something, but this save's test is purely indoors.

2023-12-25 08:18 UTC, scarf005 commented
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/7143dfd4038c3b15c356b080ed21e394dc402124/src/item.cpp#L8300-L8305

I'm suspecting that this line is making random failure.

2023-12-25 08:33 UTC, scarf005 commented
now it should work.

2023-12-25 17:56 UTC, chaosvolt approved these changes
Yep, that seems to have done it. :3

2023-12-25 17:57 UTC, merged