feat(balance): Active power armor supports heavy weapons
cataclysmbnteam/Cataclysm-BN pull request #3691
Opened 2023-11-16 10:00 UTC by chaosvolt

## Purpose of change

This was a side idea floated during discussion of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1496 that I decided to set aside for another time, since Coolthulhu mentioned in the BN discord if I recall that he wasn't 100% sure about giving this benefit to power armor or not. I figure it's worth making the case that, given it does take a fair bit of effort to get power armor up and running, combined with the idea that it fits thematically (the classic Fallout imagery of a power armored soldier hefting a minigun), it might be reasonable to enable this for active power armor.

In short, implements an item flag that enables access to the ability to use heavy weapons without supporting terrain, and applies it to some appropriate items.

## Describe the solution

C++ changes:
1. Added `FIRE_SUPPORT` flag to flag.cpp and flag.h.
2. In ranged.cpp, set `ranged::gunmode_checks_weapon` so that wearing an item with the `FIRE_SUPPORT` flag enables you to fire heavy weapons without needing mountable terrain.
3. Updated the if/else logic for recoil and dispersion penalties of hip-firing heavy weapons. Heaviest penalty now checks if you're Large or have a source of the `FIRE_SUPPORT` flag, while the improved penalty can be reached by combining both as an alternative to being Huge. If you (most likely via modding, as vanilla power armor isn't compatible with Huge) combine being Huge PLUS the `FIRE_SUPPORT` flag, the penalty is slightly improved further.

JSON changes:
1. Added `FIRE_SUPPORT` to flags.json, and updated description of `MOUNTED_GUN` flag to hopefully convey all this with a bit less length.
2. Added `FIRE_SUPPORT` flag to active light, medium, and heavy power armor.
3. Added `FIRE_SUPPORT` flag to active EM vest in C.R.I.T. mod.
4. MISC: Typo fix in description of inactive EM vest.

Doc changes:
1. Added documentation for new flag, updated `MOUNTED_GUN` flag.

## Describe alternatives you've considered

1. Setting it so only medium or heavy power armor only has the fire support feature.
2. Creating a smartgun harness style power armor accessory so that using this feature with power armor requires additional setup.
3. Making it so only mod sources of the feature can provide this.

## Testing

1. Checked affected JSON files for syntax and lint errors.
2. Compiled and load-tested.
3. Hefted a M2 browning.
4. Confirmed that it still won't let me fire it unsupported by default.
5. Confirmed I can correctly fire it while standing on a mound of dirt, open window, a bench, and in a vehicle.
6. Made myself Large, confirmed I can now fire the M2 unsupported.
7. Unlarge'd myself and put together power armor, confirmed I gain ability to fire it unsupported when it's turned on.
8. Confirmed that making myself Large AND wearing active power armor also still works fine for firing unsupported.
9. Temporarily set power armor to be oversize, tested that I can indeed shoot unsupported while Huge with active power amror too.
10. Checked affected C++ files for astlye.

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/95ff56bc-99dd-4646-9735-b6c27636feda)

## Additional context

I also looked into trying to solve https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3644 while I was at it but it's a bit more complex than I was hoping it'd be so bleh.

2023-11-16 10:56 UTC, scarf005 commented on src/ranged.cpp
I'm a little bit worried on the added complexity. maybe we could extract the "can we fire this huge gun" check into reusable function. If you're ok with it i'll have a look around tomorrow and do experiments.

2023-11-16 13:05 UTC, KheirFerrum commented
If I recall Coolthulhu's argument against was that this makes Huge mutation and mutations that prevent you from wearing PA even more undesirable as they offer little to no unique advantages that make the mutation line worth it.

2023-11-16 14:43 UTC, chaosvolt commented
> If I recall Coolthulhu's argument against was that this makes Huge mutation and mutations that prevent you from wearing PA even more undesirable as they offer little to no unique advantages that make the mutation line worth it.

Fair, it ends up making both options overlap a bit. The bonuses do combine, so if there was a form of power armor that was compatible with Huge characters, then the best bonus would entail combining Huge with active power armor, encouraging you to stack up both.

An alternative would be to make it so active power armor only ever equals the effects of having Large, with Huge still outclassing either option and Large+PA not combining their effects. This would make power armor compete with Large mutation but still be worth upgrading into Huge, which might be more reasonable since that's the point where you can no longer wear power armor.

2023-11-16 15:09 UTC, chaosvolt commented on src/ranged.cpp
If you want sure. I tried to simplify it a bit by condensing the vehicle and terrain check but didn't work. Note that there's not much point to making it reusable since it's only checked to see if the player gets the green light to fire a heavy weapon at all, the penalty effects are more specific about checking whether the player is currently getting that green light from valid bipod support, which should generally mean that they're supporting the weapon themselves.

2023-11-16 15:37 UTC, chaosvolt commented
Went with the "Huge is an upgrade over power armor" option for now.

2023-11-16 19:11 UTC, chaosvolt commented
So, I added some info messages temporarily to test if using a lifter mech to support a heavy weapon triggers the penalty and:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/de048a7d-a49a-4f57-b4dc-67fe9e7e0ff6)

So I'm gonna add a check for riding a mech to `can_use_bipod` then we can condense some of the checks in `gunmode_checks_weapon` to use that function instead.

2023-11-16 22:40 UTC, Coolthulhu commented on doc/src/content/docs/en/mod/json/reference/json_flags.md
> +- `FIRE_SUPPORT` Wearing this will let you hip-fire heavy weapons without needing terrain support,
Sounds too much like it's related to the flame kind of fire. `HEAVY_WEAPON_SUPPORT`?

2023-11-16 22:42 UTC, chaosvolt commented on doc/src/content/docs/en/mod/json/reference/json_flags.md
> +- `FIRE_SUPPORT` Wearing this will let you hip-fire heavy weapons without needing terrain support,
Fair, it also might be confused for fire support in the sense of artillery or air support. That name works fine.

2023-11-16 22:50 UTC, Coolthulhu commented on src/ranged.cpp
> +        const Character &shooter = who;
Why are you adding this alias here?

2023-11-16 22:52 UTC, chaosvolt commented on src/ranged.cpp
> +        const Character &shooter = who;
Fails to compile if fed non-const character and can't recall how else to work around that.

2023-11-16 22:52 UTC, Coolthulhu commented on src/ranged.cpp
> +            add_msg( m_info, "Aiming penalty of 3x for Huge triggered." );
Mistake in comment. 3x, but effect is 2x.

2023-11-16 22:53 UTC, chaosvolt commented on src/ranged.cpp
> +            add_msg( m_info, "Aiming penalty of 3x for Huge triggered." );
That was a testing message to visually confirm whether the penalties were triggering from the cockpit of a lifter mech, I'd left it in by mistake. I've sinced removed it.

2023-11-16 23:04 UTC, Coolthulhu commented on data/json/flags.json
> +    "info": "This weapon <info>must be mounted</info> on a vehicle or furniture (window, table, mound of dirt, etc.) to fire, <info>Large or Huge</info> mutants or those with active <info>Power Armor
The "must be mounted" should be rephrased as <bad>.
Maybe something like "this weapon <bad>can only be fired if mounted</bad> [insert text]. Sufficiently <info>hueg</info> or PA'd shooters can <info>fire from hip</info> <bad>at reduced accuracy</bad>.

The idea is that the player should see at a first glance why is it bad: most of the time it's bad because you need to mount it, but in some cases, it's bad because you can only fire it at reduced accuracy or when mounted.

2023-11-16 23:05 UTC, Coolthulhu commented on data/json/flags.json
> +    "info": "This equipment allows you to fire unwieldy weapons without requiring support from mountable terrain, as a <info>Large or Huge</info> mutant could, at the expense of <bad>reduced accuracy
A <good> would be helpful. Negating the <bad> from mountable weapons is worth a greentext.

2023-11-16 23:34 UTC, Coolthulhu commented
As for balancing: I'd buff the effect from HUGE. It wrecks slots on everything.
I don't think that giving it ability to always count as mounted would unbalance it.

At the same time, LARGE doesn't need a big buff. You can even wear PA with it. And PA doesn't need a buff either.
I'd still allow the feature, for the flavor, but we should sneak in a nerf for PA soon after. Ideally, making PA provide percentage armor and less flat armor, so that it doesn't make you indestructible, but still provides good resistance vs hard hits.

Penalizing dispersion doesn't sound like "the right thing". Miss rolls have a cap, but there's always the stray bullet hit chance, so there's a lowcap of hit chance that depends only on distance. 
Ideally, being just LARGE would let you hipfire single shots, but not let you burst fire without mounting. This way you'd be limited to anti-materiel rifles rather than miniguns, so the accuracy penalty would matter much more.
The current solution is still acceptable, but if it's not a huge load of work, it would be good if you at least tried to implement it.

I'm considering flat penalty to dispersion. It would mostly affect sniping at very low dispersion where the multiplier no longer does its job. Not sure if it's needed, though.

2023-11-17 01:02 UTC, chaosvolt commented
> As for balancing: I'd buff the effect from HUGE. It wrecks slots on everything. I don't think that giving it ability to always count as mounted would unbalance it.
> 
> At the same time, LARGE doesn't need a big buff. You can even wear PA with it. And PA doesn't need a buff either. I'd still allow the feature, for the flavor, but we should sneak in a nerf for PA soon after. Ideally, making PA provide percentage armor and less flat armor, so that it doesn't make you indestructible, but still provides good resistance vs hard hits.
> 
> Penalizing dispersion doesn't sound like "the right thing". Miss rolls have a cap, but there's always the stray bullet hit chance, so there's a lowcap of hit chance that depends only on distance. Ideally, being just LARGE would let you hipfire single shots, but not let you burst fire without mounting. This way you'd be limited to anti-materiel rifles rather than miniguns, so the accuracy penalty would matter much more. The current solution is still acceptable, but if it's not a huge load of work, it would be good if you at least tried to implement it.
> 
> I'm considering flat penalty to dispersion. It would mostly affect sniping at very low dispersion where the multiplier no longer does its job. Not sure if it's needed, though.

1. Having Huge count as functionally identical to bracing on appropriate terrain or a mech cockpit seems reasonable, sure.
2. Likewise, converting the dispersion penalty for Large/PA from a multiplier to a flat penalty seems acceptable too. Any suggestions for number? 500, 1000, ???
3. Negating the ability to fire automatic weapons wouldn't work super well. Currently just about every vanilla weapon to have the `MOUNTED_GUN` flag is a machinegun of some sort, while anti-material rifles can all be fired from the shoulder just fine (relying more on bipod as opt-in for better aim). Additionally, the recoil penalty matters more for burst-fire weapons if I recall, and especially turns hefting a minigun into a spray and pray experience (that is nonetheless entertaining and flavorful despite its ammo inefficiency, in my testing experience).
4. I could even rig it so that the current penalties are shifted such that Large characters get the 2x-tier penalty Huge currently uses, and make "Medium or smaller in active power armor" use the penalty that both currently use. This would make it so Large characters automatically get a passive upgrade to their ability to hip-fire heavy weapons with or without power armor, giving them less reason to care about PA in general, and makes human purists in power armor not on par with Large mutants. Would combo with the above suggestion to allow Huge characters to just go all-out with heavy weapons for free, as that'd be a pretty good offensive tradeoff for losing access to power armor.

Converting power armor to rely on percentage damage reduction would be neat, and possibly a buff that could be shifted to its active state (which can be justified by using flavor from the RM13 that also gains an armor boost when active) in exchange for cutting the base material thickness by however much we feel like. That could be good for a follow-up PR. Easily doable using relic data stuff, though one drawback is I have zero idea how to communicate it to the player since it won't show up on the armor screen.

2023-11-17 13:14 UTC, scarf005 commented on src/ranged.cpp
> +bool can_use_bipod( const Character &who, const map &m, const tripoint &pos )
```suggestion
bool can_use_heavy_weapon( const Character &who, const map &m, const tripoint &pos )
```

the name `can_use_bipod` could be potentially confusing as it not only checks bipod but mechs as well.

2023-11-17 13:15 UTC, scarf005 requested changes
changes look OK, logic could be structured better but the original code were very hard to edit in first place. however, it'd be great to rename the function for future contributors.

2023-11-17 14:49 UTC, chaosvolt commented on src/ranged.cpp
> +bool can_use_bipod( const Character &who, const map &m, const tripoint &pos )
Aight, will need to change all calls to that function as well and not just the function name, so one sec then.

2023-11-19 00:14 UTC, KheirFerrum commented
> As for balancing: I'd buff the effect from HUGE. It wrecks slots on everything. I don't think that giving it ability to always count as mounted would unbalance it.
> 
> At the same time, LARGE doesn't need a big buff. You can even wear PA with it. And PA doesn't need a buff either. I'd still allow the feature, for the flavor, but we should sneak in a nerf for PA soon after. Ideally, making PA provide percentage armor and less flat armor, so that it doesn't make you indestructible, but still provides good resistance vs hard hits.
> 
> Penalizing dispersion doesn't sound like "the right thing". Miss rolls have a cap, but there's always the stray bullet hit chance, so there's a lowcap of hit chance that depends only on distance. Ideally, being just LARGE would let you hipfire single shots, but not let you burst fire without mounting. This way you'd be limited to anti-materiel rifles rather than miniguns, so the accuracy penalty would matter much more. The current solution is still acceptable, but if it's not a huge load of work, it would be good if you at least tried to implement it.
> 
> I'm considering flat penalty to dispersion. It would mostly affect sniping at very low dispersion where the multiplier no longer does its job. Not sure if it's needed, though.

Yeah, been wanting to look at PA, I think the high encumbrance versions making you more or less invincible to most enemies is fine, but light and normal shouldn't stack up so high against rifles and small arms to negate them.

2023-11-21 13:13 UTC, scarf005 approved these changes
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/20c006f2-5120-4a9e-a62c-b77be681c20e


https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/f934f424-4722-4a14-a8bb-2b78f58077f5


https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/126bea7b-f465-4811-89e8-3634104436f8


https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/29291672-a6b5-440b-9cbb-ed9be4324a09

LGTM

2023-11-21 14:28 UTC, merged