feat: Effects adding other effects on removal
cataclysmbnteam/Cataclysm-BN pull request #3695
Opened 2023-11-16 16:59 UTC by Coolthulhu

## Purpose of change

This PR allows defining comedowns and similar effects that can coexist with the parent effect and can be defined by mods.

## Describe the solution

When effect expires, it can create other effects, at set duration/intensity, or inheriting duration/intensity from the decaying effect.
New effects are added at the end of the effect processing loop, and so should not be able to cause effect map migration. They are added in the same order as the parent effects were processed.
There is an option to only affect decaying (0 duration) effects, only affect removed effects (`remove_effect` when duration > 0), or both.

Reimplemented adrenaline and its comedown in the new system. This means that both effects can now coexist - you can have adrenaline buff with comedown debuff applied at the same time.

## Describe alternatives you've considered

* Waiting for lua to cover it, with associated problems, such as lack of common standard of effect decay
* Leaving it hardcoded, since we don't have many effects that could use this feature (possibly because we didn't have this feature)

## Testing

* Tests pass
* Spawn 3x adrenaline
* Use adrenaline
* Wait for it to decay
* Apply adrenaline
* Confirm both buff and debuff exist
* Wait for both to time out
* Apply adrenaline
* Use blood filtering bionic
* Confirm that adrenaline comedown is present

## Additional context

## Checklist

* [ ] Body part inheritance
* [ ] Fixing adrenaline:
  * [ ] Rebalance duration, to account for debuff no longer being included in "common duration"
  * [ ] Remove hardcoded addition of debuff from blood filtering and possibly others

2023-11-24 13:09 UTC, scarf005 commented on src/effect.h
> +};
```suggestion
const auto caused_effect_sort_less = []( const caused_effect &lhs, const caused_effect &rhs ) -> bool {
	return lhs.type == rhs.type ? lhs.intensity_requirement < rhs.intensity_requirement : lhs.type < rhs.type;
};
```

this comparator doesn't seem to be used anywhere in PR, would it be intentional?
also, making it lambda might be better for ergonomics.

2023-11-25 08:32 UTC, scarf005 approved these changes

2023-11-25 08:34 UTC, scarf005 approved these changes

2023-11-25 09:57 UTC, scarf005 requested changes
> - Tests pass
> - Spawn 3x adrenaline
> - Use adrenaline
> - Wait for it to decay
> - Apply adrenaline
> - Confirm both buff and debuff exist

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/799bdde2-42c9-46ab-993d-2e50553d3db2)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/a700610e-5858-4f28-9ba0-4014e43ae5ee)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/be8fae62-fb13-442e-9a8c-e92fead37cd5)

works as intended, however on comedown it errors with:
```
 DEBUG    : player_morale::perceived_pain is inconsistent.

 FUNCTION : bool player_morale::consistent_with(const player_morale &) const
 FILE     : /home/scarf/repo/cata/Cataclysm/src/morale.cpp
 LINE     : 878
 VERSION  : BN 8b14530d31ec
```

> - Wait for both to time out
> - Apply adrenaline
> - Use blood filtering bionic
> - Confirm that adrenaline comedown is present

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/638e49a9-9fa6-46ca-9938-9c07662795f4)

even after using blood filter CBM, the effect does not wear off.

2023-11-28 23:46 UTC, Coolthulhu commented on src/effect.h
> +};
Oh right, I used it for something before, but now it's probably obsolete.

2023-12-20 20:08 UTC, Coolthulhu commented
I didn't realize that blood filter was not removing adrenaline. That's why it wasn't triggering the aftereffect.

2023-12-21 02:07 UTC, scarf005 approved these changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2520aa7a-2fe7-4996-b1af-1a15f3eb98cd)

LGTM.

2023-12-21 02:07 UTC, scarf005 approved these changes

2023-12-21 02:07 UTC, merged