fix: martial arts damage buffs apply to all damage types
cataclysmbnteam/Cataclysm-BN pull request #3728
Opened 2023-11-20 21:19 UTC by yay855

## Purpose of change

There are multiple unarmed martial arts weapons ingame that perform a variety of damage types, but many martial arts techniques and buffs only buffed bashing damage.

## Describe the solution

All martial arts techniques and buffs that only buffed one or two of the three main melee damage types (bash, cut, stab) now buff all three.

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2023-11-21 12:54 UTC, scarf005 commented on data/json/martialarts.json
> +          { "stat": "damage", "type": "stab", "scale": 2.0 }
identical `{ "stat": "block", "scaling-stat": "str", "scale": 0.5 }` bonus is repeated three times, would this be intentional?

2023-11-21 14:58 UTC, chaosvolt commented on data/json/martialarts.json
> +          { "stat": "damage", "type": "stab", "scale": 2.0 }
```suggestion
          { "stat": "block", "scaling-stat": "str", "scale": 0.5 },
          { "stat": "damage", "type": "bash", "scale": 2.0 },
          { "stat": "damage", "type": "cut", "scale": 2.0 },
          { "stat": "damage", "type": "stab", "scale": 2.0 }
```
Definitely just a copypaste error it looks like.

2023-11-21 15:01 UTC, chaosvolt reviewed
Rest of it looks good, though I'd note that most of these buffs specify what damage types they modify, so should edit those to not reference a specific damage type.

2023-11-21 18:48 UTC, yay855 commented on data/json/martialarts.json
> +          { "stat": "damage", "type": "stab", "scale": 2.0 }
Oh, it wouldn't. I must have accidentally copied it alongside the damage scaling. I'll fix it.

2023-11-21 18:49 UTC, yay855 commented on data/json/martialarts.json
> +          { "stat": "damage", "type": "stab", "scale": 2.0 }
Oh, Chaos already did.

2023-11-22 14:07 UTC, scarf005 requested changes
like CV said, I think we should change all descriptions to reflect PR, e.g `+2 Bash damage` to `+2 damage` to correctly describe changes.

2023-11-26 00:37 UTC, scarf005 approved these changes
LGTM

2023-11-26 01:40 UTC, merged