feat(UI): korean and english fuzzy search
cataclysmbnteam/Cataclysm-BN pull request #3757
Opened 2023-11-26 07:16 UTC by scarf005

## Purpose of change

improve ergonomics of filtering items.

## Describe the solution

`lcmatch` now uses `std::wregex` to fuzzy-search items.
e.g `mgzn` -> `m.*?g.*?z.*?n`

this isn't the best fuzzy search algorithm, however it's not too complex and supports complex fuzzy searching in korean (e.g match '감' with either 'ㄱ' or '가')

## Describe alternatives you've considered

### using `std::locale` on language.cpp

<details><summary>diff</summary>

```diff
diff --git a/src/language.cpp b/src/language.cpp
index da7c57a00568..657252dd9541 100644
--- a/src/language.cpp
+++ b/src/language.cpp
@@ -2,6 +2,7 @@
 
 #include <algorithm>
 #include <fstream>
+#include <locale>
 
 #if defined(_WIN32)
 #  if 1 // Prevent IWYU reordering platform_win.h below mmsystem.h
@@ -158,23 +159,9 @@ static std::string getSystemUILang()
 // Linux / Android
 static std::string getSystemUILang()
 {
-    std::string ret;
+    const auto lang = std::setlocale( LC_ALL, std::locale( "" ).name().c_str() );
 
-    const char *language = getenv( "LANGUAGE" );
-    if( language && language[0] != '\0' ) {
-        ret = language;
-    } else {
-        const char *loc = setlocale( LC_MESSAGES, nullptr );
-        if( loc != nullptr ) {
-            ret = loc;
-        }
-    }
-
-    if( ret == "C" || string_starts_with( ret, "C." ) ) {
-        ret = "en";
-    }
-
-    return to_valid_language( ret );
+    return to_valid_language( lang );
 }
 #endif // _WIN32 / !MACOSX
```

</details> 

### filtering entries by regex relevance in `uilist::filterlist`

this would be a big change, thus deserves its own PR.

## Testing

added `string_fuzzy_search_test.cpp`.

### fuzzy search in english

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2577c8c6-efd9-42e4-963e-2d5dea38176a

### fuzzy search in korean

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/aec97fa9-9ef1-4a21-8c0a-9c47cce87bae

## Additional context

reference: https://taegon.kim/archives/9919

2023-12-03 00:29 UTC, Vollch requested changes
I see this feature being useful, but it need to be toggleable via hotkey, or something like that.
I suppose it might work better in korean, but in english it's prone to be very misleading. Look at that, for example:
Before:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/544763/741c6a6d-7b41-449b-8213-3123383f279c)
After:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/544763/ae9fc9d3-541c-46ce-84a6-20f03c57be9b)

Second pic is pretty much unusable.

2023-12-04 00:28 UTC, scarf005 commented
or maybe we could improve the logic to make `lcmatch` return 'certainty score', and sort the result accordingly.

2023-12-04 01:06 UTC, Vollch commented
That'll break alphabetical sorting. I'd change step 4 to "sort by score, and then alphabetically within same score groups"

2023-12-09 01:24 UTC, scarf005 commented
setting it to draft until mentioned changes are done.

2025-04-16 23:33 UTC, closed without merging