feat(content): `clockworks` recipe, `handmade pocket watch`
cataclysmbnteam/Cataclysm-BN pull request #3800
Opened 2023-12-02 03:50 UTC by yay855

## Purpose of change

There was currently no method to create an innawoods clock or timepiece; it's such a minor change and QOL tidbit I figured why not, and after much debate on the server, here we are.

## Describe the solution

Added a recipe to craft clockworks and a steel pocketwatch item, recipe, and uncraft.

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2023-12-02 12:53 UTC, scarf005 requested changes

2023-12-02 12:53 UTC, scarf005 commented on data/json/items/tool/misc.json
> +    "price_postapoc": 100,
```suggestion
    "price": "250 USD",
    "price_postapoc": "1 USD",
```

2023-12-02 12:58 UTC, scarf005 requested changes
Could we [`copy-from`](https://docs.cataclysmbn.org/en/mod/json/reference/items/json_inheritance/#copy-from) `"pocketwatch"` to reduce code duplication?

this will also allow us to use [proportional](https://docs.cataclysmbn.org/en/mod/json/reference/items/json_inheritance/#examples), e.g make the price cheaper.

2023-12-02 16:52 UTC, chaosvolt commented on data/json/recipes/other/materials.json
> +      { "id": "DRILL", "level": 1 },
```suggestion
    "qualities": [
      { "id": "HAMMER_FINE", "level": 1 },
      { "id": "CUT_FINE", "level": 1 },
      { "id": "DRILL", "level": 2 },
```
Since it already mandates a full-on hacksaw and screwdriver set, might as well upgrade these tools a bit. Plus, not often a recipe actually gets to call hammer_fine instead of just max-tier hammer. :3

2023-12-03 05:20 UTC, chaosvolt commented on data/json/items/tool/misc.json
> +    "to_hit": -3,
```suggestion
    "copy-from": "pocketwatch",
    "name": { "str": "steel pocket watch", "str_pl": "steel pocket watches" },
    "description": "An old-fashioned pocket watch, useful for telling the time and not much else.",
    "looks_like": "pocketwatch",
    "price": "250 USD",
    "price_postapoc": "1 USD",
```
Those two bits are same as watch it inherits from so don't need them, will cause it to complain about updating assigned values on load otherwise.

2023-12-04 10:06 UTC, Krwak commented
https://www.youtube.com/watch?v=9_QsCLYs2mY just for reference how complex mechanical watches are. 
A typical pocket watch isn't much larger than wrist watch btw.
I suggest making pocket watches craftable with moving parts that wouldn't be craftable by hand.
https://en.wikipedia.org/wiki/Movement_(clockwork)

2023-12-04 14:43 UTC, chaosvolt commented
> I suggest making pocket watches craftable with moving parts that wouldn't be craftable by hand.

If we're gonna do that we might as well make them booklearn-only. Since that was vetoed by the others on the basis of it defeating the point of being craftable, then so too would locking it behind uncraftable components. If we did that then the no-brainer solution would just be don't allow crafting clockworks, but then you have to take apart a watch to make a watch, which would just be a waste of time.

2023-12-04 14:57 UTC, chaosvolt commented on data/json/recipes/other/tools.json
> +    "book_learn": [ [ "textbook_mechanics", 4 ], [ "manual_mechanics", 4 ], [ "textbook_fabrication", 4 ] ],
Forgot to add this suggestion hecc
```suggestion
    "difficulty": 5,
    "skills_required": [ "mechanics", 3 ],
    "time": "2 h",
    "autolearn": [ [ "mechanics", 3 ] ],
    "book_learn": [ [ "textbook_mechanics", 3 ], [ "manual_mechanics", 3 ], [ "textbook_fabrication", 3 ] ],
```

2023-12-04 23:45 UTC, scarf005 commented
My personal idea as a player (not as a reviewer, as I've delegated @chaosvolt as assignee):
1. Naming the new clock `crude pocketwatch` or `makeshift pocketwatch` might convey its purpose better.
2. If we make the new clock recipes locked behind book recipes, it might actually make sense to add hourglass or sundial that can be created without books.

2023-12-05 00:07 UTC, chaosvolt commented
`handmade` pocketwatch could also work.

2023-12-05 00:16 UTC, chaosvolt commented on data/json/items/tool/misc.json
> +    "name": { "str": "steel pocket watch", "str_pl": "steel pocket watches" },
```suggestion
    "name": { "str": "handmade pocket watch", "str_pl": "handmade pocket watches" },
```

2023-12-05 00:17 UTC, chaosvolt submitted a review, later dismissed
Anyway, I am screm.

2023-12-05 02:12 UTC, Krwak commented
Ok, to put it here plainly what i do think is craftable innawoods and that is a sandclock. 
It wouldn't be portable but you could very well abstract the turning and make it show time to appease the innawoods needs.
If you don't mind the idea of it being dumbed down.
The goal is to have a timepiece.

2023-12-06 01:52 UTC, scarf005 approved these changes
## Summary

I approve the changes, given that the homemade watch is a lot harder to craft now. While sandclocks(hourglass) could work, i think that'd be better as a separate PR.

## Description

had private discussion with @yay855, and we both agreed that making clock from scratch a lot harder would make sense. thus recipes are heavily nerfed:
- both `clockworks` and `pocketwatch_crude` requires `7 mechanics` and `6 fabrication`.
- weight and volume nerfed to 0.5kg and 0.5L
- uncraft time nerfed to 3 minutes

2023-12-06 02:13 UTC, RoyalFox2140 commented
> ## Summary
> I approve the changes, given that the homemade watch is a lot harder to craft now. While sandclocks(hourglass) could work, i think that'd be better as a separate PR.
> 
> ## Description
> had private discussion with @yay855, and we both agreed that making clock from scratch a lot harder would make sense. thus recipes are heavily nerfed:
> 
> * now `mechanics` are primary skill requirement
> * both `clockworks` and `pocketwatch_crude` requires `7 mechanics` and `6 fabrication`.
> * weight and volume nerfed to 0.5kg and 0.5L
> * uncraft time nerfed to 3 minutes

We have come to the compromise that @chaosvolt and I will end up redoing the mechanics skill to move items with moving parts such as flintlocks and crossbows to mechanics so it can be trained to at least 7 or 8 innawoods with a new line of recipes. This will not be an attainable item until then due to any higher than 3 mechanics being impossible innawoods

2023-12-06 02:19 UTC, merged

2023-12-06 02:23 UTC, chaosvolt commented
My goal long-term is definitely to make mechanics less of a pain in the ass to level up, yes. Dunno when since so many things to juggle but eventually.

For consistency I did recommend the following regarding ranged weapon recipes:
1. Crossbows probably should stay fabrication-first, to stay consistent with non-firearm ranged weapon recipes generally being fab-first.
2. Flintlocks however can reasonably be set to be mechanics-first, however...
3. We would want to revert basic pipe rifles being set to use fabrication as the primary skill, on the basis of making firearm recipes use mechanics consistently.

2023-12-06 02:25 UTC, scarf005 commented
also, do our system allows 'cross-training'? (e.g learning primary skill also improves secondary skill, albeit at slower rate)

2023-12-06 02:30 UTC, chaosvolt commented
> also, do our system allows 'cross-training'? (e.g learning primary skill also improves secondary skill, albeit at slower rate)

Don't think so, but that is 100% something we need code-wise. Maybe a valid candidate for first mechanics-related thing to add?