feat(content): Aftershock ports 1, Shoddy laser rifle
cataclysmbnteam/Cataclysm-BN pull request #3809
Opened 2023-12-02 15:37 UTC by RoyalFox2140

## Purpose of change
Aftershock ports part 1: Shoddy laser rifle

The first step on mainlining Aftershock, the shoddy laser rifle is migrated into the game with its crafting recipe. Due to the way this will affect balance I have ported this alone. This is the first autolearn craftable UPS laser in Bright Nights. @chaosvolt @scarf005 to approve balance.

## Describe the solution

I have changed or removed a lot of fields since it properly copies from rifle_energy and ensured it is internally consistent with the V29 and A7. It is set to 15 damage 30 UPS as suggested, its skill field was removed and its durability set to homemade rifles. It has 5 less range than all other lasers, its crafting recipe is set to autolearn at 5 electronics instead of 4. Its gunmods and ammo effects are properly inherited, It's also twice as loud as the V29. External tileset updated.

## Describe alternatives you've considered

None.

## Testing

## Additional context

@Maleclypse @John-Candlebury Co-authorship established to maintain credit and goodwill. I won't ping in future pulls unless requested.

No migrations are required and the relevant entries were deleted from Aftershock, the game will automatically register what happened. Changes must be tested on a world without Aftershock present or you won't know if it's functional.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/efabaddb-a60f-434c-bf8b-cc8dca6afff0)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/d526112e-8ce8-48fc-8ae1-1ce4b650f846)

2023-12-02 15:46 UTC, RoyalFox2140 commented
> could we copy paste entire tileset, rather than porting select few tilesets? this makes it easier to manage aftershock assets during multiple PRs

I figured it was a bad practice but I will do that then.

2023-12-02 15:55 UTC, RoyalFox2140 commented
I am unsure if you want me to also completely delete it on Aftershock so I did that in a separate pull.

2023-12-02 22:20 UTC, chaosvolt commented on data/json/recipes/weapon/ranged.json
> +      [ [ "amplifier", 2 ] ],
```suggestion
    "using": [ [ "soldering_standard", 200 ] ],
    "components": [
      [ [ "battery_ups", 1 ] ],
      [ [ "amplifier", 2 ] ],
```

2023-12-06 00:45 UTC, scarf005 commented on doc/src/content/docs/en/mod/json/reference/graphics/external_tileset.md
Maybe this line could be reverted as shoddy laser rifles defaults to using `energy_rifle` sprite?

2023-12-06 00:49 UTC, scarf005 approved these changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/e87d7b7c-f907-427b-8ce2-5c48729ccedf)

attributions correctly done, more laser weapons variants look good.

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/26ac3eae-c715-4ee5-b3ca-648610dcc623)
also we apply some PR scope spam

2023-12-06 00:53 UTC, scarf005 requested changes
```
 DEBUG    : Error: Could not load image "data/mods/bn/../../json/Aftershock_normal.png": Couldn't open data/mods/bn/../../json/Aftershock_normal.png

 FUNCTION : bool main_menu::load_character_tab(const std::string &)
 FILE     : /home/scarf/repo/cata/Cataclysm/src/main_menu.cpp
 LINE     : 1020
 VERSION  : BN 34d1bf82cc87
```
...wait, need to fix the path.

2023-12-06 00:55 UTC, RoyalFox2140 commented
> ```
>  DEBUG    : Error: Could not load image "data/mods/bn/../../json/Aftershock_normal.png": Couldn't open data/mods/bn/../../json/Aftershock_normal.png
> 
>  FUNCTION : bool main_menu::load_character_tab(const std::string &)
>  FILE     : /home/scarf/repo/cata/Cataclysm/src/main_menu.cpp
>  LINE     : 1020
>  VERSION  : BN 34d1bf82cc87
> ```
> 
> ...wait, need to fix the path.

I was not sure if you wanted me to delete the sprite sheet from the original mod, but that can be reverted

2023-12-06 00:56 UTC, scarf005 commented on data/json/external_tileset/AFS_external.json
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/ab8ce454-9c0b-4813-a78f-31f04800ebc9)

this entry removal causes shoddy rifles to use default sprites for energy rifle.
to clarify, would this be intentional?

2023-12-06 00:57 UTC, RoyalFox2140 commented on data/json/external_tileset/AFS_external.json
I like the new appearance as otherwise we won't tell the difference between the two rifles on npc's.

2023-12-06 01:11 UTC, scarf005 approved these changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/20acf521-8307-4251-a656-77afe6c3c873)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/56f47902-92e1-467f-8e19-3b87e91452e7)

LGTM.

2023-12-06 02:19 UTC, merged