fix: id, description of concrete floor without roof
cataclysmbnteam/Cataclysm-BN pull request #3891
Opened 2023-12-13 14:03 UTC by 0Monet

## Purpose of change
Rename id "t_thconc_floor_nofloor" of concrete floor without roof for consistency.
Remove the "roof" part of the terrain description.
## Describe the solution
Replace id with "t_thconc_floor_no_roof".
## Describe alternatives you've considered
None
## Testing

## Additional context
<img width="665" alt="Capture d’écran 2023-12-13 145534" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/146018959/fcf75f89-0f73-4bd3-b12a-4265dbca07aa">

2023-12-13 14:07 UTC, scarf005 commented
> Rename id "t_thconc_floor_nofloor" of concrete floor without roof for consistency.

would it be compatible with old saves or maps that use the id `t_thconc_floor_nofloor`?

2023-12-13 14:10 UTC, 0Monet commented
no

2023-12-13 14:12 UTC, scarf005 commented
@chaosvolt would it be possible to define migration for terrain ids?

2023-12-13 14:19 UTC, 0Monet commented
Maybe add "t_thconc_floor_nofloor" to uncategorized.json in obsoletion

2023-12-13 17:16 UTC, chaosvolt commented
I think you can use `alias` to fix this? Check walls, railings, chain link fences and the link for examples.

2023-12-13 17:24 UTC, RoyalFox2140 requested changes
It's not worth the incompatibilities here since people won't confuse floor_nofloor as not having a floor instead of not having a roof. 

You would need to update every mapgen palette in base game to use the new ID or you'll have broken a lot of locations, and that's still not mentioning how many mods use the old ID that would need to scramble to update just to let people run their game again.

2023-12-13 17:38 UTC, chaosvolt commented
Personally I feel that the ID has fairly low risk of confusing people (the floor has no floor! :D), but I'm sure someone out there might assume it to be some kinda skylight. The question then becomes, does the risk of "someone's failed attempt to add said skylight to their mapgen becoming our problem" outweigh making the fix for it everyone else's problem?

If `alias` works correctly (we'll need to test it, namely load-test while retaining an unchanged use of the old terrain somewhere in the JSON, then test further by spawning some of the old terrain in another build without this change then load that save with your JSON changes), then we have the best of both worlds (we can fix the ID without breaking shit for other people). If not, then I'd say retain the old ID instead because it's really not worth it.

2023-12-13 17:39 UTC, chaosvolt requested changes
Personally I feel that the ID has fairly low risk of confusing people (the floor has no floor! :D), but I'm sure someone out there might assume it to be some kinda skylight. The question then becomes, does the risk of "someone's failed attempt to add said skylight to their mapgen becoming our problem" outweigh making the fix for it everyone else's problem?

If `alias` works correctly (we'll need to test it, namely load-test while retaining an unchanged use of the old terrain somewhere in the JSON, then test further by spawning some of the old terrain in another build without this change then load that save with your JSON changes), then we have the best of both worlds (we can fix the ID without breaking shit for other people). If not, then I'd say retain the old ID instead because it's really not worth it.

2023-12-13 17:41 UTC, chaosvolt commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "id": "t_thconc_floor_no_roof",
```suggestion
    "id": "t_thconc_floor_no_roof",
    "alias": "t_thconc_floor_nofloor",
```
Should've actually added the relevant code suggestion to the change request proposal hecc

2023-12-13 18:25 UTC, 0Monet commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "id": "t_thconc_floor_no_roof",
I loaded a save with the old terrain from a build without changes into a build with changes.
No error message.

2023-12-13 19:03 UTC, chaosvolt commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "id": "t_thconc_floor_no_roof",
Uh, you sure about that? The map would be trying to load terrain in its save JSON that's been outright deleted.

2023-12-13 19:28 UTC, 0Monet commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "id": "t_thconc_floor_no_roof",
No idea...
In my build without change:
<img width="683" alt="Capture d’écran 2023-12-13 201839" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/146018959/d4c22ccb-d2af-41aa-bbdc-f7dd73595936">
When, I load the save in the build with change:
<img width="960" alt="Capture d’écran 2023-12-13 202121" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/146018959/62c87bbb-a38b-4af4-ba85-62f74346a327">
It seems to change "t_thconc_floor_nofloor" to "t_thconc_floor_no_roof".

2023-12-13 20:17 UTC, chaosvolt commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "id": "t_thconc_floor_no_roof",
Hmm, that's a good sign then? Weird, I would've expected it to need some kinda migration or alias...maybe we can still assign `alias` just to be safe though?

2023-12-13 20:18 UTC, RoyalFox2140 commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "id": "t_thconc_floor_no_roof",
This requires further investigation @chaosvolt

2023-12-13 20:22 UTC, RoyalFox2140 commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "id": "t_thconc_floor_no_roof",
> No idea... In my build without change: <img alt="Capture d’écran 2023-12-13 201839" width="683" src="https://private-user-images.githubusercontent.com/146018959/290304224-d4c22ccb-d2af-41aa-bbdc-f7dd73595936.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTkwMjksIm5iZiI6MTcwMjQ5ODcyOSwicGF0aCI6Ii8xNDYwMTg5NTkvMjkwMzA0MjI0LWQ0YzIyY2NiLWQyYWYtNDFhYS1iYmRjLWY3ZGQ3MzU5NTkzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMDE4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODRmOWYzY2Q0ZWU1NmUxM2FlMTYwODA5OWQ2YzJkNDIwMjdiYTYzNzRlOGVhYjFmNTYwZmM0NWMyZTQxMGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V37unKVGEi-zi3KEj7kuYKY5-87tXi7OkpfxYaaZyVU"> When, I load the save in the build with change: <img alt="Capture d’écran 2023-12-13 202121" width="960" src="https://private-user-images.githubusercontent.com/146018959/290304239-62c87bbb-a38b-4af4-ba85-62f74346a327.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTkwMjksIm5iZiI6MTcwMjQ5ODcyOSwicGF0aCI6Ii8xNDYwMTg5NTkvMjkwMzA0MjM5LTYyYzg3YmJiLWEzOGItNGFmNC1iYTg1LTYyZjc0MzQ2YTMyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMDE4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDE4OTM5MzkwM2U4ZDhmNjY5MjkyNjE5NWY2NDM1ZTYwYjY5YWM0MTcyNzJkOWYyZDRhOGMyMmEyMDljZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6PFYx__kOHwEAKdqA5rizdYJjppPK-bHAjPe2neHuh0"> It seems to change "t_thconc_floor_nofloor" to "t_thconc_floor_no_roof".

I made a migration for aftershock furnitures it may be worth testing one here. I sadly didnt test my migration as I figured if it didnt work it wasnt possible.

2023-12-14 06:48 UTC, 0Monet commented
I close, it's not worth changing anything.

2023-12-14 06:48 UTC, closed without merging