featport (content): `More NPCs`
cataclysmbnteam/Cataclysm-BN pull request #3917
Opened 2023-12-16 00:23 UTC by Zlorthishen

## Purpose of change

## Describe the solution
https://github.com/CleverRaven/Cataclysm-DDA/pull/36287 by Maleclypse
https://github.com/CleverRaven/Cataclysm-DDA/pull/57483 by MNG-cataclysm
https://github.com/CleverRaven/Cataclysm-DDA/pull/62134 by MNG-cataclysm

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2023-12-16 01:04 UTC, scarf005 requested changes
Hi, thanks for the port. however, these commits are ported from DDA and thus must be [attributed accordingly](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). could you add attribution to individual commits?

2023-12-16 01:08 UTC, RoyalFox2140 requested changes
You've left in DDA exclusive items in the dialogue. lc_steel_lump mc_steel_lump and hc_steel_lump are not in BN and are not candidates to port as those are different carbon grades of steel. I am also unsure if we even have muriatic acid in the game. You'll need to playtest the changes and remove references to things that don't exist.

I also may have missed it but I didn't see a blacksmith NPC in this pull that is referenced in the scrapyard questline, we need to either port that blacksmith or remove that quest for now.

I give my overall general approval of the npc's, quest, and dialogue once any JSON issues are ironed out. Asking thoughts on the NPC's from @KheirFerrum as the lore re-writer.

2023-12-16 01:10 UTC, RoyalFox2140 commented
@scarf005 The tests won't account for item ID's we're missing from DDA.

2023-12-16 01:41 UTC, Zlorthishen commented
> I also may have missed it but I didn't see a blacksmith NPC in this pull that is referenced in the scrapyard questline, we need to either port that blacksmith or remove that quest for now.

I removed that mission, those NPC's will be added in a followup

2023-12-16 03:02 UTC, scarf005 requested changes
```
Terminated: Json error: data/json/mapgen/apartment_con_new.json:383:60: format: rows: row 25 column 25: '~' has no terrain, furniture, or other definition

        "****|%%%%%%%%%%%|>,,G..~~..=EEx|%%%%%%%%%%%|****",
        "****|%%%%%%%%%%%|<,,G..~~..=EEE|%%%%%%%%%%%|****",
        "***||||||||||||||||||..~~..||||||||||||||||||***",
                                                           ^
        "***|á.....+r-u+í....|..~~..|Í....+u-r+..ä...|***",
        "***w......-----.....|..~~..|.....-----......w***",
        "***w......-STb-.....|..~~..|.....-bTS-......w***",

Make sure that you're in the correct working directory and your data isn't corrupted.
```

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/fb0c8acc-4022-4b9d-bd6b-a71ae5785230

1. newly inserted apartment floors slightly diverge from BN's existing layout, for example missing elevator controls.
2. apartment palettes are missing many symbols, for example `~`.

2023-12-17 04:31 UTC, KheirFerrum commented
I'll give it a look over later today.

2023-12-17 04:38 UTC, KheirFerrum commented
Quick lookover. Main issue I see is that it still follows the very old and very incongruent lore where the Cataclysm wasn't much of an event, with no portal storms, no huge monsters, etc, just rioters. It's not exactly a huge issue though, would just mean there's more to rewrite when lore is fully finalized.

2023-12-17 19:22 UTC, RoyalFox2140 commented
> I'll give it a look over later today.
> 
> Edit: Though a summary would be nice.

Scrapyard guy, lumber mill workers, innawoods chemist, moonshiner, homeless camp, a guy in his apartment. They all have different stories to tell but yeah no portal storms mentioned or huge monsters. I will note that the moonshiner certainly was in town but the rest I'm pretty sure were just hiding out where there'd be less trouble and storms.

2023-12-22 00:36 UTC, chaosvolt commented on data/json/npcs/Mr_Lapin/Mr_Lapin.json
> +    "name_unique": "Mr Lapin",
Don't we already have this NPC?

2023-12-22 00:56 UTC, chaosvolt commented on data/json/npcs/Mr_Lapin/Mr_Lapin.json
> +    "name_unique": "Mr Lapin",
Wait, we do: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/data/json/npcs/holdouts/Mr_Lapin.json

2023-12-24 03:26 UTC, scarf005 requested changes

2023-12-24 03:26 UTC, scarf005 commented on data/json/npcs/cabin_chemist/chemist_missions.json
> +    "item": "trade_writ",
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2d3b6491-344b-45e3-9dc7-e848d281eb42)

as the `writs of trade` is not consumed on mission and both chemist and scrapyard requires it, the player _could_ exploit it but i think the chance of this happening is low.

2023-12-24 03:26 UTC, scarf005 commented on data/json/overmap/overmap_special/specials.json
> +  },
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/1e288c07-4f6e-4011-8876-17e8366f26f0)

road placement is being weird but i'm not sure how to fix it

2023-12-24 03:26 UTC, scarf005 commented on data/json/npcs/cabin_chemist/cabin_chemist.json
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2abbe16b-31c8-402b-858e-cb79f968594d)

works good.

2023-12-24 03:26 UTC, scarf005 commented on data/json/npcs/lumberyard/lumbermill_missions.json
> +    },
this causes error because `occupied_lum_wall` is missing.

2024-01-04 01:36 UTC, Zlorthishen commented on data/json/overmap/overmap_special/specials.json
> +  },
changed the road to originate from (0,-1) to (-1,0). so it should come from the X-axis instead of Y

2024-01-04 02:51 UTC, Zlorthishen commented on data/json/npcs/cabin_chemist/chemist_missions.json
> +    "item": "trade_writ",
i split the writs of trade into separate items for the chemist and the lumberyard

2024-01-04 02:55 UTC, Zlorthishen commented on data/json/npcs/lumberyard/lumbermill_missions.json
> +    },
added the missing nested_mapgen_id's

2024-01-09 03:57 UTC, scarf005 commented
@chaosvolt could you review the changes after i reviewed 2 weeks ago?

2024-01-09 06:01 UTC, chaosvolt commented on data/json/mapgen/apartment_con_new.json
> +      "place_zones": [ { "type": "NPC_NO_INVESTIGATE", "faction": "no_faction", "x": [ 0, 13 ], "y": [ 30, 39 ] } ],
I have zero idea if this works as intended applying this to the "lone wolf" faction but interesting I guess.

2024-01-09 06:03 UTC, chaosvolt commented on data/json/mapgen/apartment_con_new.json
> +      [ "apartments_con_tower_113", "apartments_con_tower_013" ],
Is it intended that this be basically identical to the mapgen entry above except for placing the NPC and related zones, by the way? I guess there's no real sane or easy way to shift the ownership and zone placement such that it only triggers if the NPC spawns, though nested chunk or mapgen update stuff could be done to pare this down into just being a fixed chance of spawning in the baseline variant.

2024-01-09 06:08 UTC, chaosvolt commented on data/json/snippets/epilogue_factions.json
> +    "category": "epilogue_factions",
This should be merged into the existing faction epilogues above.

2024-01-09 06:14 UTC, chaosvolt requested changes
Proposed some easy fixes but moving the epilogues to the existing set of epilogues (honestly with how much other stuff this PR added related to him was redundant I'm surprised he doesn't already HAVE epilogues) will be slightly more complicated than what chance suggestions can do.

2024-01-09 06:14 UTC, chaosvolt commented on data/json/overmap/overmap_terrain/overmap_terrain.json
> +  },
Redundant, cabin overmap terrain already defines these IDs.
```suggestion
```

2024-01-09 06:14 UTC, chaosvolt commented on data/json/overmap/overmap_special/specials.json
> +  },
Also already exists, also we have it as a unique special with `ELECTRIC_GRID` so fucking hilarious that DDA evidently still thinks there needs to be up to two Misters Lapin per overmap chunk.
```suggestion
```

2024-01-09 06:14 UTC, chaosvolt commented on data/json/overmap/overmap_special/specials.json
> +    "flags": [ "CLASSIC", "WILDERNESS" ]
```suggestion
    "flags": [ "CLASSIC", "WILDERNESS", "ELECTRIC_GRID" ]
```

2024-01-09 06:14 UTC, chaosvolt commented on data/json/overmap/overmap_special/specials.json
> +    "flags": [ "CLASSIC", "WILDERNESS" ]
```suggestion
    "flags": [ "CLASSIC", "WILDERNESS", "ELECTRIC_GRID" ]
```

2024-01-11 00:46 UTC, chaosvolt approved these changes
Can't see anything else that stands out as odd so think it's all good, but can let Scarf take a last-minute look at it too.

2024-01-11 00:49 UTC, scarf005 approved these changes
_I highly trust CV_

could merge once the tests pass.

2024-01-11 01:33 UTC, merged

2024-03-15 09:43 UTC, Lamandus commented on data/json/npcs/cabin_chemist/cabin_chemist.json
> +        "effect": [ { "u_buy_item": "aspirin", "container": "bottle_plastic_pill_prescription", "cost": 4000, "count": 20 } ],
that is the problem. Sadly noone checked the container.