feat: seconary crafting skills gain EXP too
cataclysmbnteam/Cataclysm-BN pull request #3921
Opened 2023-12-16 06:39 UTC by chaosvolt

## Purpose of change

Implements the suggestion in https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/3825

## Describe the solution

In crafting.cpp, set it so that `player::craft_skill_gain` also calls `practice` for any secondary skills in the recipe, at half the EXP rate as the primary skill. Also makes sure to exclude cases where, for some derp reason, the primary skill is also a subskill so that doing so won't make it gain 50% more EXP.

## Describe alternatives you've considered

Trying to figure out the least clunky way to also let NPCs benefit from this.

## Testing

1. Compiled and load-tested.
2. Started crafting a heavy rail rifle via debug hammerspace and unlocking all skills.
3. Stopped it after a few seconds, observed that all the skills involved gained EXP, with primary skill of fabrication being ahead as expected.
4. Temporarily added a message that triggers when a subskill is practiced by this function, used it to confirm making a bone shiv (a weird recipe where survival is both a primary skill and a subskill) doesn't trigger the bonus practice.
5. Bumped all skills up to 3 and crafted a homemade half-pike, survival and piercing weapons didn't gain EXP since they only need level 1 instead of 3.
6. Lowered survival and piercing skill down to 1 and made another half-pike, all three skills gained EXP.
7. Checked affected file for astyle.

## Additional context

## Checklist

2023-12-16 11:11 UTC, scarf005 requested changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/653218f0-933b-478a-a6da-770a907f1d68)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/d19a5445-2d82-4590-a31c-9e2b5e389bae)

it seems that skill caps are not applied for secondary skills. also, it allows learning non-crafting skills sunch as marksmanship through crafting; would it be intended?

2023-12-16 16:02 UTC, chaosvolt commented
> it seems that skill caps are not applied for secondary skills. also, it allows learning non-crafting skills sunch as marksmanship through crafting; would it be intended?

Weird, I thought I defined a separate skill cap for secondary skills. Any idea why that's not working?

As for combat skills, if we want I could add to the "check the sub-skill isn't also primary skill" section and also filter out skills flagged as combat skills.

2023-12-16 16:30 UTC, scarf005 commented
it's because next level calculation for secondary skills use its current skill for cap which always resolves to itself (e.g -> 1 * 1.25 -> rounded to 1). i'm locally writing a fix.

2023-12-16 16:56 UTC, chaosvolt commented
Ah, whoops. I just commited a check for combat skills and that seems to work at least, hope that doesn't mess up the work on the fix. ^^"

2023-12-17 01:21 UTC, chaosvolt commented
Wait, I think I see the problem? I'm fairly certain what it's doing is using the player's level in the secondary skill as the skill cap, but what it needs to be doing is taking the recipe's skill requirement instead.

2023-12-17 01:32 UTC, chaosvolt commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/e2e2f418-c892-4d23-9fc4-26b85bd7841d)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/f06f605d-01d8-4751-91dc-877cb8306ff5)

There we go, that's more like what I was expecting.

2023-12-17 03:28 UTC, scarf005 approved these changes

2023-12-17 03:28 UTC, merged