feat(content,port): JSONize terrain flag requirement for plants.
cataclysmbnteam/Cataclysm-BN pull request #3937
Opened 2023-12-17 18:47 UTC by RoyalFox2140

## Purpose of change

Ports https://github.com/CleverRaven/Cataclysm-DDA/pull/68664 which will set cattails as growing in shallow water and It also makes it so that different plants can have different terrain requirements for farming.

## Describe the solution

To quote the original PR: 

"seed_data" has a new optional field, "required_terrain_flag". This is set to "PLANTABLE" by default. In order to plant a seed somewhere, the terrain or furniture there needs to have the given flag.
If this flag is set to anything other than "PLANTABLE", the terrain will not turn into dirt after the seed is planted. This is to prevent the water to turn into dirt when you plant stuff in it.
Places that previously checked for the "PLANTABLE" tag now instead checks for the tag specified by the "seed_data".
Cattail seeds are set to have "required_terrain_flag": "SHALLOW_WATER".
Documentation is updated to match.
A new hardcoded message string is added for when you're trying to plant a seed in an invalid spot; add_msg( _( "This type of seed can not be planted in this location." ) );. This might need translation.

This will likely change as it has issues, setting to draft and asking for help from @scarf005 as I've tried to fix the errors but my skills are too limited.

## Describe alternatives you've considered

None

## Testing

We'll get there when it works.

## Additional context

## Checklist

If this is a C++ PR that modifies JSON loading or behavior:
- [ ] Document the changes in the appropriate location in the `doc/` folder.
- [ ] If documentation for this feature does not exist, please write it or at least note its lack in PR description.
- [ ] New localizable fields need to be added to the `lang/bn_extract_json_strings.sh` script if it does not support them yet.
- [ ] If applicable, add checks on game load that would validate the loaded data.

2023-12-17 18:50 UTC, RoyalFox2140 commented
If I'm not available when it's being looked over and fixed, push through necessary changes and I will try to learn what went wrong with the port when I get back online.

2023-12-17 20:35 UTC, Vollch requested changes
We don't have `ter_furn_flag` enum, it's plain string.

2023-12-17 20:35 UTC, Vollch commented on src/activity_handlers.cpp
> +        } else if( seed_id->seed->required_terrain_flag == ter_furn_flag::TFLAG_PLANTABLE ) {
```suggestion
        } else if( seed_id->seed->required_terrain_flag == flag_PLANTABLE ) {
```

2023-12-17 20:35 UTC, Vollch commented on src/itype.h
> +    itype_id required_terrain_flag = ter_furn_flag::TFLAG_PLANTABLE;
```suggestion
    std::string required_terrain_flag = flag_PLANTABLE;
```

2023-12-17 20:43 UTC, Vollch requested changes
And also here, this const is out of scope. Just raw string should work.
(Ideally it shouldn't store default string at all, that's a waste of memory. But it's hard to fix properly using review ui -_-)

2023-12-17 20:43 UTC, Vollch commented on src/itype.h
> +    std::string required_terrain_flag = flag_PLANTABLE;
```suggestion
    std::string required_terrain_flag = "PLANTABLE";
```

2023-12-17 20:45 UTC, RoyalFox2140 commented
> And also here, this const is out of scope. Just raw string should work. (Ideally it shouldn't store default string at all, that's a waste of memory. But it's hard to fix properly using review ui -_-)

I do appreciate the help, the PR can be left open for a better rewrite if it needs a better implementation.

2023-12-17 22:50 UTC, Vollch commented
Now it want you to remove [that](https://github.com/RoyalFox2140/Cataclysm-BN/blob/6a79d1b0c0f2e98265b10cc738f1855eaeaf7dac/src/activity_item_handling.cpp#L144) unused line. I can't make a mergeable suggestion for it, it's not a part of PR.

2023-12-18 01:05 UTC, RoyalFox2140 commented
> Now it want you to remove [that](https://github.com/RoyalFox2140/Cataclysm-BN/blob/6a79d1b0c0f2e98265b10cc738f1855eaeaf7dac/src/activity_item_handling.cpp#L144) unused line. I can't make a mergeable suggestion for it, it's not a part of PR.

Done as requested

2023-12-18 03:49 UTC, RoyalFox2140 commented
Well after testing, cattail seeds can't be manually planted in shallow water because they are edible and water prompts you to drink. Zones allow you to set a farm zone but your character won't attempt to plant them in water, you can manually try to farm cattails on land and it will fail saying you should plant on shallow water, but then drops the seed.

Normal farming still works exactly the same.

2023-12-24 03:53 UTC, scarf005 approved these changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/64c92660-5391-4b72-ada6-531087c2d29e)

## Future work needed

- maybe we should differentiate activating and eating seeds someday
- farm zones should print an error message when the seed cannot be planted due to season or other reason

2023-12-24 03:53 UTC, scarf005 approved these changes

2023-12-24 03:53 UTC, merged