feat: JSONize some trap features [CR]
cataclysmbnteam/Cataclysm-BN pull request #3941
Opened 2023-12-18 01:13 UTC by chaosvolt

## Purpose of change

The continues the work started with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3939 to improve trap-related code and add some more eventually. WIP because it's a bit harder than expected to get it working.

## Describe the solution

Todo:
1. Use spawn_items from vehicle_data to define items dropped when a trap is triggered, add a function for spawning them that gets called by all trapfuncs.
2. Also create a bool, like benign, that gets used to determine if a trap is removed or not when triggered.
3. Add a function called by each trapfunc that checks the above two conditions, to spawn items if defined and remove the trap if so flagged.

## Describe alternatives you've considered

I'd say "screaming" but too late, the screm has begun.

## Testing

## Additional context

## Checklist

2023-12-18 22:12 UTC, chaosvolt commented
Discovery of the day: successfully evading a sinkhole via a grappling hook or the like spawns a pit at your NEW location, not the old one, and leaves the sinkhole intact. Confirmed in build `2023-12-12-0039` that it's not my code changes doin it.

2023-12-24 04:13 UTC, scarf005 commented on data/json/obsoletion/uncategorized.json
> +      "damage": 300,
wow that's a lot of damage.

2023-12-24 04:15 UTC, chaosvolt commented on data/json/obsoletion/uncategorized.json
> +      "damage": 300,
Straight copy of the shotgun trap that got obsoleted, so that's just how damage values of traps being hit by vehicles scales it seems (that's vehicle_data so only applies when a tire sets it off and defines what it does to the vehicle that hit it).

2023-12-24 04:18 UTC, scarf005 requested changes
Looks good, but could we document the JSON changes?

2023-12-24 04:19 UTC, chaosvolt commented
Oh yeah I knew I was forgetting something. Do we even have documentation for trap data...?

2023-12-24 04:27 UTC, scarf005 approved these changes
well, if the JSON docs for traps are missing then it'd be better as a separate PR.

2023-12-24 04:28 UTC, scarf005 approved these changes

2023-12-24 04:28 UTC, merged