feat(lua): Additional (mostly creature class-family) lua bindings
cataclysmbnteam/Cataclysm-BN pull request #3990
Opened 2023-12-27 09:24 UTC by AluminumAlman

#### Summary

SUMMARY: Infrastructure "More game, mostly creature class-family's, functions/methods exposed to Lua"

#### Purpose of change

Building on top of #2216, a whole bunch of functions for creature, character, avatar and NPC are now exposed to Lua, with other bindings in order for the aforementioned bindings to work, and a few other miscellaneous bindings.

#### Describe the solution

In order to bind most of the creature class family's methods and members to Lua, the types used/returned had to be bound to Lua first, which required additions to them, most of them covered by doc/LUA_SUPPORT.md. By using (mostly) regex, header files of the classes in question were formatted step-by-step so that it wouldn't be as tedious as doing it manually, however looking over the result was necessary sometimes. Preprocessor macros were made to make typing bindings manually less of a hassle when the regex processing didn't work.

#### Testing

- Project builds (on my machine);
- Ran some bound functions through the Lua console to make sure that they worked;

#### Additional context

- Remake of #3170 as the branch was failing to build after merge conflict fix because of the PR's staleness.
- Some of the bindings are commented out, whether it be because they are unnecessary, throw errors when building or "I did not want to confuse Lua modders with too many bindings" (I was lazy to uncomment them). If need be, those can (hopefully) be uncommented easily.
- No regression tests were done; `get_character_name` was replaced by a member of a class, therefore there may be some broken Lua mod(s) with the current state of the PR.
- Additional images:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/34545746/38f33d5a-6a23-4620-bd7c-2066422328fc)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/34545746/a805ec9d-5d39-439d-ba99-821dc958016d)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/34545746/10037e1b-8fb2-4289-ad22-3043d830d625)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/34545746/dba4c81e-7fb4-4e45-a0d5-645e7f680751)

2024-01-01 14:49 UTC, olanti-p commented on tests/lua/global_functions_test.lua
> +local creature_avatar_name = if creature_avatar then creature_avatar:get_name() else NIL_STRING
That's not valid Lua syntax. There's also no ternary operator in Lua, but it's functionality can be imitated like so:
```suggestion
local creature_avatar_name = creature_avatar and creature_avatar:get_name() or NIL_STRING
```

2024-01-01 14:49 UTC, olanti-p commented on src/catalua_bindings_creature.cpp
> +        sol::resolve< func_type >( &UT_CLASS::func_name))
These macros could be useful long-term, perhaps move them to a new/existing header? Otherwise nobody will know they exist.

2024-01-01 14:49 UTC, olanti-p commented on src/catalua_bindings_creature.cpp
> +    // from Lua to C++ functions that expect base class.
This comment doesn't make sense here anymore.
```suggestion
```

2024-01-01 14:49 UTC, olanti-p commented on src/catalua_bindings_creature.cpp
> +        // s@\(.\{-}\)\([A-z_]*\)\((.\{-}\);@SET_FX_T(\2, \1\3 );
This doesn't seem to be relevant for people working on this code in the future.
If this is a part of PR description, it should be moved into PR description.
If these are instructions on how to generate more bindings, they should be moved into the docs.

2024-01-01 14:49 UTC, olanti-p commented on src/catalua_bindings_creature.cpp
> +        //SET_FX_T( is_player, bool() const );
Commented out code (here, and everywhere else in this file) should be removed. It doesn't have any use but is guaranteed to bitrot as soon as someone changes up the relevant class.

2024-01-01 14:49 UTC, olanti-p commented on src/catalua_bindings.cpp
> +    //} );
Removing/changing functions breaks backwards compatibility. It's probably fine for now, considering there isn't (m)any mods out there that use Lua, but normally such change must be coupled with a bump to `LUA_API_VERSION`, otherwise all mods that use this will silently and semi-randomly break.

2024-01-01 14:49 UTC, olanti-p commented on src/catalua_luna_doc.h
> +#include "creature.h" // Has to be included because of Creature::Attitude
Much better solution would be to extract `Attitude` out of `Creature`. `creature.h` is mega-heavy, including it in headers propagates the mega-heaviness to many `.cpp` files and seriously worsens build times.

2024-01-01 14:54 UTC, olanti-p commented on src/catalua_bindings_creature.cpp
Breaking this up into multiple files, or breaking functions inside into smaller functions, may improve build times. Hard to say how much of these 2.3k are actual code, but considering that every function and member binding expands into many lines of template-generated code, this file ends up quite heavy.

2024-01-01 20:06 UTC, AluminumAlman commented on src/catalua_bindings_creature.cpp
> +        //SET_FX_T( is_player, bool() const );
Moved out to `catalua_bindings_utils.h`.

2024-01-01 20:07 UTC, AluminumAlman commented on src/catalua_bindings_creature.cpp
> +        sol::resolve< func_type >( &UT_CLASS::func_name))
Moved the macros out to `catalua_bindings_utils.h`.

2024-01-01 20:07 UTC, AluminumAlman commented on tests/lua/global_functions_test.lua
> +local creature_avatar_name = if creature_avatar then creature_avatar:get_name() else NIL_STRING
Whoops, got too accustomed to Luau; fixed.

2024-01-02 19:53 UTC, AluminumAlman commented on src/catalua.cpp
> +constexpr int LUA_API_VERSION = 2;
Resloved with 3454e70a429376745e717d83ec9f2a643ad5a5d4.

2024-01-05 14:30 UTC, AluminumAlman commented on doc/src/content/docs/en/mod/lua/reference/lua.md
> +`<cppval: St3mapI9string_idI23mutation_category_traitEiSt4lessIS2_ESaISt4pairIKS2_iEEE >`
> Does binding std::* containers directly as members work properly, especially ones with "exotic" types (e.g. string ids)? If not, it may require hacking around by adding accessor functions.

It appears that it does:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/34545746/a4146fed-7079-41a2-9c2e-7521e0685c99)

2024-01-06 09:13 UTC, scarf005 requested changes
> feat!: Additional Lua bindings, documentation, attitude decoupled from creature

Would it be possible to list commits or changes for `attitude decoupled from creature`? As this is a huge change ![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/be846c94-c834-449c-805d-8221306f2e46), Splitting this PR into two step would make it easier to review, e.g)

1. `refactor: decouple attitude from creature`
2. `feat!: additional lua bindings`
huge

2024-01-06 12:13 UTC, AluminumAlman commented
Splitting this PR into two per request of scarf005.

2024-01-06 12:13 UTC, closed without merging