feat(content): Thick socks
cataclysmbnteam/Cataclysm-BN pull request #4079
Opened 2024-01-09 00:34 UTC by yay855

## Purpose of change

Normal socks are not very warm, but wool socks can be annoying to acquire. Thicker cotton socks makes perfect sense.

## Describe the solution

Added in new item, thick socks, and corresponding recipe. They're half as warm as wool socks.

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2024-01-09 00:58 UTC, chaosvolt commented on data/json/items/armor/boots.json
> +    "material_thickness": 2
5 more warmth than stockings but still zero encumbrance? o3o

2024-01-09 03:51 UTC, scarf005 commented on data/json/items/armor/boots.json
> +    "material_thickness": 2
yeah, increasing encumbrance a bit could work.

2024-01-09 09:54 UTC, RoyalFox2140 requested changes
I own a pair of something like this IRL and I can say its at least 2 or 3 encumbrance because its slightly harder to walk around in. The extra material is a bit cumbersome but not by that much. I'd also say for balance we tend to have winter clothing give higher encumbrance, especially because of layering blunt and cut armor in winter to fight zombies without taking damage, so it needs a trade-off so it would follow more internal balance consistency to encumber a player.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/cb475de9-4343-42e9-af47-fc6773b21b6d)

2024-01-10 00:02 UTC, yay855 commented on data/json/items/armor/boots.json
> +    "material_thickness": 2
There we go, added 3 encumbrance to them.

2024-01-10 00:02 UTC, chaosvolt approved these changes

2024-01-10 00:37 UTC, merged