docs: add info for mutation enchantments
cataclysmbnteam/Cataclysm-BN pull request #4118
Opened 2024-01-17 18:49 UTC by RoyalFox2140

## Purpose of change

There was poor documentation for adding effects via mutation, I added documentation for doing this with mutation enchantments.

## Describe the solution

In json_info.md The field for enchantments is added.

in effects_json.md I gave an in-repo example of a mutation that grants an enchantment, and an example of an enchantment that grants a permanent effect.

## Describe alternatives you've considered

Keeping it a mystery because that's funnier. Bugging others.

## Testing

It's docs.

## Additional context

Pain

2024-01-17 18:51 UTC, scarf005 requested changes

2024-01-17 18:51 UTC, scarf005 commented on doc/src/content/docs/en/mod/json/reference/creatures/effects_json.md
> +"multiply": -0.08 }, { "value": "ARMOR_BULLET", "multiply": -0.15 } ] }
could we use code block to syntax highlight it?
https://youtu.be/qkdTuuwmxwQ?si=hoILJGTH0QSKMAf_

2024-01-18 00:28 UTC, chaosvolt approved these changes
Seems to be gud :>

2024-01-18 01:32 UTC, scarf005 commented
dismissing existing reviews doesn't do anything, approving does.

2024-01-18 01:32 UTC, merged