feat:add paddy field and soil-to-clay constr
cataclysmbnteam/Cataclysm-BN pull request #4197
Opened 2024-02-07 18:53 UTC by NappingOcean

## Purpose of change

Add a paddy field and construction for gathering clay from soil.
Former is expansion of #4120, latter is for QoL.
No more struggles in order to finding clay.

## Describe the solution

### Construct a paddy field
Unlike a field, the composition of the soil in a paddy field is important. This is because the clay holds water and creates the right environment for crops like rice.
So I made it so that clay is required for construction. Since rice paddies are always planted on lower ground, I had them start with a shallow pit, and finally, just in case, I created a construction to remove it.

### Gather more clay
Clay is in unexpectedly high demand.
Especially before you can make a clay crucible, or when you're out in the wild and can't find a pot and need to make a clay pot.
However, many of the methods of obtaining clay rely on luck, so to reduce that dependency for better QoL, I created this construction.
Put 50 unit soil and 64 water, then get your homemade clay terrain.

## Describe alternatives you've considered

## Testing

## Additional context

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/129575271/c2166ce0-fa73-423d-897d-8a4ef38df248)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/129575271/5b0c6e72-09e3-4974-84e1-a460c812c988)

I add `"iexamine_action": "dirtmound"`.
It works well, but also allows other seeds which don't need `SHALLOW_WATER` flag.
I can't decide to remove it or not.

## Checklist

2024-02-08 03:46 UTC, NappingOcean commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "description": "A damp, muddy field used to grow crops that require a lot of water. The clay holds moisture, making it perfect for the crops.",
```suggestion
    "description": "A damp, muddy field used to grow crops that require a lot of water. The clay holds moisture, making it perfect for the crops.", 
```

2024-02-08 04:14 UTC, NappingOcean reviewed
2 space.

2024-02-08 04:14 UTC, NappingOcean commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "description": "A pit filled with muddy water. Neither used as a water source nor ground. Keep pouring water and stirring it.",
```suggestion
    "description": "A pit filled with muddy water.  Neither used as a water source nor ground.  Keep pouring water and stirring it.",
```

2024-02-08 16:19 UTC, chaosvolt requested changes
Mostly could but some suggestions mebbe

2024-02-08 16:19 UTC, chaosvolt commented on data/json/construction.json
> +    "components": [ [ [ "clay_lump", 8 ] ], [ [ "water", 4 ], [ "water_clean", 4 ] ], [ [ "material_sand", 1 ], [ "material_soil", 2 ] ] ],
1 soil is 5 liters, 1 sand is 5 ml. Suggestion here uses the same ratio that "Fill Shallow Water With Dirt" uses, which is still barely any but eh, doesn't have to be exact given that would require 2000 sand:
```suggestion
    "components": [ [ [ "clay_lump", 8 ] ], [ [ "water", 4 ], [ "water_clean", 4 ] ], [ [ "material_sand", 20 ], [ "material_soil", 2 ] ] ],
```

2024-02-08 16:19 UTC, chaosvolt commented on data/json/construction.json
> +    "byproducts": [ { "item": "pebble", "charges": [ 2, 16 ] } ],
This I assume should probably be clay lumps instead of pebbles, and equal the amount of clay you get out of `constr_extract_clay`?
```suggestion
    "byproducts": [ { "item": "clay_lump", "charges": [ 6, 12 ] } ],
```

2024-02-08 16:19 UTC, chaosvolt commented on data/json/construction.json
> +    "post_terrain": "t_clay"
Likewise, extracting clay from a pit of soil probably shouldn't turn it into a solid mound of clay you can then extract even more from:
```suggestion
    "post_terrain": "t_dirt"
```

2024-02-08 16:19 UTC, chaosvolt commented on data/json/furniture_and_terrain/terrain-floors-outdoors.json
> +    "description": "A pit filled with muddy water.  Neither used as a water source nor ground.  Keep pouring water and stirring it.",
Weird phrasing for second sentence, and the last sentence might confuse players as to whether to drop water on it or not.
```suggestion
    "description": "A pit filled with muddy water.  With additional work, some clay could be separated from the silt.",
```

2024-02-08 17:18 UTC, chaosvolt commented on data/json/construction.json
> +    "components": [ [ [ "clay_lump", 8 ] ], [ [ "water", 4 ], [ "water_clean", 4 ] ], [ [ "material_sand", 1 ], [ "material_soil", 2 ] ] ],
Could work then, soil's more reliable to get than sand so.

2024-02-08 22:50 UTC, RoyalFox2140 requested changes
left clarification on rice paddies and on the clay extraction.

2024-02-08 22:50 UTC, RoyalFox2140 commented on data/json/construction.json
> +    "components": [ [ [ "clay_lump", 8 ] ], [ [ "water", 4 ], [ "water_clean", 4 ] ], [ [ "material_sand", 1 ], [ "material_soil", 2 ] ] ],
Rice paddies require a hard layer of solid clay to trap water molecules in the pond. Sand is too porous to contain water so you want as much compacted clay as possible. There's a lot of research here but that's the jist of how a paddy field is done.

2024-02-08 22:50 UTC, RoyalFox2140 commented on data/json/construction.json
> +    "post_terrain": "t_clay"
"t_clay" is a deep clay deposit, you're only settling and filtering some surface dirt to get the silt and sand out of the clay so it leaves dirt.

2024-02-09 00:32 UTC, chaosvolt requested changes
Forgot one

2024-02-09 00:32 UTC, chaosvolt commented on data/json/construction.json
> +    "post_terrain": "t_clay"
```suggestion
    "post_terrain": "t_dirt"
```

2024-02-09 03:28 UTC, NappingOcean reviewed
Accept to change `t_clay` to `t_dirt`, and adjust other things accordingly.

2024-02-09 03:28 UTC, NappingOcean commented on data/json/construction.json
> +    "byproducts": [ { "item": "clay_lump", "charges": [ 6, 12 ] } ],
Consuming 90 minutes looks too much to get clay same as extracting.
So I cut the time to 2/3, and slightly increase the clay.

```suggestion
    "time": "60 m",
    "qualities": [ [ { "id": "DIG", "level": 1 } ] ],
    "byproducts": [ { "item": "clay_lump", "charges": [ 8, 16 ] } ],
```

2024-02-09 03:46 UTC, chaosvolt approved these changes
:3

2024-02-09 04:53 UTC, merged