feat(content): Innawood
cataclysmbnteam/Cataclysm-BN pull request #4224
Opened 2024-02-11 22:04 UTC by Zlorthishen

clean-room reverse engineered

## Purpose of change
Adds a BN version of `innawood`

## Describe the solution

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2024-02-12 01:02 UTC, chaosvolt requested changes
Okay so...it relies a lot on full overrides for things like overmap terrain, region settings, and even scenarios. In fact the scenario override especially is really bad.

If it breaks when city size is above zero in the first place then just leave scenarios untouched, scenarios with the `CITY_START` flag are already automatically excluded in zero-city-size worlds.

2024-03-03 20:47 UTC, chaosvolt commented
Re-stating it here: the full scenario overrides are not nessecary and will just break compatibility with other mods.

2024-03-20 13:39 UTC, chaosvolt requested changes
And now you have full overrides of overmap specials instead of using `copy-from`?

2024-03-24 04:39 UTC, chaosvolt requested changes

2024-03-24 04:39 UTC, chaosvolt commented on data/mods/innawoods/specials.json
> +    "id": "trailhead_basic",
The continued saga of large numbers of full overrides to overmap specials still polluting this mod.

2024-03-24 20:07 UTC, Lamandus commented on data/mods/innawoods/specials.json
> +    "id": "trailhead_basic",
what @chaosvolt is trying to say is the following mantra:

The less lines you have to change, the better. Using "copy from" would be a good starting point. Try to recycle as much as you can.

2024-03-31 23:05 UTC, chaosvolt approved these changes
Okay, I think...hope, it's ready...

2024-04-01 14:22 UTC, merged