feat(content,port): Centipede overhaul
cataclysmbnteam/Cataclysm-BN pull request #4246
Opened 2024-02-22 01:29 UTC by Zlorthishen

## Purpose of change

## Describe the solution

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2024-02-22 01:44 UTC, scarf005 submitted a review, later dismissed
please add co-authors to each commits.

2024-02-22 01:45 UTC, Zlorthishen commented
> please add co-authors to each commits.

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/79779913/fa906b70-7184-41bf-93ef-c092450d5956)

2024-02-22 03:40 UTC, scarf005 commented
![Screenshot_2024-02-22-12-38-31-080_com.github.android.jpg](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/7f8d1336-3a55-4723-8dc2-d84e343b72ef)

sorry @Zlorthishen, i didn't know that github mobile lacked commit details/co-author display like on browser.

2024-02-23 18:39 UTC, chaosvolt requested changes

2024-02-23 18:39 UTC, chaosvolt commented on data/json/effects.json
> +    "resist_traits": [ "POISRESIST" ],
```suggestion
    "resist_traits": [ "POISRESIST" ],
    "resist_effects": [ "antitoxin" ],
```

2024-02-23 18:39 UTC, chaosvolt commented on data/json/effects.json
> +    "resist_traits": [ "POISRESIST" ],
```suggestion
    "resist_traits": [ "POISRESIST" ],
    "resist_effects": [ "antitoxin" ],
```

2024-02-24 03:42 UTC, scarf005 approved these changes

2024-02-24 03:42 UTC, merged