fix: nets should not deal damage
cataclysmbnteam/Cataclysm-BN pull request #4341
Opened 2024-03-12 07:24 UTC by ekaratzas

As the title implies, nets should not be dealing damage to the monsters they envelop. No matter how hard you throw a net, you are just throwing a net, it shouldn't kill a chicken in 2 throws.

Introduce NO_DAMAGE flag to deal with projectiles that should apply effects but not actually deal damage using typical logic.

## Purpose of change

Currently throwing a net to envelop a creature actually deals damage using regular damage formula, albeit with the NOGIB flag preventing overkill. However just 1 throw can severely injure a small creature (e.g. chicken) and I have managed to kill chickens in a couple of throws just by throwing nets.

In several video-games nets are typically just effect-applying items, not damage dealing items. Also throwing a net so hard you kill something is silly and unfun - ask me how I know.

This change prevents nets from dealing damage - they still deal the tangle effect, same as before.

## Describe the solution

Solution works by introducing a new flag called NO_DAMAGE. This flag gets applied to projectile and we simply check if it's present in Creature::deal_projectile_damage(). If it is present, we just nullify the impact damage of the projectile.

## Describe alternatives you've considered

Considered applying this flag to bolas item too but was on the fence. On one hand, it's a much more violent thrown item compared to a net so it could deal damage - on the other hand, it's annoying to kill what you are trying to capture. Open to feedback on this.

## Testing

Character with all stats at 12, throwing at 10 - many nets.
Use net to 'tangle' monster. Tangle still works ok.
Throw 10 nets at chicken. Chicken takes no damage.

## Additional context
![catch-a-chicken-net](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/4570952/affccab8-a78b-4dc5-89a5-91c351cfe512)

## Checklist

2024-03-15 09:00 UTC, Lamandus commented
I wonder if there are other objects that could actually get that tag, like bolas. Can you check if you find it plausible? That way we can introduce the tag in multiple items.

2024-03-15 17:00 UTC, ekaratzas commented
> Considered applying this flag to bolas item too but was on the fence. On one hand, it's a much more violent thrown item compared to a net so it could deal damage - on the other hand, it's annoying to kill what you are trying to capture. Open to feedback on this.

I'm open to the idea of also applying this to bolas.

2024-03-26 22:41 UTC, Lamandus commented
> > Considered applying this flag to bolas item too but was on the fence. On one hand, it's a much more violent thrown item compared to a net so it could deal damage - on the other hand, it's annoying to kill what you are trying to capture. Open to feedback on this.
> 
> I'm open to the idea of also applying this to bolas.

please check for those items and if you are quite sure, that there are no other ones left, merging can happen.

2024-03-26 22:41 UTC, Lamandus requested changes
bolas, etc, should be included.

2024-03-26 23:59 UTC, ekaratzas commented
added a commit to also use this new flag for bolas, also rebased on top of latest main

2024-03-27 05:32 UTC, Lamandus approved these changes

2024-03-27 05:32 UTC, merged