chore: delete camps
cataclysmbnteam/Cataclysm-BN pull request #4369
Opened 2024-03-19 06:51 UTC by Dread-Pirate-Hogarth

## Purpose of change

https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/3866

## Describe the solution
delete

didn't try to preserve savegames. discussion said we didn't need to, so I didn't. don't think you could find anyone that'd do that stupid amount of work.

should build but haven't done so yet

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2024-03-19 07:13 UTC, RoyalFox2140 commented
This must've been a monumental amount of work to do. I hope everything goes off without a hitch.

2024-03-19 08:15 UTC, Dread-Pirate-Hogarth commented
> This must've been a monumental amount of work to do. I hope everything goes off without a hitch.

was much faster to do from the web interface, did a check afterwards to see if any errors were reported. must've missed some stuff

2024-03-19 20:28 UTC, Lamandus commented
Please try to fix the errors soonish

2024-03-21 05:41 UTC, scarf005 commented on src/condition.cpp
>          }
i think closing bracket should be removed too.

2024-03-21 06:11 UTC, scarf005 requested changes
hi, thanks for the hard work!

however, there's many issues preventing the PR from building, namely:

- many files like map.cpp and mapgen.cpp still references basecamp (e.g `#include "basecamp.h"` or `bcp`)
- (faction camp) bulletin board function missing in iexamine.cpp
- faction.cpp has unwrapped brackets which breaks function signature in `npc::faction_display`
- also unwrapped brackets in `condition.cpp`
- `job_data` unremoved
- missing `companion_mission`. i think it's maybe used for other cases than faction camp?

could you make sure the PR can be built locally and mark it as ready?

2024-03-21 13:48 UTC, Dread-Pirate-Hogarth commented
no need to run tests yet i have it in vs

will tell you when it compiles

2024-03-21 14:21 UTC, Dread-Pirate-Hogarth commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/163970638/470f5c58-6fdc-4750-935d-52ed3373dbf7)


didn't see any use for companion_mission outside of camp but will double check

2024-03-21 16:25 UTC, Dread-Pirate-Hogarth commented
companion_mission only gets used at the board for camp mission
not much use buying land for your camp that doesn't exist

regular talk_mission_list still works

npc go_to you from radio is broken but seems that was broken before the PR

2024-03-22 08:19 UTC, scarf005 commented
one major save-breaking issue: npcs sent scavenging from faction camp before the faction camp removal will be lost. @Dread-Pirate-Hogarth maybe should we take care of this.

2024-03-22 21:43 UTC, Dread-Pirate-Hogarth commented
they should load now. will be placed wherever they were when sent on mission

will still have junk data for npc_companion_mission but this is not a big issue. data will not impact performance and can be removed later or kept for use in new systems

2024-03-23 02:24 UTC, scarf005 commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/0cb4d7d5-fec5-402e-8d3a-00eab0684a72)

they do return correctly now.

2024-03-24 07:49 UTC, scarf005 approved these changes
it errors with invalid zone type on load but can be easily resolved by removing said zone. overall LGTM but would like to wait for @Coolthulhu's opinion.

2024-03-24 09:31 UTC, Lamandus commented
> it errors with invalid zone type on load but can be easily resolved by removing said zone. overall LGTM but would like to wait for @Coolthulhu's opinion.

But only one error, or all the time?

2024-03-25 06:11 UTC, scarf005 commented
it'll keep error on load until all existing camp related zones are removed.

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/e1c3e400-1c00-4271-b0cd-8549b7a3eb6e)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/7f7b9702-e9b8-4a9a-b25e-460575bdf590)

2024-03-25 06:46 UTC, Lamandus commented
Then loot-zones.json has to be changed, too

2024-03-25 07:00 UTC, Lamandus requested changes
Changes to the loot zones have to be made. Not only in the json, I suppose in the source code, too.

2024-03-25 07:01 UTC, Lamandus commented
> it'll keep error on load until all existing camp related zones are removed.
> 
> ![image](https://private-user-images.githubusercontent.com/54838975/316403293-e1c3e400-1c00-4271-b0cd-8549b7a3eb6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTAzMDcsIm5iZiI6MTcxMTM1MDAwNywicGF0aCI6Ii81NDgzODk3NS8zMTY0MDMyOTMtZTFjM2U0MDAtMWMwMC00MjcxLWIwY2QtODU0OWI3YTNlYjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NDljZDU5NzczYzI5YzQwNzZlNDAyMTNmYTMwYmFkYmZlYTc3ZjYyODRjMDMwMjAxYmM4Y2YyN2Q3M2JkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bDHN1Ks6c83wGfyqes7-NE3LfQ0YOuM586hMQQkYZJ4)
> 
> ![image](https://private-user-images.githubusercontent.com/54838975/316403629-7f7b9702-e9b8-4a9a-b25e-460575bdf590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTAzMDcsIm5iZiI6MTcxMTM1MDAwNywicGF0aCI6Ii81NDgzODk3NS8zMTY0MDM2MjktN2Y3Yjk3MDItZTliOC00YTlhLWIyNWUtNDYwNTc1YmRmNTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MDg0ZjEzMWVjZTE2MzRjNzdiNGYzMDQzNTcwMmYyYzkxZTVkNTc5MTljY2MxMjk3YzE2NDU4YjAyOThhMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.71RTDP02UlfNd-Ard53JslFq7EmDpJJGX7eoelR0Eww)
> 
> strangely, only `CAMP_FOOD` will error; `basecamp: storage` won't.

I suppose it is because storage is "just food storage". While camp food is linked to a function.

2024-03-25 09:43 UTC, Dread-Pirate-Hogarth commented
ill take a look

2024-03-27 07:47 UTC, Dread-Pirate-Hogarth commented
simple preexisting error in implementation of iterator. if zone exists in loaded world, should error once and properly erase invalid zone now.

2024-03-27 07:55 UTC, Lamandus commented
> simple preexisting error in implementation of iterator. if zone exists in loaded world, should error once and properly erase invalid zone now.

gonna take a look now, I am compiling it, will take a few minutes for testing.

2024-03-27 07:57 UTC, Dread-Pirate-Hogarth commented
i pushed another fix right after you posted. make sure you check that one

2024-03-27 09:43 UTC, Lamandus approved these changes

2024-03-27 09:43 UTC, merged

2024-03-27 11:00 UTC, scarf005 commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/90513a3a-94ea-4293-b970-934d71c2caae)

this causes segmentation fault on loading old save.