feat(content,port): Add `Brawler` trait
cataclysmbnteam/Cataclysm-BN pull request #4382
Opened 2024-03-23 01:18 UTC by Zlorthishen

## Purpose of change
- https://github.com/CleverRaven/Cataclysm-DDA/pull/57948

## Describe the solution

## Describe alternatives you've considered

## Testing

## Additional context
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/79779913/76786163-7368-42af-a16f-abe5f2154c35)

## Checklist

2024-03-23 18:19 UTC, chaosvolt commented on data/json/mutations/mutations.json
> +    "points": -4,
Only 4 points for giving up the primary way to deal with hulk-tier enemies, bloated zombies, acidic zeds, electric zeds, and hostile NPCs seems underwhelming considering Wayfarer is -8.

2024-03-23 18:27 UTC, Zlorthishen commented on data/json/mutations/mutations.json
> +    "points": -4,
-7 ?

2024-03-24 01:57 UTC, chaosvolt commented on data/json/mutations/mutations.json
> +    "points": -4,
Eh, 8 is probably good enough to be consistent at least, since which facet of gameplay is more important to the player will likely be subjective.

I've said before in the discord that Wayfarer is either the best source of free points ever or the worst trait ever, with zero middle ground, depending entirely on one's playstyle and world settings. XP

2024-03-24 03:06 UTC, chaosvolt requested changes
1. Compiled and load-tested.
2. Started off with Brawler trait.
3. Spawned in an M4A1.
4. Trying to fire it prints the message twice.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/df1532a3-e4c5-4749-9a66-d9d6e2eca087)

2024-03-24 06:28 UTC, scarf005 commented
@Zlorthishen did you also port https://github.com/CleverRaven/Cataclysm-DDA/pull/60328 ?

2024-03-24 19:17 UTC, Zlorthishen commented
> @Zlorthishen did you also port [CleverRaven/Cataclysm-DDA#60328](https://github.com/CleverRaven/Cataclysm-DDA/pull/60328) ?

I did now, it also fixed the double message problem CV found
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/79779913/9115002d-4fe2-44a4-933d-0e85f24ab520)

2024-03-24 21:52 UTC, chaosvolt commented
> I did now, it also fixed the double message problem CV found

Nope. Try wielding a weapon with more than one fire mode, that's probably why it's doing this.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/bd59fdea-4ef3-4b6d-8d4f-ab18301b5604)

2024-03-25 07:50 UTC, Lamandus commented
> > I did now, it also fixed the double message problem CV found
> 
> Nope. Try wielding a weapon with more than one fire mode, that's probably why it's doing this. ![image](https://private-user-images.githubusercontent.com/11582235/316345433-bd59fdea-4ef3-4b6d-8d4f-ab18301b5604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTMyNTEsIm5iZiI6MTcxMTM1Mjk1MSwicGF0aCI6Ii8xMTU4MjIzNS8zMTYzNDU0MzMtYmQ1OWZkZWEtNGVmMy00YjZkLThkNGYtYWIxODMwMWI1NjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NjZjNzE3YWFkNDg4ZTdlZjNjMWRjNjMzMDAxMDA4ZmFlYzNlMWExMTk0NmU3ZTZjNjBjNTNkNDgzYzdmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u-E2PVUgWOBrF_N4sauJS8iPBZNV_WOpAtJYrUTZeuE)
> 
> EDIT: Yep, m1911 prints it just once but m4a1 prints it twice. ![image](https://private-user-images.githubusercontent.com/11582235/316345520-2f20b0c0-fd4a-41f1-a751-3b4d762d2d9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTMyNTEsIm5iZiI6MTcxMTM1Mjk1MSwicGF0aCI6Ii8xMTU4MjIzNS8zMTYzNDU1MjAtMmYyMGIwYzAtZmQ0YS00MWYxLWE3NTEtM2I0ZDc2MmQyZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Yjk5NGRmYzVkMmY4NTRhZjQ0Yzk1MzJhOTAxYTY1ODMxZmExYmQzMWFmODgwMzdlMmI5NDhjOTU3MjUyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VuZGarZSBFeug0BAXn6Tc0i8AgD4wwxzszpkD9fIes4)

I wonder if a gun with a bajonett does it more.

2024-03-25 14:28 UTC, chaosvolt commented
I didn't even get to the point of testing reach weapons or bayonets yet since the message spam issue keeps being the first problem I run into. XD

2024-03-28 16:20 UTC, Zlorthishen commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/79779913/e3965aa6-dabf-498c-a42a-e5f16d8e5f07)

2024-03-28 17:18 UTC, chaosvolt approved these changes
1. Compiled and load-tested.
2. Spawned in an M4A1, confirmed you only get the message for Brawler once, and can still cycle through fire modes.
3. Slapped a bayonet on, confirmed it works with `f` when cycled to bayonet, or via `tab` for general melee.
4. Likewise tested to confirm a spear works with `f` and `tab`.
5. Spawned in a holstered M1911, hitting `f` with empty hands still lets me draw the pistol but then goes "oh wait brawler, guns meh" once it's wielded.
6. Spawned in an humvee, confirmed I can neither fire the mounted M2 manually nor remotely from the controls.

2024-03-28 17:53 UTC, KheirFerrum requested changes

2024-03-28 17:53 UTC, KheirFerrum commented on src/handle_action.cpp
> +            }
These additions probably shouldn't be here. This should all be handled in `can_fire_turret()`, and referenced by appropriate functions.

You'll want to add an if block to `bool vehicle::turrets_aim_and_fire_all_manual( bool show_msg )` using `can_fire_turret()` the way that `void avatar_action::fire_turret_manual( avatar &you, map &m, turret_data &turret )` does it, or you can add it downstream from `turrets_aim_and_fire_all_manual` in `int vehicle::turrets_aim_and_fire( std::vector<vehicle_part *> &turrets )` instead. Either way, cut down on the number of times this code is repeated, so nobody has to go hunting when we want to edit other restrictions on turret use.

2024-03-28 17:53 UTC, KheirFerrum commented on src/avatar_action.cpp
> +        add_msg( m_good, _( "Pfft.  You are a brawler; using this weapon is beneath you." ) );
This comment is out of place, given that the description says it's possibly trauma, make it more neutral like the other comment where the player simply refuses.

2024-03-28 17:53 UTC, KheirFerrum commented on src/ranged.cpp
> +static const trait_id trait_BRAWLER( "BRAWLER" );
No longer used, remove

2024-03-28 17:53 UTC, KheirFerrum commented on src/turret.cpp
> +
Same as other comment earlier, this should be handled by `can_use_turret()` only. Likely added because the original author was plugging holes, as this covers the issue that firing from the controls will bypass `can_use_turret()`. Will be fixed if you add a `can_use_turret()` check to `avatar_action::fire_turret_manual()` or `vehicle::turrets_aim_and_fire()` as suggested earlier.

2024-03-28 20:35 UTC, Zlorthishen commented on src/handle_action.cpp
> +            }
> These additions probably shouldn't be here. This should all be handled in `can_fire_turret()`, and referenced by appropriate functions.
I removed the redundant checks, it still works correctly

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/79779913/673b53de-cfd3-46c7-8290-8e9bef43e2a7)

2024-03-28 20:46 UTC, Zlorthishen commented on src/handle_action.cpp
> +            }
> You'll want to add an if block to `bool vehicle::turrets_aim_and_fire_all_manual( bool show_msg )` using `can_fire_turret()` the way that `void avatar_action::fire_turret_manual( avatar &you, map &m, turret_data &turret )` does it, or you can add it downstream from `turrets_aim_and_fire_all_manual` in `int vehicle::turrets_aim_and_fire( std::vector<vehicle_part *> &turrets )` instead. Either way, cut down on the number of times this code is repeated, so nobody has to go hunting when we want to edit other restrictions on turret use.

there is already an if {} check in `vehicle::turrets_aim`, isn't that sufficient already?

2024-03-29 00:20 UTC, KheirFerrum requested changes

2024-03-29 00:20 UTC, KheirFerrum commented on src/handle_action.cpp
> -
So when I said you should remove those lines I meant the if block the PR added that checked the brawler flag, you should restore all of these. My bad for not being clear.

2024-03-29 00:20 UTC, KheirFerrum commented on src/handle_action.cpp
> +            }
> > You'll want to add an if block to `bool vehicle::turrets_aim_and_fire_all_manual( bool show_msg )` using `can_fire_turret()` the way that `void avatar_action::fire_turret_manual( avatar &you, map &m, turret_data &turret )` does it, or you can add it downstream from `turrets_aim_and_fire_all_manual` in `int vehicle::turrets_aim_and_fire( std::vector<vehicle_part *> &turrets )` instead. Either way, cut down on the number of times this code is repeated, so nobody has to go hunting when we want to edit other restrictions on turret use.
> 
> there is already an if {} check in `vehicle::turrets_aim`, isn't that sufficient already?

I want that check gone and replaced with the check I mentioned. The check in `turrets_aim()` is very late down the chain and more importantly independently checks for the brawler flag instead of checking `can_fire_turret()`. This is a problem because it means that the game doesn't actually ever check `can_fire_turret()` if you use it from the control panel.

2024-03-29 00:31 UTC, Zlorthishen commented on src/handle_action.cpp
> -
restored

2024-03-29 00:46 UTC, KheirFerrum commented on src/handle_action.cpp
> +            }
Update: I looked into what would be required to make this work and it will require migration of `turrets_aim_and_fire_all_manual()` and `turrets_aim_and_fire_single()` to `avatar_actions.cpp`, as well as tweaks to `can_fire_turrets()` so that it can handle arrays of turrets. Therefore I'll consider this out of scope since the issue is much more complex and has existed before this PR.

2024-03-29 01:04 UTC, KheirFerrum commented
Alright, everything looks fine. This will require a followup PR to fix a bug exposed here though. Namely that `can_fire_turrets()` is not called in any capacity when firing turrets from the control panel.

Fixing this will require migration of `turrets_aim_and_fire_all_manual()` and `turrets_aim_and_fire_single()` to `avatar_actions.cpp`, as well as tweaks to `can_fire_turrets()` so that it can handle arrays of turrets. Likely merging the two functions above into a single function. I _hate_ all this spaghetti. Here's hoping I don't end up fucking up my exam prep cause of a compulsion to fix this shit.

2024-03-30 00:26 UTC, chaosvolt approved these changes

2024-03-30 00:26 UTC, merged