fix: Recipe changes to address land mine component inconsistencies
cataclysmbnteam/Cataclysm-BN pull request #4389
Opened 2024-03-25 17:55 UTC by NerdPunkFu

## Purpose of change

To fix land mine component inconsistencies in regard to real life land mines and other explosives within the game. For more issue see #4381. To fully address the issue land mines still need to be divided into real world or fictional models, but this requires the land mine trap effect to be moved from an hardcoded effect to something that can be modified by JSON. 

## Describe the solution

Introduces my changes to the crafting and uncrafting recipes for land mines mentioned in #4381. For crafting I added bone glue, changed the fragmentation element to be the same as the scrap loaded 00 shot recipe just 10x to be in line with what it was before, got rid of all that random nonsense that were useable as explosive and instead used the same lists as other explosives used equivalent in amount to 600 composition b and lastly I added the option to use fuses for landmines since for example the M16 mine uses a black powder fuse(there should be a mechanism to light it when stepped on so maybe a "makeshift fuze" item should be added that is made of fuse and some method to light it e.g. flint and steel). For disassembly I just increased the composition b amount to 600 and added bearings as frag.

## Describe alternatives you've considered

Rewrite how the game handles land mine traps, but this requires rewriting the hardcoded effect land mine traps currently have. Also, there is ambiguity about what kind of land mine the ingame landmines are supposed to be, I just assumed it's a classic explodes-in-the-ground type of land mine that has a charge about as strong as a claymore or M16 mine, but AFAIK the US military does not use such mines and none of them have composition b as main charges, but we do not have TNT or C4 in increments that would make it useable in crafting like we do for composition b or other explosives like RDX. We should probably also address this deficiency in the future, no reason why a player could take bits of C4 to make custom charges. It's basically a hard, chewy playdough style paste. TNT is harder, but probably still possible?

## Testing

Got no errors booting up, crafting or uncrafting in my playthrough using these changes.

## Additional context

## Checklist

2024-03-25 18:30 UTC, chaosvolt commented
You could potentially also use impact fuzes (`impact_fuze`) in addition to or instead of regular fuzes for flavor.

2024-03-25 19:58 UTC, chaosvolt commented
Fair point, I just figured it'd be good for flavor, a better choice than gunpowder fuses (though having a craftable option is probably okay for balance).

2024-03-25 20:07 UTC, chaosvolt submitted a review, later dismissed

2024-03-25 20:15 UTC, NerdPunkFu commented
> Fair point, I just figured it'd be good for flavor, a better choice than gunpowder fuses (though having a craftable option is probably okay for balance).

[This is an example](https://www.youtube.com/watch?v=1FlUOdCcasI) of how you could do a gunpowder fuse for a mine(or grenade). As I laid out before, you'd need a method of lighting it though and maybe a spring mechanism because random amounts of pressure applied over a random amount of time is probably not the best way to strike a match or some such.

2024-03-26 00:28 UTC, Lamandus commented
> > You could potentially also use impact fuzes (`impact_fuze`) in addition to or instead of regular fuzes for flavor.
> 
> That probably wouldn't work actually. There are different impact fuzes but a lot of them are something [like this](https://www.youtube.com/watch?v=FxHmJtOSIcM). As you can see, the fuze relies on quite a bit of force and the inertia of the round. An anti-tank mine might work with something like that, but a human foot isn't likely to generate enough force to crush that fuze and send the firing pin into the initial charge(the safety could probably be circumvented easy enough).

on the one hand you are right,

on the other, I would like to have the chance to use impact fuses, too, we can craft high end pneumatic weaponary with very ordinary things, so I think making it work with a impact fuse, would be favourable.

2024-03-26 08:27 UTC, Lamandus requested changes
Adding the other fuse would be better.

2024-03-26 17:27 UTC, Lamandus approved these changes

2024-03-26 17:49 UTC, chaosvolt approved these changes

2024-03-26 18:19 UTC, merged