feat(balance): Changing Values for the Suppressors
cataclysmbnteam/Cataclysm-BN pull request #4490
Opened 2024-04-16 09:28 UTC by spyfox321

Removed Damage Penalty from the makeshift suppressors and tweaked the handling of the MP5SD integral suppressor.

The damage modifier for the MP5SD suppressor has Intentionally not changed to reflect its unique subsonic internal suppressor.

## Purpose of change
Suppressors in real life don't decrease the Velocity of bullets, decreasing the damage. The normal suppressors don't have a negative damage modifier, so I removed them to make consistent.

## Describe the solution

Fully removed the damage penalty from makeshift suppressor, soda bottle suppressor, and shotgun suppressor.

I've intentionally left the MP5SD's internal suppressor as it's a uniquely designed suppressor to slow the bullet to a subsonic round.

## Describe alternatives you've considered

Theoretically, if the loudness values are great enough, I think as a balance mechanic it would be viable to keep the damage penalty. But from my experience, I considered the loudness modifiers as "realistic" so I wanted to tweak the modifiers as such.

I would've adjusted the suppressor's loudness modifier too to make the suppressors most realistic, but just by checking the JSON, it's hard to check how loud the are guns and what the loudness values truly mean.

## Testing

## Additional context

Currently, it's very unclear to me how much of what is loudness value means. if someone can/want to adjust the loudness modifiers too, feel free.

## Checklist

2024-04-16 09:31 UTC, scarf005 requested changes
`feat(balance): Changing Values for the Suppressors`

could we have a more descriptive PR title? from the PR title alone it's not obvious what the changes are (e.g is it a nerf? is it a buff?)

2024-04-16 09:56 UTC, spyfox321 commented
I would actually buff the MP5SD's suppressor, but I really can't tell how much is -32 loudness modifier, so I'll leave it to people who know what these values mean more.

2024-04-21 15:45 UTC, VissValdyr commented
> I would actually buff the MP5SD's suppressor, but I really can't tell how much is -32 loudness modifier, so I'll leave it to people who know what these values mean more.

The easiest way is to test them out. One step is 5 sound, if I recall, so build it from there. You can debug spawn a friendly NPC and give him a mp5sd, spawn a enemy and save. Let him shoot him and then consider, how far away do you have to be to hear his firing as loud as footsteps. If you consider it too far, make the number higher than -32, for example -40. Save the value and test again until you are happy with the findings.

2025-04-21 15:14 UTC, scarf005 approved these changes
LGTM, needs to hear from other devteam tho

2025-04-21 17:36 UTC, RoyalFox2140 approved these changes

2025-04-21 17:36 UTC, RoyalFox2140 commented
Thats how guns work

2025-04-21 18:16 UTC, merged