feat(balance): replace ~1 pound to 400g and 500g
cataclysmbnteam/Cataclysm-BN pull request #4568
Opened 2024-05-01 14:54 UTC by scarf005

## Purpose of change

- #2505

[metricate](https://en.wikipedia.org/wiki/Metrication) item weights, part 1.

1. many items weighted a pound to depict them as 'somewhat heavy'.
2. it could have been weighed 500g or 400g instead.
3. eradicate trace of customary units from the game.

## Describe the solution

replaced all items weighting 450~500g to 500g, and items weighting 400~450 to 400g.

## Describe alternatives you've considered

making them all 500g to be nice and simple.

## Testing

passed automated tests in local environment.

## Additional context

~98.4% of existing countries have fully adopted metric system (195/192 countries, with the exception of Liberia, Myanmar, and the United States.

2024-05-01 19:07 UTC, chaosvolt commented on data/json/items/chemicals_and_resources.json
> +    "//2": "Previously 10 doses to a gram, so about 400g to the 500g.",
400 grams to the 500 grams? Just delete this comment if it's not going to be actually useful anymore.

2024-05-01 20:41 UTC, RobbieNeko commented on data/json/items/gun/22.json
> -    "weight": "420 g",
This seems a little out of place for this PR, given that a Ruger LCR .22 is legitimately about 420 grams IRL (422.4 to be exact). Considering this PR is stated to be primarily about handling cases where something was set to be about a pound for the sake of just making it "somewhat heavy", I'd hesitate to say this really fits. 420 is already a perfectly round number.

2024-05-01 20:46 UTC, RobbieNeko commented on data/json/items/chemicals_and_resources.json
> -    "weight": "460 g",
460 is actually about the correct weight for 250 ml of sulfuric acid (the calculated weight based on density being 457.5)

2024-05-01 20:47 UTC, RobbieNeko commented
Looks to me like a couple chemicals and firearms got caught in the crossfire when in actuality they've got pretty accurate weights that are still nice rounded numbers regardless

2024-05-10 03:47 UTC, VissValdyr commented
While not in the 500 but rather in the 1500 range, books need some help as well. 
`
{
  "type": "BOOK",
  "name": {
    "str": "Internal Combustion Fundamentals",
    "str_pl": "copies of Internal Combustion Fundamentals"
  },
  "description": "A college-level textbook that details the operation, maintenance, and repair of internal combustion engines.",
  "bashing": 4,
  "material": [
    "paper"
  ],
  "symbol": "?",
  "looks_like": "story_book",
  "color": "blue",
  "flags": [
    "TINDER",
    "FLAMMABLE"
  ],
  "id": "book_icef",
  "copy-from": "base_book",
  "weight": "1587 g",
  "volume": "1500 ml",
  "price": "5950 cent",
  "price_postapoc": "2250 cent",
  "skill": "mechanics",
  "required_level": 4,
  "max_level": 8,
  "intelligence": 6,
  "time": "30 m",
  "fun": -1
}
`

2024-05-13 23:57 UTC, scarf005 commented on data/json/items/gun/22.json
> -    "weight": "420 g",
true, tho i was thinking of #2505

2024-05-14 00:24 UTC, RobbieNeko commented on data/json/items/gun/22.json
> -    "weight": "420 g",
Fair, though I think that nearest 10 grams is already within #2505 's goal. 100% would support rounding the Cobray Streetsweeper to 420g, for example. (And magazines I have no qualms over how you adjust them, those are a lot more variable anyway)

2024-05-14 00:44 UTC, scarf005 commented on data/json/items/gun/22.json
> -    "weight": "420 g",
makes sense. will revert it when i get home.

2024-06-14 19:47 UTC, chaosvolt requested changes

2024-06-14 19:47 UTC, chaosvolt commented on data/json/items/chemicals_and_resources.json
> +    "//2": "Previously 10 doses to a gram, so about 400g to the 500g.",
```suggestion
```

2024-06-14 19:47 UTC, chaosvolt commented on data/json/items/chemicals_and_resources.json
> +    "weight": "500 g",
Probably safe to keep chemical weights unrounded, not super important though.
```suggestion
    "weight": "460 g",
```

2024-06-14 19:47 UTC, chaosvolt commented on data/json/items/chemicals_and_resources.json
> +    "weight": "500 g",
As above
```suggestion
    "weight": "460 g",
```

2024-06-14 19:47 UTC, chaosvolt commented on data/json/items/gun/22.json
> +    "weight": "400 g",
As per discussion between Scarf and Robbie, reversion of gun weights since already at nearest 10 grams
```suggestion
    "weight": "420 g",
```

2024-06-14 19:47 UTC, chaosvolt commented on data/json/items/gun/22.json
> +    "weight": "500 g",
```suggestion
    "weight": "450 g",
```

2024-06-14 19:47 UTC, chaosvolt commented on data/json/items/gun/32.json
> +    "weight": "500 g",
```suggestion
    "weight": "460 g",
```

2024-06-14 19:47 UTC, chaosvolt commented on data/json/items/gun/shot.json
> +    "weight": "400 g",
Went with nearest 10 grams for this one instead since gun, also 420 teehee
```suggestion
    "weight": "420 g",
```

2024-06-14 19:49 UTC, chaosvolt approved these changes
Hopefully is okay to revert just those items mentioned, everything else looks good. :3

2024-06-14 19:50 UTC, chaosvolt approved these changes

2024-06-14 20:49 UTC, merged