feat: grid water wheels
cataclysmbnteam/Cataclysm-BN pull request #4571
Opened 2024-05-01 20:02 UTC by chaosvolt

## Purpose of change

This follows up on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4448 by starting work on a basic implementation of grid water wheels. As with plutonium generators and wind turbines, right now they use the hacky method of "steady consumer that uses negative power drain" and construction restrictions like turbines, but in the future I want to follow up on both these items by implementing some proper checks for terrain conditions to make them work more like solar panels.

WIP because, while I figured that the terrain-checking can be held off on for now, I intend to clean up some potential loopholes that would allow you to finagle a grid water wheel on solid ground, which will require some code adjustments I need to handle when I can check this branch out at home.

## Describe the solution

1. Defined furniture for grid water wheels, both regular and large varieties. Deconstruct and bash yields overall fairly similar to wind turbines for the moment. More notable is their power production is properly consistent with the `epower` rates, close as I can get them. Consumer grid furniture deals in kJ while vehicle power and grid solar panels deal in watts, so they're set to generate 1 kJ in however many seconds would be a reasonable fit for their vehicle version's wattage  (rounded up). Bigger version also is now a bit harder to smack down than normal ones, and both get ballistic data and coverage values.
2. Added construction entries for water wheels and large water wheels. Based mostly off the shallow pit construction entries for wind turbines, though taking a bit longer like vehicle wheels do. Terrain requires the `CURRENT` flag.
3. Updated power production of wind turbines to be consistent with their vehicle versions, likewise matching how grid water wheels and plutonium generators behave. Large version is now a bit harder to bash than the normal one. Large version also gets coverage of 30 and ballistic data (with intercept chance comparable to small water wheels, on the assumption that a wind turbine will be more elevated and thus offer less cover).
4. Also fixed wind turbines being in construction category instead of workshop where all the grid stuff belongs.

TODO
1. Fix exploit allowing you to fill in water currents that have furniture on top of them using a shovel, by changing shovel use action function to cancel out if targeting a tile with furniture on it.
2. Search for any other obvious exploits in item code and the like. I likely won't be able to fix them all (being able to surround wind turbines in solid walls that mechanically would block all wind is basically unavoidable), and they'll become obsolete once we actually have wind and water power as dedicated powergen types (as they'll be able to just check the required conditions and not output their desired wattage if that condition fails), so I wouldn't worry too much over it for now.

## Describe alternatives you've considered

Screaming at C++ and fixing the hackery now instead of later.

## Testing

Checked affected files for syntax and lint errors. Testing to continue once I tackle the C++ stuff.

## Additional context

## Checklist

2024-05-02 16:05 UTC, chaosvolt commented
Okay so I'm testing this now and I...can't just fill flowing shallow water in anyway?
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/49815da3-163a-4317-9d84-8b63988d327e)

I dunno what loophole I managed to miss here if it wasn't that, I could've sworn it let me fill in shallow water previously.

2024-05-14 00:46 UTC, chaosvolt commented
Bonus:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/3e135ba1-47c6-47d0-8fd7-6e48cc39f55d)

2024-05-14 03:59 UTC, Lamandus commented
About the steady consumption of the wind turbine. I choose those high numbers because the game would start to lag on weaker machines. Not sure if the discussion was on GitHub or discord, but I think either olanti or chulu pointed it out.

2024-05-14 04:17 UTC, Lamandus requested changes

2024-05-14 04:17 UTC, Lamandus commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "looks_like": "f_water_mill",
```suggestion
    "looks_like": "f_water_mill_active",
```
It should move in dead people

2024-05-14 09:41 UTC, chaosvolt commented
> About the steady consumption of the wind turbine. I choose those high time numbers because the game would start to lag on weaker machines. Not sure if the discussion was on GitHub or discord, but I think either olanti or chulu pointed it out.
> 
> It was kheir

Ah, weird. I should note that those power numbers were still inaccurate relative to the output of wind turbines, but I could put them back to a slow-but-corrected value if desired I guess?

2024-05-14 09:42 UTC, Lamandus commented
> > About the steady consumption of the wind turbine. I choose those high time numbers because the game would start to lag on weaker machines. Not sure if the discussion was on GitHub or discord, but I think either olanti or chulu pointed it out.
> > It was kheir
> 
> Ah, weird. I should note that those power numbers were still inaccurate relative to the output of vehicle wind turbines, but I could put them back to a slow-but-corrected value if desired I guess?

that would be nice, yes. I think we should check all grid appliances if they follow that rule. They should.

2024-05-14 10:16 UTC, Lamandus requested changes

2024-05-14 10:16 UTC, Lamandus commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "//": "10 watts, all of these below are staggered across 5 minutes to avoid lag.  Todo: conver to not rely on steady_consumer hacks",
```suggestion
    "//": "10 watts, all of these below are staggered across 5 minutes to avoid lag.  Todo: convert to not rely on steady_consumer hacks",
```

2024-06-08 04:25 UTC, scarf005 approved these changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/45e1b0b8-a77f-4b4d-ad53-5ccb6635fa88)

2024-06-08 04:27 UTC, merged