feat(port): Keyboard format updates, tweaks
cataclysmbnteam/Cataclysm-BN pull request #4635
Opened 2024-05-11 23:28 UTC by Kenan2000

Ports these pull requests 

https://github.com/CleverRaven/Cataclysm-DDA/pull/40961,
https://github.com/CleverRaven/Cataclysm-DDA/pull/41866,
https://github.com/CleverRaven/Cataclysm-DDA/pull/47263,
https://github.com/CleverRaven/Cataclysm-DDA/pull/56212, 
https://github.com/CleverRaven/Cataclysm-DDA/pull/46796,
https://github.com/CleverRaven/Cataclysm-DDA/pull/55152,
https://github.com/CleverRaven/Cataclysm-DDA/pull/57266,

This also includes pull requests #4627, #4623 by @chaosvolt for easier mergeability. This depends on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4634 so it cannot be merged until it's merged 

`activity_handlers.cpp` file, line 1257, `crafting_gui.cpp` file line 718 throw errors during compiling which, based on conversation with @Coolthulhu, will be fixed with help of Coolthulhu or other developers or both. `action.cpp` file, line 930 could not be ported because it throws an error so it was added to a comment with explanation 

Coauthors have been linked properly via GitHub Desktop built-in function to do this work hopefully

2024-05-13 12:19 UTC, Coolthulhu requested changes

2024-05-13 12:19 UTC, Coolthulhu commented on src/activity_handlers.cpp
>          int level_cap = std::min<int>( MAX_SKILL, ( corpse->size + ( cbms.size() * 2 + 1 ) ) );
```suggestion
        int level_cap = std::min<int>( MAX_SKILL, ( static_cast<int>( corpse->size ) + ( cbms.size() * 2 + 1 ) ) );
```

2024-05-13 18:55 UTC, Coolthulhu commented on src/activity_handlers.cpp
>          int level_cap = std::min<int>( MAX_SKILL, ( corpse->size + ( cbms.size() * 2 + 1 ) ) );
BTW same change can be applied in other PRs - it seems that all of them failed at this line.

2024-05-30 17:44 UTC, chaosvolt commented
Okay so evidently https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4636 contained the file changes for this PR and the other one so these can be closed? According to Kenan at least.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/189df9b5-b376-4457-b6cf-b463d9e77c0e)

I'm going to hope this is the right descision, if anyone spots anything vital in this re-open and fix merge conflicts then, bleh.

2024-05-30 19:35 UTC, chaosvolt commented
Per request but marking it as WIP afterward.

2024-06-01 23:33 UTC, Kenan2000 commented
Closing this because pull request of @KheirFerrum includes fixed version of this work

2024-06-01 23:33 UTC, closed without merging