make corpses bleed
cataclysmbnteam/Cataclysm-BN pull request #4727
Opened 2024-06-03 15:21 UTC by chrsrns

## Purpose of change

Fixes #4726 when done.

## Describe the solution

Provides a way to 'bleed' corpses, which is seen in DDA.

## Describe alternatives you've considered

Just add the bloods to the entries in `harvest.json` without providing the bleed feature.

## Testing

Nothing yet.

## Additional context

Eventually, this shows up after bleeding a corpse:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/43345572/23d7673e-8162-4e71-a9c4-f2e28317cb1d)

## Checklist

### For the feature itself:
- [ ] Add the `Bleed corpse` entry to the UI.
- [ ] Finish the handler for bleeding corpses.
- [ ] Add the blood entries to `harvest.json`.

### Other checklist:
- [ ] Document the changes in the appropriate location in the `doc/` folder.
- [ ] If documentation for this feature does not exist, please write it or at least note its lack in PR description.
- [ ] New localizable fields need to be added to the `lang/bn_extract_json_strings.sh` script if it does not support them yet.
- [ ] If applicable, add checks on game load that would validate the loaded data.
- [ ] If it modifies format of save files, please add migration from the old format.

2024-06-03 16:28 UTC, chrsrns commented
Okay I don't get why that general build matrix test failed.

2024-06-03 17:37 UTC, chaosvolt commented
Let's see, might be uh...
```
(~[slow] ~[.],starting_items)=> (continued from above) ERROR: The do_turn function ACT_BLEED doesn't correspond to a valid activity_type.
(~[slow] ~[.],starting_items)=> 16:20:47.086 ERROR DEBUGMSG : src/activity_type.cpp:98 [static void activity_type::check_consistency()] The finish_function ACT_BLEED doesn't correspond to a valid activity_type
```

2024-06-03 21:08 UTC, Lamandus commented
what can you do with the blood at the moment?

2024-06-03 21:43 UTC, chrsrns commented
> Let's see, might be uh...
> 
> ```
> (~[slow] ~[.],starting_items)=> (continued from above) ERROR: The do_turn function ACT_BLEED doesn't correspond to a valid activity_type.
> (~[slow] ~[.],starting_items)=> 16:20:47.086 ERROR DEBUGMSG : src/activity_type.cpp:98 [static void activity_type::check_consistency()] The finish_function ACT_BLEED doesn't correspond to a valid activity_type
> ```

Ohh. Found it. Totally missed that

2024-06-03 21:46 UTC, chrsrns commented
> what can you do with the blood at the moment?

not much in the base game IFAIK, but mods like Arcana have some recipes that uses blood, and its a bit tedious to get a lot of those using the blood draw kit

2024-06-03 21:53 UTC, Lamandus commented
> > what can you do with the blood at the moment?
> 
> not much in the base game IFAIK, but mods like Arcana have some recipes that uses blood, and its a bit tedious to get a lot of those using the blood draw kit

that is not good. Since we add these to the main game, there should be use for it


please consider the following:
1. add a recipe to make concentrated tainted blood via cooking. It should lower the volume by 10.
2. make concentrated blood be used in any serum recipe that uses tainted flesh and replace it
3. tainted tornado is using tainted meat, using the blood would fit more.

2024-06-03 21:58 UTC, chrsrns commented
> > > what can you do with the blood at the moment?
> > 
> > 
> > not much in the base game IFAIK, but mods like Arcana have some recipes that uses blood, and its a bit tedious to get a lot of those using the blood draw kit
> 
> that is not good. Since we add these to the main game, there should be use for it
> 
> please consider the following:
> 
>     1. add a recipe to make concentrated tainted blood via cooking. It should lower the volume by 10.
> 
>     2. make concentrated blood be used in any serum recipe that uses tainted flesh and replace it
> 
>     3. tainted tornado is using tainted meat, using the blood would fit more.

that makes sense. will do

2024-06-03 21:59 UTC, chaosvolt commented
Using them for mutagen seems like the most fitting vanilla use. There's also quest usage, I'll likely want to later on confirm that it interacts correctly with the blood draw kit, at minimum not letting you draw blood from bodies that've been bled dry, ideally also using the kit affecting how much blood can be harvested but I can see that being harder to implement...

2024-06-06 18:41 UTC, chaosvolt commented
One thing I realized, it'll prompt the player with liquid handling every time they butcher, won't it?

2024-06-07 01:54 UTC, chrsrns commented
> One thing I realized, it'll prompt the player with liquid handling every time they butcher, won't it?

```
                if( p.is_npc() || action != butcher_type::BLEED ) {
```

I thought this would prevent that for non-bleed actions. I only assumed tho didn't really test it. Will test later.

2024-06-07 16:10 UTC, chaosvolt commented
I feel that's fine. Being able to bleed the corpse as a separate action means the blood's accessible, while it spilling if you do other butchery actions means it won't constantly pester the player about liquid handling, which would make butchering multiple corpses immensely annoying.

2024-06-09 08:47 UTC, Lamandus requested changes
consider removing meat from serum making completely

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat_tainted", 3 ], [ "dry_meat_tainted", 3 ], [ "blood_tainted_concentrate", 9 ] ],
```suggestion
      [ [ "blood_tainted_concentrate", 9 ] ],
```
I would rather see only powder/fluids in making serums.

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat", 3 ], [ "animal_blood_concentrate", 9 ] ],
```suggestion
      [ [ "animal_blood_concentrate", 9 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat", 3 ], [ "animal_blood_concentrate", 9 ] ],
```suggestion
      [ [ "animal_blood_concentrate", 9 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat", 1 ], [ "animal_blood_concentrate", 3 ] ],
```suggestion
      [ [ "animal_blood_concentrate", 3 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat", 3 ], [ "animal_blood_concentrate", 9 ] ],
```suggestion
      [ [ "animal_blood_concentrate", 9 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat", 3 ], [ "animal_blood_concentrate", 9 ] ],
```suggestion
      [ [ "animal_blood_concentrate", 9 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat", 3 ], [ "animal_blood_concentrate", 9 ] ],
```suggestion
      [ [ "animal_blood_concentrate", 9 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [ [ "meat", 3 ], [ "animal_blood_concentrate", 9 ] ],
```suggestion
      [ [ "animal_blood_concentrate", 9 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +        [ "blood_tainted_concentrate", 9 ],
```suggestion
       [ [ "can_chowder", 1 ], [ "can_clams", 1 ], [ "blood_tainted_concentrate", 9 ] ],
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      [
```suggestion
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +        [ "meat_tainted", 3 ],
```suggestion
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +        [ "dry_meat_tainted", 3 ],
```suggestion
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +      ],
```suggestion
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +        [ "can_clams", 1 ]
```suggestion
```

2024-06-09 08:47 UTC, Lamandus commented on data/json/recipes/chem/mutagen.json
> +        [ "can_chowder", 1 ],
```suggestion
```

2024-06-09 09:12 UTC, chrsrns commented
I am pondering on recipe would make concentrated blood. The idea is that this just removes most of the water from it, so just heating it up and stirring continuously to prevent most of the clotting makes sense to me. I think this would just translate in game to needing a boiling 1 tool and heat. A part of me thinks that this would need an anticoagulant of sorts to make sense, but that is just a feeling, as I can't find any concrete basis online on how to concentrate blood.

Just removing concentrated blood and just using the blood itself is an option, but the reduced volume would be nice. Unnecessary at that point of the game, but nice.

My search history for this is wild.

2024-06-09 09:25 UTC, Lamandus commented
> I am pondering on the recipe that would make concentrated blood. The idea is that this just removes most of the water from it, so just heating it up and stirring continuously to prevent most of the clotting makes sense to me. I think this would just translate in game to needing a boiling 1 tool and heat. A part of me thinks that this would need an anticoagulant of sorts to make sense, but that is just a feeling, as I can't find any concrete basis online on how to concentrate blood.
> 
> Just removing concentrated blood and just using the blood itself is an option, but the reduced volume would be nice. Unnecessary at that point of the game, but nice.
> 
> My search history for this is wild.

while not wholly correct, Aspirin (ASS) is an antiplatelet medication.
Alternative would be the use of a rag to get the chunks out (I do it usually when making blood-sausage)

speaking of which, can you make a "Blutwurst" recipe?

https://www.chefkoch.de/rezepte/2324751370527261/Die-Herstellung-von-Blutwurst.html

https://www-chefkoch-de.translate.goog/rezepte/2324751370527261/Die-Herstellung-von-Blutwurst.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp (translated)

Blood sausage is very popular in Germany, so it would be a good use for animal blood.

Sausage casting, concentrated animal blood, chunks of meat and some salt/spices are what we use in Germany.

You can either add a new recipe, or put the concentrated blood into the wasteland sausage recipe. Your call.

2024-06-09 12:16 UTC, Relgar commented
This is an exciting pull request that has many potential applications.

There are a fair few pieces of lab equipment that would benefit being given a 'use' or tool quality that works with bloods or liquids. They could be used to extract specific things from the many lifeforms we have that bleed: animals, humans, zombies, mi-go, nether creatures, or mutants. It could also analyse if specific useful compounds are present in blood. In turn, extracting these specific minerals or compounds from the above list can lead to applications such as: 

- enhanced healing items (IV bags FINALLY) 
- experimental mutagen serums instead of requiring tainted meat as mentioned
- maybe solve the zombie bite problem with a vaccine
- powering mi-go weapons with fuel extracted from mi-go blood, which would play nicely with the idea of biological weapons
- cooking / brewing / formulating many other foods / drinks /drugs with these

2024-06-09 13:48 UTC, chrsrns commented
> You can either add a new recipe, or put the concentrated blood into the wasteland sausage recipe. Your call.

I went with creating a blutwurst item and recipe. Since it is a famous dish, it felt weird for it to be alike to the wateland sausage with negative morale.

2024-06-09 13:50 UTC, chrsrns commented
> ## Purpose of change
> 
> Fixes #4726 when done.
> ## Describe the solution
> 
> Provides a way to 'bleed' corpses, which is seen in DDA.
> ## Describe alternatives you've considered
> 
> Just add the bloods to the entries in `harvest.json` without providing the bleed feature.
> ## Testing
> 
> Nothing yet.
> ## Additional context
> 
> Eventually, this shows up after bleeding a corpse: ![image](https://private-user-images.githubusercontent.com/43345572/336130093-23d7673e-8162-4e71-a9c4-f2e28317cb1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDExODgsIm5iZiI6MTcxNzk0MDg4OCwicGF0aCI6Ii80MzM0NTU3Mi8zMzYxMzAwOTMtMjNkNzY3M2UtODE2Mi00ZTcxLWE5YzQtZjJlMjgzMTdjYjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEzNDgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMWRjZmZhYWRlNWFhMTkxMDk5NDFiNzcyNmNhMWMzZDFlZWFmOWM4ZDNlNDE3NDhkOWE1ZjgzOGI3MmE5MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i8KOogftzEBBqYiHySgt06kJXR9jokoz5vNxwNLrMLI)
> ## Checklist
> ### For the feature itself:
> 
>     * [x]  Add the `Bleed corpse` entry to the UI.
> 
>     * [x]  Finish the handler for bleeding corpses.
> 
>     * [x]  Add the blood entries to `harvest.json`.
> 
>     * [ ]  Add recipes that uses blood as an alternative ingredient.
> 
>     * [ ]  Make sure that the blood draw kit can no longer draw blood from bled corpses.
> 
> 
> ### Other checklist:
> 
>     * [ ]  Document the changes in the appropriate location in the `doc/` folder.
> 
>     * [ ]  If documentation for this feature does not exist, please write it or at least note its lack in PR description.
> 
>     * [ ]  New localizable fields need to be added to the `lang/bn_extract_json_strings.sh` script if it does not support them yet.


    * [x]  Add recipes that uses blood as an alternative ingredient.

    * [x]  Make sure that the blood draw kit can no longer draw blood from bled corpses.

2024-06-09 13:51 UTC, scarf005 commented
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/9c1975f2-73fb-403f-ab7d-6d8399eca128)

while related to PR, it seems like those new recipes could've been a separate PR (so it's easier to review), could they get extracted out?

2024-06-09 13:53 UTC, chrsrns commented
> while related to PR, it seems like those new recipes could've been a separate PR (so it's easier to review), could they get extracted out?

That's fair. Will do that now.

2024-06-09 20:04 UTC, chaosvolt commented
Fixed a smol case of a harvest entry having blood defined twice and added human blood to some human harvest entries missing it. Looks good at first glance but not currently home so won't be able to compile and playtest just yet.

I'd be very tempted to ponder reducing the mass ratios of blood a lil but it depends on how much blood you can get out of a body, plus with all the things we've foisted on you already I figure it's something entirely fine to leave as something I can tinker with myself in a followup PR.

2024-06-09 23:04 UTC, chrsrns commented
> plus with all the things we've foisted on you already I figure it's something entirely fine to leave as something I can tinker with myself in a followup PR.

I'm very new to the codebase so that's totally fine

2024-06-10 03:55 UTC, chaosvolt approved these changes
1. Compiled and load-tested.
2. Played around with bleeding and butchering of zeds and NPCs to test behavior.

Fixed some oddities I encountered during testing:
1. Fixed the way blood is zeroed out by flag checks so that it doesn't require all of the flags, thus fixing  it still dropping blood on dissection and the like.
2. Set the bleed action to grab specifically whatever is defined as a blood harvest entry instead of specifically searching for liquids in the harvest.
3. Removed the extra effect of a failed field dressing on bleeding since field dressing in general already automatically zeroes out the blood yield in an earier check.
4. Tweaked reduction of corpse weight to lose 10% of weight instead of 20% since havest entries all use 10% as the mass ratio.
5. Fixed incorrect message when trying to use blood draw kit on an already-bled corpse.
6. Edited comments in a few spots.

I found a bug where it's possible to dupe organs, that plus it always saying you fail to obtain yields you already harvested in an earlier action are two issues that predate this PR and I think I might fuck with it as a direct followup of this.

2024-06-10 05:47 UTC, merged