feat (port): corpses decay into items, actually implement in JSON
cataclysmbnteam/Cataclysm-BN pull request #4751
Opened 2024-06-07 01:10 UTC by chaosvolt

## Purpose of change

This aims to port over a feature recently added to DDA that'd been on my wishlist for a while, allowing corpses to decay into bones when left alone. As with regen modifiers, actual JSON implementation I'll have to do myself.

WIP because while code all seems to work, I'm not done adding the feature in JSON.

## Describe the solution

C++ changes:
1. In item.cpp, added handling of decaying corpses to `item::process_internal`, and definition of `item::get_corpse_mon` to item.cpp and item.h. Also set it to not do this with corpses that're about to zombify into something, so it doesn't break that.
2. In map.cpp and map.h, ported over `map::handle_decayed_corpse` from the source PR, converted to behave with the item identity behavior and to use tripoint instead of faffing about with submap stuff.
3. In monstergenerator.cpp, added JSON definition of `decay` to monster info.
4. In mtype.cpp, defined `decay_human` as the default harvest result of decay if not specified. DDA version uses null, where this defines an actual default entry for all those monsterless human corpses since we're actually starting to implement stuff.

JSON changes:
1. Added harvest entries for decaying corpses. This would be the part where it stops becoming a port and starts becoming my work. Started with a default `decay_human` entry for human corpses, then began adding basic bone drops for animals, chitin, etc with variations as needed.
2. Implemented decay entries for all vanilla monsters. Most use `decay_animal_standard`, for anything where the main drop is just bones and sinew, or `decay_zombie_standard` for tainted bones.
3. Misc: Standardized and sanity-checked some of the mass ratios in harvest entries.
4. Misc: Fixed some bugs lacking sinew.
5. Misc: fixed several oddball cases of mutant human harvest entries not using human bones.
6. Misc: Fixed acid ant queens and fungal bosses having some weird harvestdefs.

Documentation changes:
1. Added documentation of both harvest entries and decay entries to monsters.md, our formatting is different from DDA's monster docs so had to write up our own version.

## Describe alternatives you've considered

1. Waiting to see if a JSON implementation will come later today or if it'll be like regen modifiers where it took them years to use it for anything in-repo.
2. Trying to hijack `butchery_drops_harvest` so we never even have to use this function. This would entail defining a fake npc to do the butchering for us however so it'd be a lot of hassle, plus we'd need to hijack `extract_or_wreck_cbms` for good measure if we want it to also fix bionics.

## Testing

1. Compiled and load-tested.
2. Spawned in a human corpse, turned on debug mutations to wait for it to rot.
3. Observed a message showing it rotted away, saw there were indeed bones in it.
4. Spawned in and full-butchered a default human corpse, confirmed the amount of bones in the rotten corpse was properly lower than butchering a human.
5. Spawned in and killed a feral human, let it decay a few days with revives turn on, confirmed it still turns into a zombie and gets back up.
6. Spawned in some assorted animals, confirmed they rot into bones or chitin in the case of ants, as expected.

## Additional context

PR source: `Corpses can decay into bones, etc.`, by @RenechCDDA: https://github.com/CleverRaven/Cataclysm-DDA/pull/74328

In the future I'd also like to have it attempt to dump CBMs and other items generated on a corpse when it rots away, likely at the minimum of 10% chance so the player is still encouraged to harvest them themselves, but that can be a separate PR.

## Checklist

2024-06-07 03:14 UTC, scarf005 requested changes
this adds new methods in `item` and `map` class directly, which we should generally avoid without good reason (check #3200 for details). not sure for items, but for map it seems like the method added could have been a separate free function. could we extract the method into regular function here?

2024-06-07 03:21 UTC, chaosvolt commented
Maybe? Not sure where best to put it.

Also, discovered a critical issue with this: bodies don't actually drop their harvest results if they rotted away while out of the reality bubble. Also covers bodies that spawn in map extras and the like when visited long after zero day.

2024-06-07 03:40 UTC, chaosvolt commented
Tested DDA to see if I could replicate it, I can't even actually get bodies to properly recognize that it's been a year so they should've already rotted like I can in BN, and also managed to get it to error about not recognizing the harvest entry for the decay value I gave a zed for testing, so DDA's version of it is for now a complete write-off.

Notifying @renechcdda since this is a DDA error with their version of the feature:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/e182ea45-a095-4243-8ccf-fb007d99574c)

2024-06-07 06:28 UTC, chaosvolt commented
So, root problem here in particular here is corpse removal off-map appears to be handled by `map::remove_rotten_items`: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/src/map.cpp#L7264 while `item::process_internal` seems to mainly be used for in-map spawns.

Problem is, dumping a call to `handle_decayed_corpse` into `map::remove_rotten_items` seems to explode, specifically because it really does not like the idea of calling `add_item_or_charges` at a tripoint that's off in parts unknown. I'm not sure if this is the reason why the source PR retained its weird hack of "get abs then localize later" (doubt, as no call to the function was injected into any apparent counterpart to `map::remove_rotten_items` in the PR) or if the solution is something else.

2024-06-08 18:28 UTC, chaosvolt commented
Two problems discovered:
1. Off-map decay is beefing up and actually spawning its item twice.
2. Something about copper wire specify seems to be spawning whole stacks instead of charges.

Off-map decay of a cyborg, with a not-yet-commited addition that lets CBMs spawn:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/023c774c-e0ad-4e9b-b425-741966dd1c33)

On-map decay, working correctly except for big stacks of wire:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/a3550a09-3a45-47d5-afca-6acb01f0e577)

2024-06-09 15:45 UTC, joveeater submitted a review, later dismissed
This looks good to me. Adding items into a temporary vector and then handling them at the end to avoid memory problems is fine and it's something we do in other places.

2024-06-09 17:34 UTC, chaosvolt commented
Aight, retested. Everything still seems to be good except for the copper wiring thing:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/641ccae5-8513-4619-909e-3275d8b21f74)

This only affects pretty much a single monster currently, and I plan to defer the question of harvesting bionics this way for a later PR, so I'll go ahead and mark as ready and just see if I can get time to fix this weird case.

2024-06-10 00:26 UTC, scarf005 submitted a review, later dismissed

2024-06-10 06:20 UTC, chaosvolt commented
Apologies to Scarf for also dismissing the appoval, but I figured out what seems to be a viable fix for the "copper wires from cyborgs spawn way more than intended on decay due to being multiplied by default stack" issue:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/6bf45190-f8bb-41bf-ae8f-5b7ca4c0b72d)

2024-06-10 18:30 UTC, chaosvolt commented
And at request of @VissValdyr during discussion in the BN server, I went ahead and added the "decay can potentially drop corpse components" idea in this PR instead of in a follow-up, since is a fairly basic addition. Uses the same odds and general behavior as the bare-minimum chance of obtaining corpse components when dissecting.

Lowering it to something like 5% instead of 10% is a potential option if we feel it more balanced to make "at least try even though you know the success rate is at rock bottom currently" still worth attempting.

2024-06-14 01:51 UTC, scarf005 approved these changes

2024-06-14 03:44 UTC, merged