feat(content): blutwurst recipe
cataclysmbnteam/Cataclysm-BN pull request #4761
Opened 2024-06-09 14:21 UTC by chrsrns

## Purpose of change

If #4727 gets merged, this will add a blood sausage comestible to incentivize bleeding of corpses.

## Describe the solution

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2024-06-09 14:28 UTC, Lamandus requested changes

2024-06-09 14:28 UTC, Lamandus commented on data/json/items/comestibles/meat_dishes.json
> +    "copy-from": "sausage_raw",
to get "better results" try to copy from sausage instead.

```suggestion
    "copy-from": "sausage",
```

2024-06-09 14:28 UTC, Lamandus commented on data/json/recipes/food/meat.json
> +    "autolearn": true,
```suggestion
    "autolearn": true,
    "book_learn": [ [ "family_cookbook", 2 ], [ "scots_cookbook", 2 ] ],
```

2024-06-09 14:28 UTC, Lamandus commented on data/json/recipes/food/meat.json
> +    "autolearn": true,
```suggestion
    "autolearn": true,
    "book_learn": [ [ "family_cookbook", 2 ], [ "scots_cookbook", 2 ] ],
```

2024-06-09 14:28 UTC, Lamandus commented on data/json/recipes/food/meat.json
> +    "autolearn": true,
```suggestion
    "autolearn": true,
    "book_learn": [ [ "family_cookbook", 2 ], [ "scots_cookbook", 2 ] ],
```

2024-06-09 14:28 UTC, Lamandus commented on data/json/recipes/food/meat.json
> +    "autolearn": true,
```suggestion
    "autolearn": true,
    "book_learn": [ [ "family_cookbook", 2 ], [ "scots_cookbook", 2 ] ],
```

2024-06-09 14:28 UTC, Lamandus commented on data/json/recipes/food/meat.json
> +    "autolearn": true,
```suggestion
    "autolearn": true,
    "book_learn": [ [ "family_cookbook", 2 ], [ "scots_cookbook", 2 ] ],
```

2024-06-09 14:28 UTC, Lamandus commented on data/json/recipes/food/meat.json
> +    "charges": 1,
```suggestion
```

2024-06-09 14:30 UTC, Lamandus commented
consider adding spawns into the game for those sausages.

if you use notepad++, check the folder "itemgroups" and search for the item "sausage" (and their variants). Add the blutwurst to it with around 1/4 of the chance of spawning it.

2024-06-09 14:36 UTC, Lamandus commented
https://en.wikipedia.org/wiki/Schwarzsauer

https://en.wikipedia.org/wiki/Blood_soup

are also things to consider

2024-06-09 15:18 UTC, Lamandus commented
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4762
as a follow up.

2024-06-10 08:11 UTC, Lamandus commented
please update this branch from main to rerun the tests and put it "away" from draft.

2024-06-10 08:39 UTC, chaosvolt commented
Went ahead and updated it from upstream for you along with fixing a spacing thing it complained about, so should be good to mark as ready.

2024-06-10 16:19 UTC, chaosvolt approved these changes

2024-06-10 16:19 UTC, merged