feat(content): 3D printers
cataclysmbnteam/Cataclysm-BN pull request #4801
Opened 2024-06-15 03:12 UTC by yay855

## Purpose of change

3D printers are a thing IRL, and are capable of making custom items out of plastic, carbon fiber, and even metal, yet the closest thing we have ingame is the nanofabricator.

## Describe the solution

3D printers are now added to the game, as well as various carbon fiber armors and weapons.

## Describe alternatives you've considered

## Testing

## Additional context

## Checklist

2024-06-15 04:05 UTC, kevingranade commented
Need a source for the carbon fiber 3d printers, that's news to me.

2024-06-15 04:24 UTC, yay855 commented
> Need a source for the carbon fiber 3d printers, that's news to me.

https://www.3dsourced.com/3d-printer-materials/carbon-fiber-3d-printing-guide/

It's a thing, but it has some flaws- namely, IRL 3D printed carbon fiber has to be mixed with other materials to work, a problem that will likely be solved in the near future. It's also rough on the printer, and cheaper 3D printers will outright break if you try it.

2024-06-15 06:20 UTC, KheirFerrum commented
From the gameplay side, I'd want more information on where exactly you think this will fall in progression, sidegrades to proper plate armour, upgrades, step down? Then how you intend to balance it for that niche.

In terms of real life I suppose the gloves and to some small extent the boots are odd to me since both are likely to require articulation instead of just printing it as a single piece.

2024-06-15 14:03 UTC, yay855 commented
> From the gameplay side, I'd want more information on where exactly you think this will fall in progression, sidegrades to proper plate armour, upgrades, step down? Then how you intend to balance it for that niche.
> 
> In terms of real life I suppose the gloves and to some small extent the boots are odd to me since both are likely to require articulation instead of just printing it as a single piece.

The idea is that it will be a firmly midgame type of thing akin to arc welders, allowing you to make midgame level armor and weapons. You will be able to sometimes find the 3D printers or their products, and crafting the former requires highish electronics skill and the right recipe book. Properly tough carbon fiber is genuinely equivalent to kevlar in most regards, though somewhat more brittle and less flexible, while carbon fiber weapons could in theory be extremely lightweight in exchange for losing sharpness faster. And because it can also be used to print synthetic rubbers like neoprene, you could use it to make rubber tires, too.

As for the gloves and boots, those I'm going to say have multiple overlapping carbon fiber plates attached to a synthetic fabric glove or sock.

2024-06-15 15:50 UTC, scarf005 requested changes

2024-06-15 15:50 UTC, scarf005 commented on data/json/items/armor/shields.json
> +    "proportional": { "weight": 0.6, "encumbrance": 0.7, "price": 2, "price_postapoc": 2 }
it looks like you've both added `weight` and `proportional.weight`. an error is being made because the game cannot determine which one to use. removing `weight` should fix the issue.

2024-06-15 15:51 UTC, yay855 commented on data/json/items/armor/shields.json
> +    "proportional": { "weight": 0.6, "encumbrance": 0.7, "price": 2, "price_postapoc": 2 }
Whoops, my bad. Thanks for that.

2024-06-15 15:51 UTC, yay855 commented
I still need to do loot tables and balance checking, but I think this is mostly done!

2024-06-15 16:23 UTC, chaosvolt commented on data/json/items/melee/unarmed_weapons.json
> +    "name": { "str": "carbon fiber jamadhar" },
```suggestion
    "name": { "str": "carbon fiber katar" },
```

2024-06-15 16:24 UTC, yay855 commented on data/json/items/melee/unarmed_weapons.json
> +    "name": { "str": "carbon fiber jamadhar" },
Thanks for catching that!

2024-06-15 16:24 UTC, chaosvolt commented on data/json/items/ranged/crossbows.json
> +    "type": "GENERIC",
```suggestion
    "type": "GUN",
```

2024-06-15 16:25 UTC, chaosvolt commented on data/json/items/tool/science.json
> +    "description": "Although it's not nearly as fancy as the experimental nanofabricators, this civilian-grade 3D printer can produce almost any item out of plastic, polymer, or carbon fiber...  so l
```suggestion
    "description": "Although it's not nearly as fancy as the experimental nanofabricators, this civilian-grade 3D printer can produce almost any item out of plastic, polymer, or carbon fiber…  so long as you can program it.",
```

2024-06-15 16:40 UTC, chaosvolt commented
I do wonder if it'd suit balance better to have the crafting material for carbon fiber items require a specific item and have it be made using a recipe that roughly mimics the general idea of making carbon fiber filaments from a precursor, while still allowing you to repair them with plastic chunks. But I'm not sure what'd be the best fit for that (possibly a CVD machine or nanofab?).

On the other hand, this could be instead flavored away as something the advanced 3D printer can already do, and thus rig it so that a regular 3D printer can make a variety of plastic items and repair carbon fiber items, while either the carbon fiber ones either require an advanced 3D printer to make, or simply require them to make a specific material component that either printer can then put together (with possibly some other existing superscience machine being retweaked into being usable as an alternative tool for making them).

If we do go the route of restricting carbon fiber items in that way, some of the basic items here like the pistol could be reflavored as more conventional 3D prints, since some designs for things more complicated than the Liberator have cropped up since then (though making it relatively more likely to suffer damage than a conventional firearm would still be reasonable balance-wise).

2024-06-15 16:44 UTC, yay855 commented
> I do wonder if it'd suit balance better to have the crafting material for carbon fiber items require a specific item and have it be made using a recipe that roughly mimics the general idea of making carbon fiber filaments from a precursor, while still allowing you to repair them with plastic chunks. But I'm not sure what'd be the best fit for that (possibly a CVD machine or nanofab?).
> 
> On the other hand, this could be instead flavored away as something the advanced 3D printer can already do, and thus rig it so that a regular 3D printer can make a variety of plastic items and repair carbon fiber items, while either the carbon fiber ones either require an advanced 3D printer to make, or simply require them to make a specific material component that either printer can then put together (with possibly some other existing superscience machine being retweaked into being usable as an alternative tool for making them).
> 
> If we do go the route of restricting carbon fiber items in that way, some of the basic items here like the pistol could be reflavored as more conventional 3D prints, since some designs for things more complicated than the Liberator have cropped up since then (though making it relatively more likely to suffer damage than a conventional firearm would still be reasonable balance-wise).

That's just it though, IRL carbon fiber is made from polymers. Usually organic ones since they have carbon in them, but you _can_ make it from petroleum. The manufacturing process isn't super intensive, and a near-future 3D printer very well could convert regular plastic into carbon fiber, albeit inefficiently.

2024-06-15 16:53 UTC, chaosvolt commented
Seems fair yeah. Definitely reasonable to have the advanced model be all-in-one and able to make filaments directly from generic plastic precursor, I was mostly just wondering if "can make its own carbon fiber" would be worth bothering with as a reason to distinguish the regular and advanced printers. Right now both seem to be identical for the purpose of recipes, and only really differ in their value as repair tools.

2024-06-15 17:10 UTC, yay855 commented
> Seems fair yeah. Definitely reasonable to have the advanced model be all-in-one and able to make filaments directly from generic plastic precursor, I was mostly just wondering if "can make its own carbon fiber" would be worth bothering with as a reason to distinguish the regular and advanced printers. Right now both seem to be identical for the purpose of recipes, and only really differ in their value as repair tools.

The advanced one is something I'm planning on bumping up in a later PR, making it so that it can function like a 3D printer, welder, etc; basically it can 3D print metals to make complex things quickly. But your idea of making it able to craft carbon fiber isn't a bad idea.

2024-06-15 19:58 UTC, chaosvolt reviewed
This should fix the syntax error, one sec and I'll apply them as a batch.

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/ammo/arrows.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/ammo/arrows.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/armor/arms.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/armor/feet.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/armor/hands.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/armor/head.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/armor/legs.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/armor/other.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/armor/other.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/other/containers.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/other/containers.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/other/containers.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/cutting.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/cutting.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/magazines.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/magazines.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/magazines.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/piercing.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/piercing.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/piercing.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/ranged.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/ranged.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 19:58 UTC, chaosvolt commented on data/json/recipes/weapon/ranged.json
> +    "tools": [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ],
```suggestion
    "tools": [ [ [ "3d_printer_basic", 100 ], [ "3d_printer_advanced", 100 ] ] ],
```

2024-06-15 20:24 UTC, yay855 commented
> This should fix the syntax error, one sec and I'll apply them as a batch.

Thanks for handling that, I think I burnt myself out a little putting all this out this quickly.

2024-06-21 18:56 UTC, chaosvolt reviewed
Okay, passes all tests so that bit's good. So that leaves the main questions:
1. Should the advanced 3D printer be placeable as grid furniture like the basic model currently is? If so, will need a construction entry too.
2. Currently looks like the advanced model doesn't spawn anywhere either. I assume this can if strictly needed be saved for a later PR however, if so that also renders point one a non-issue for now.
3. A minor improvement that could make the advanced model more distinct from the basic model, in the same vein as firearm repair kits vs gunsmith kits, could be changing it so that the advanced printer uses less charges than the basic one when used in recipes. That said, that's a lot of recipes to update, which leads to the next major point...
4. Right now it's all a fixed amount of printer use per recipe no matter the component cost. Before actually making them vary, it might be a good idea to convert the printer tool to a crafting requirement to streamline things a bit. That way implementing point three would be as simple as changing a single number (plus or minus the fact you'd already have to change everything to implement this one, hecc).
5. Feel free to make note of any other plastic items we want to make printable. That said, this leads to secondary questions.

Secondary thoughts to ponder on:
1. I assume the main benefit of 3D-printing basic plastic items over making them using existing methods like taping plastic containers or plastic molding is time saved? Since we have things like the food processor recipes for flour I suppose that's fine enough, just wonder what differences would be relevant to tinker with.
2. Do we want to bother with added lower-quality plastic guns like the Liberator, or just stick to the two advanced carbon fiber guns?
3. I'll need to eyeball what the carbon fiber weapons and armor look like balance-wise. Given how involved it can be to make plate armor yourself, this still gives the impression of being a sidegrade rather than an upgrade in terms of effort, so them being comparable to their medieval equivalents or equivalent-yet-different-in-some-ways is probably fine.
4. As noted, still unsure what else could be done to make the advanced model noticeably different over the basic one. Ideally I'd be tempted to overhaul carbon fiber such that it's a very useful material that either printer can work with but only the advanced printer can produce, and have it be a material that spawns in relevant industrial or science locations, but that's a lot to foist on a PR author and it'd require fucking about with the carbon fiber items a lot more to ensure they'd actually be worth bothering with if they were made that rare, plus it'd require a lot more plastic recipes to make the basic model become worth it if carbon fiber recipes became more restrictive.

Regarding the primary points, if you'd rather I tackle implementing them instead feel free to let me know and I can yeet out changes to the branch to convert the tool use to a crafting requirement or whatever other major overhauls are needed, instead of dropping the task on your lap to deal with.

2024-06-21 20:36 UTC, yay855 commented
Honestly I think the advanced 3D printer was premature of me, I didn't end up using it at all. It's just free-floating in the code. The charges difference is a good idea, and you're right that the recipes need to have their charges tinkered with. The plastic stuff is a sidegrade to plastic molds, similar to the food processor, yeah; it's faster and convenient, that's all.

Lower-quality plastic guns would be a fun idea, but I feel like that would require us to make carbon fiber harder to get, which I'm fine with, but I'm not ready to work on today. Carbon fiber armor and weapons are lighter than their metal counterparts, so the weapons swing a lot faster, and the armor is also much stronger; it's roughly twice as protective as regular medieval plate armor, actually.

2024-06-24 05:49 UTC, scarf005 approved these changes

2024-06-24 07:52 UTC, scarf005 approved these changes

2024-06-25 09:50 UTC, chaosvolt commented
Guess we can tinker with what to do regarding advanced printers later on, already had a few smol ideas come to mind.

2024-06-25 09:50 UTC, merged