[WIP] New helicopter based scenario and fix for inability to set helicopter as starting vehicle
cataclysmbnteam/Cataclysm-BN pull request #481
Opened 2021-04-18 20:50 UTC by Firestorm01X2

New helicopter based scenario where player starts with helicopter avalible.
"You manage to get to the chopper right when Cataclysm begins.  But are there safe places to land left in this world now?"
In this scenario player starts in wilderness but with military helicopter available. For now there are military helicopter profession with UH-60 as starting vehicle.

#### Summary

SUMMARY: Content "New helicopter based scenario"
New wilderness scenario where player starts with helicopter available right from the start.

#### Purpose of change
New scenario designed to provide player helicopter experience and provide new source of feedback on helicopters.

#### Describe the solution
1) Fix bug that does not allow to properly set helicopter as starting vehicle
2) Add scenario with helicopter as starting vehicle.

#### Describe alternatives you've considered

#### Testing 
1) Start new "Flight of the Valkyries" scenario
2) Check if helicopter is avalible.

#### Additional context
Helicpters sometime can spawn somewhat far from player. But it is how starting vehicle spawn now.

2021-04-18 21:16 UTC, Firestorm01X2 commented
Note: spawning Apache producing error.

2021-04-19 06:45 UTC, Coolthulhu commented on data/json/professions.json
> +    "description": "You manage to make it to your UH-60. Your co-pilot didn't.",
Spaces after period

2021-04-20 09:55 UTC, Coolthulhu commented on src/game.cpp
> +        } else if( veh.max_ground_velocity() > 0 ) {
Not sure if this check is needed. What does it protect from?
Floating vehicles should be restricted to water, road-only vehicles to road, amphibious vehicles can go on water or land (possibly only roads).
Since none of the vehicles in the repo are road-only, no need to implement that restriction.

This boils down to: if it's a boat, it needs water. Otherwise, no need to check whether it's a car, helicopter or shopping cart.

2021-04-20 09:57 UTC, Coolthulhu requested changes

2021-04-20 09:57 UTC, Coolthulhu commented on src/vehicle.h
> +        bool is_helicopter() const;
Once the check for vehicle being drivable is removed, this won't be needed.

2021-04-20 09:57 UTC, Coolthulhu commented on data/json/scenarios.json
> +    "description": "You manage to get to the chopper right when Cataclysm begins.  But are there safe places to land left in this world now?",
"You `managed`"

2021-04-20 09:57 UTC, Coolthulhu commented on data/json/professions.json
> +    "description": "You manage to make it to your UH-60.  Your co-pilot didn't.",
`managed`

2021-04-21 16:42 UTC, Firestorm01X2 commented on src/game.cpp
> +        } else if( veh.max_ground_velocity() > 0 ) {
Done. Just one note. I've set priority to find location to vehicle spawn starting vehicle to fields instead of roads, especially for wilderness starts.. Usually it should provide much closer position for starting vehicle since fields are everywhere but rorads are not.
Still potentially it could move vehicle further away with city starting location, but it usually should not be that far anyway- since, again, fields are everywhere.

2021-04-21 16:42 UTC, Firestorm01X2 commented
Done. Just one note. I've set priority to find location to vehicle spawn starting vehicle to fields instead of roads, especially for wilderness starts.. Usually it should provide much closer position for starting vehicle since fields are everywhere but rorads are not.
Still potentially it could move vehicle further away with city starting location, but it usually should not be that far anyway- since, again, fields are everywhere.

2021-04-21 17:40 UTC, Coolthulhu approved these changes

2021-04-21 17:40 UTC, Coolthulhu commented on data/json/scenarios.json
> +    "description": "You managed to get to the chopper right when Cataclysm begins.  But are there safe places to land left in this world now?",
"right when Cataclysm begins" sounds weird. Try to run it through the translator from English and back to English - when it doesn't break the meaning, it often makes it sound more correct.

2021-04-21 17:40 UTC, Coolthulhu commented on data/json/professions.json
> +    "description": "You managed to make it to your UH-60.  Your co-pilot didn't.",
"managed to make it to" is a bit odd.

2021-04-21 17:52 UTC, Firestorm01X2 commented on data/json/scenarios.json
> +    "description": "You managed to get to the chopper right when Cataclysm begins.  But are there safe places to land left in this world now?",
Reworded

2021-04-21 17:52 UTC, Firestorm01X2 commented on data/json/professions.json
> +    "description": "You managed to make it to your UH-60.  Your co-pilot didn't.",
Reworded

2021-04-21 17:58 UTC, Coolthulhu approved these changes

2021-04-21 18:35 UTC, Coolthulhu commented
Holy shit that chopper drains its fuel faster than if all its tanks were wrecked. It's less of a vehicle and more of an immobile fuel tanker with two good engines to scavenge. It spawns with tons of fuel.

I guess it's still good to go, but it's a gimmick start for now.

2021-04-21 18:35 UTC, merged

2021-04-24 13:39 UTC, Firestorm01X2 commented
> Holy shit that chopper drains its fuel faster than if all its tanks were wrecked

Yep. I've heard about it. Should be fixed.