feat(conntent): Adds mushroom farming via racks and logs, obsoletes spores
cataclysmbnteam/Cataclysm-BN pull request #4927
Opened 2024-07-03 12:11 UTC by Ali-Anomma

## Checklist

### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

- [ ] This PR ports commits from DDA or other cataclysm forks.
  - [ ] I have attributed original authors in the commit messages adding [`Co-Authored-By`](https://docs.github.com/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in the commit message.
  - [ ] I have linked the URL of original PR(s) in the description.
- [ ] This is a C++ PR that modifies JSON loading or behavior.
  - [ ] I have documented the changes in the appropriate location in the `doc/` folder.
  - [ ] If documentation for this feature does not exist, please write it or at least note its lack in PR description.
  - [ ] New localizable fields need to be added to the `lang/bn_extract_json_strings.sh` script if it does not support them yet.
  - [ ] If applicable, add checks on game load that would validate the loaded data.
  - [ ] If it modifies format of save files, please add migration from the old format.
- [ ] This is a PR that modifies build process or code organization.
  - [ ] Please document the changes in the appropriate location in the `doc/` folder.
  - [ ] If documentation for this feature or process does not exist, please write it.
  - [ ] If the change alters versions of software required to build or work with the game, please document it.

- [X] This is a PR that removes JSON entities.
  - [X] The removed JSON entities have new entries in `data/json/obsoletion/` folder or use some other migration process for existing saves.

## Purpose of change

A macronutritient system idea is floating around for a long time. But if it implemented today, there would be a big lack of protein sources. Mushrooms are a reliable protein source, but their way of farming is just like normal plants, which was a limitation of old code, where "PLANTABLE" flag wasnt jsonized yet.
## Describe the solution

Added mushroom culture as a replacement for seed-like mushroom spore, added racks for artifical mushroom growing medium, while repurposed stumps and trunks for natural alternatives.
## Describe alternatives you've considered

Keep the mushroom spores, or make mushroom culture plantable on dirt
## Testing

Used a local mod for testing
## Additional context
We need a reminder to add protein to mushrooms when we finally add macronutritients

2024-07-03 13:57 UTC, ChucklesTheBeard commented on data/json/obsoletion/recipes.json
> +  },
?

2024-07-03 17:50 UTC, RoyalFox2140 requested changes
You are obsoleting "seed_mushroom" twice on the recipes.json obsoletion file, without obsoleting the recipe for morel spores. You are also either obsoleting "cooked_burrito' or otherwise aren't adding your obsoletions at the end of the file which confused some (including me).

Everything else is fine.

2024-07-03 17:59 UTC, chaosvolt commented on data/json/obsoletion/recipes.json
> +  },
```suggestion
  {
    "type": "recipe",
    "result": "seed_mushroom",
    "obsolete": true
  },
  {
    "type": "recipe",
    "result": "seed_mushroom_morel",
    "obsolete": true
  },
```

2024-07-03 18:09 UTC, chaosvolt reviewed
This is only technically a review just so I can bundle the double-space fixes in one quick commit with less spam.

2024-07-03 18:09 UTC, chaosvolt commented on data/json/items/comestibles/seed.json
> +    "description": "A wet plant chunk, suitable for growing your own mushrooms. You need to \"plant\" it on logs or racks to grow though.",
```suggestion
    "description": "A wet plant chunk, suitable for growing your own mushrooms.  You need to \"plant\" it on logs or racks to grow though.",
```

2024-07-03 18:09 UTC, chaosvolt commented on data/json/furniture_and_terrain/terrain-manufactured.json
> +    "description": "A rack specifically made for raising mushrooms. You can plant mushroom cultures in here.",
```suggestion
    "description": "A rack specifically made for raising mushrooms.  You can plant mushroom cultures in here.",
```

2024-07-03 18:09 UTC, chaosvolt commented on data/json/items/comestibles/seed.json
> +    "description": "A wet plant chunk, suitable for growing your own morel mushrooms. You need to \"plant\" it on logs or racks to grow.",
```suggestion
    "description": "A wet plant chunk, suitable for growing your own morel mushrooms.  You need to \"plant\" it on logs or racks to grow.",
```

2024-07-03 18:42 UTC, chaosvolt commented on data/json/items/comestibles/seed.json
> +    "material": "veggy",
```suggestion
    "name": { "str_sp": "mushroom culture" },
    "weight": "100 g",
    "price": "2 USD",
    "charges": 1,
    "primary_material": "mushroom",
    "color": "light_gray",
    "id": "mushroom_culture",
    "copy-from": "seed",
    "description": "A wet plant chunk, suitable for growing your own mushrooms.  You need to \"plant\" it on logs or racks to grow though.",
    "seed_data": {
      "plant_name": "mushroom",
      "fruit": "mushroom",
      "fruit_div": 2,
      "seeds": false,
      "required_terrain_flag": "MUSHROOM_PLANTABLE",
      "grow": "28 days"
    }
  },
  {
    "type": "COMESTIBLE",
    "name": { "str_sp": "morel mushroom culture" },
    "weight": "100 g",
    "price": "250 cent",
    "price_postapoc": "40 cent",
    "charges": 1,
    "material": "veggy",
```

2024-07-03 19:33 UTC, chaosvolt requested changes
Okay so github is screaming at me so I can't just check this PR out and fix it directly, but: having the mushroom rack be terrain is actually really bad. Planting on terrain converts it to dirt, so you'll be wasting your nails and canvas bag every time, plus this can be constructed on any empty floor as a way to convert it to dirt afterward.

So the obvious answer is make it furntiure instead, but at that point question: do you still want specifically mushroom racks to be a thing separate from planter boxes? If yes then it's mostly gonna be a lot of copy-paste from planter boxes and their stages.

If not, tacking the new flag on empty planter boxes would be much simpler solution for that. Only real question becomes whether you want regular seeds and mushrooms to be plantable on the same furniture or not.

2024-07-03 20:42 UTC, chaosvolt commented
So it turns out it does work fine but only because right now they can only be planted using zone farming, which is something we're going to want to fix in the future. I guess them being terran is fine for now but I'll likely fuck with replacing them with a furniture version in a followup PR.

2024-07-03 21:18 UTC, chaosvolt submitted a review, later dismissed

2024-07-03 21:19 UTC, chaosvolt approved these changes
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/cfc6e6ed-4850-4a15-b325-392ebc857e3a)

2024-07-03 22:09 UTC, chaosvolt approved these changes

2024-07-04 04:41 UTC, merged

2024-07-04 04:41 UTC, chaosvolt commented
Figuring out how to unfuck planting via iexamine is my problem now.