chore(UI): change executable name into "cataclysm-bn-tiles"
cataclysmbnteam/Cataclysm-BN pull request #4989
Opened 2024-07-13 23:20 UTC by Ali-Anomma

## Checklist

### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional
- [X] This is a PR that modifies build process or code organization.
  - [X] Please document the changes in the appropriate location in the `doc/` folder.
## Purpose of change

Apps detecting games, such as Discord considers this game as Cataclysm DDA as they both has same exe name. So i added -bn to this fork, giving a way to differ.

## Describe the solution

Replaced cataclysm-tiles with cataclysm-bn-tiles and replaced cataclysm on cmake files with cataclysm-bn. 

## Describe alternatives you've considered

Look deeply on game detecting apps and make them recognize CBN by just from window name, not the executable one.

## Testing

MSYS2 tiled version showed bn name both on console and task manager. Additional OS and curses tests are welcome.

## Additional context

Should help with #3497.
Discord saying it gets game data from https://www.igdb.com/ , as Discord-recognized CDDA has its own page on it: https://www.igdb.com/games/cataclysm-dark-days-ahead .
We need to do some off site work for recognition.

2024-07-14 01:02 UTC, chaosvolt submitted a review, later dismissed
1. Compiled and load-tested.
2. Discord no longer has it pop up as anything.

![image](https://github.com/user-attachments/assets/36675838-f505-4b5f-a73e-cf2edd817d70)

I assume that's an improvement at least over it mislabeling us as DDA.

2024-07-14 01:05 UTC, scarf005 requested changes
could you check all `cataclysm` and `cataclysm-bn` is changed accordingly?

2024-07-14 01:05 UTC, scarf005 commented on cataclysm-launcher
> +    for bin in cataclysm-bn-tiles cataclysm
```suggestion
    for bin in cataclysm-bn-tiles cataclysm-bn
```

2024-07-14 08:32 UTC, Ali-Anomma commented
> 1. Compiled and load-tested.
> 2. Discord no longer has it pop up as anything.
> 
> ![image](https://private-user-images.githubusercontent.com/11582235/348510143-36675838-f505-4b5f-a73e-cf2edd817d70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDU4NzksIm5iZiI6MTcyMDk0NTU3OSwicGF0aCI6Ii8xMTU4MjIzNS8zNDg1MTAxNDMtMzY2NzU4MzgtZjUwNS00YjVmLWE3M2UtY2YyZWRkODE3ZDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA4MjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGNlODQzNGZkOTE2ZGQwM2ZlNmMzYjc1NWIzZWM5NjhjMTk2YmFiMDVhYzJkMTg4NjVkNzRhNmViNjg5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2SLu8X697ZuhriMMu27-_IObXZ1dUiDRh7fEBbQQm-k)
> 
> I assume that's an improvement at least over it mislabeling us as DDA.

go to discord settings>registered games>add game
there is something named with random numbers and letters (name of CBN instance after cataclysm bright nights part). select it.
igbd registeration needed for universal "Cataclysm: Bright Nights" text for everyone

2024-07-14 09:20 UTC, RoyalFox2140 commented
> 1. Compiled and load-tested.
> 2. Discord no longer has it pop up as anything.
> 
> ![image](https://private-user-images.githubusercontent.com/11582235/348510143-36675838-f505-4b5f-a73e-cf2edd817d70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDkwNDcsIm5iZiI6MTcyMDk0ODc0NywicGF0aCI6Ii8xMTU4MjIzNS8zNDg1MTAxNDMtMzY2NzU4MzgtZjUwNS00YjVmLWE3M2UtY2YyZWRkODE3ZDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA5MTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NTEyYzNhNjM0MzU1ZTg4Yzg5NDM3Nzg3ZDZmMGQzMTM4M2FhNjZhNjc0ODBiYzZkMTM0NDVmOWRmMmVhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ry96jMQD4HHAEXQZEK2PY3LLbUacsRVyeRwJrHUwvc8)
> 
> I assume that's an improvement at least over it mislabeling us as DDA.

Discord manually sets up every connection for the user on their end (Which I am still livid about, you can't change it once they do it) They will not create the connection unless someone emails them about it or gets in contact with someone directly.

2024-07-14 15:43 UTC, chaosvolt commented
Nice, that seems fine to me then.

2024-07-15 03:30 UTC, chaosvolt approved these changes

2024-07-15 04:07 UTC, scarf005 approved these changes
let's see how it turn out...

2024-07-15 04:14 UTC, merged