feat(balance): disassembly learning now works 100% instead of 25%
cataclysmbnteam/Cataclysm-BN pull request #5125
Opened 2024-08-01 15:23 UTC by Lamandus

## Checklist

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

## Purpose of change
Learning something from disassembly was a very frustrating affair. With only a chance of 25% it was a extremly unreliable way in learning a recipe from something. You need 8 tries to have a 90% chance in learning something. That is not good at all (imagine how many engines you have to disassemble to learn anything. It was planned to be linked to INT, but it never happened. So I probably do everyone a favor and cut the "failure" state completly.

If your skills are too low, you still won't learn the recipe, so be careful with that as well.

## Describe the solution
Remove the 3 in 4 chance to fail to learn something. Now one time is enough. No save scumming needed.

## Describe alternatives you've considered
leaving as is, but it is less than optimal.

## Testing
![grafik](https://github.com/user-attachments/assets/37bb7d2a-0239-4acd-9e4f-b426a00a0c9e)

works, loads, all fine.

## Additional context

2024-08-01 15:29 UTC, chaosvolt commented
Making it actually depend on INT is obviously another option, or have the chance increase with how much higher your skill is beyond the base requirement.

Not sure what'd be best.

2024-08-01 15:30 UTC, Lamandus commented
> Making it actually depend on INT is obviously another option, or have the chance increase with how much higher your skill is beyond the base requirement.
> 
> Not sure what'd be best.

but the status quo is not good, that is for certain.

2024-08-01 15:41 UTC, RoyalFox2140 commented
Personally, I believe it should not be RNG-based. However, I think it should be at least 2 items, preferably 3 or 4. Additionally at high enough skill above the item it could lower the amount of items needed up to having it be 1 at double the skill value. This is probably a fine temporary measure until someone wants to make it a bit more complex.

2024-08-01 15:49 UTC, chaosvolt commented
I suppose for now we can add it and mess with adding a less wonky check later. Tracking number of disassemblies and making it 100% after a given number seems like it'd be more hassle to do however.

2024-08-01 15:52 UTC, RoyalFox2140 commented
> I suppose for now we can add it and mess with adding a less wonky check later. Tracking number of disassemblies and making it 100% after a given number seems like it'd be more hassle to do however.

I'll see if Kheir has an idea how to make it not suck as a game mechanic. There has to be a better way somehow.

2024-08-01 15:56 UTC, chaosvolt commented
My rough idea for a better RNG-based method would be something like an `x_in_y` function instead of `one_in`, using 1 + how much you exceed the target skill level for the X. That way it'd become 4 in 4 (thus 100%) once you're 3 skill levels above the target.

2024-08-01 16:09 UTC, RoyalFox2140 commented
> My rough idea for a better RNG-based method would be something like an `x_in_y` function instead of `one_in`, using 1 + how much you exceed the target skill level for the X. That way it'd become 4 in 4 (thus 100%) once you're 3 skill levels above the target.
> 
> It wouldn't be ideal for high-level recipes however.

Int check, relevant CBM's. There's a few ways and means. Though if we tie it to Int my 4 int waifu's are going to have a hard time understanding a brick is a brick.

2024-08-01 16:58 UTC, chaosvolt commented
Taking the "1 + skill excess" and then multiplying it by "current INT divided by 8" would be a way to factor in int too, and make it so that above-average-INT characters can learn the skill earlier, and provide potential for 100% access to recipes that learn at too high a level to exceed the level+3 threshold, yeah. That would indeed make your 4-INT characters suffer :D

2024-08-01 22:16 UTC, KheirFerrum commented
Make it baseline 25%. Every skill level above the minimum increases chance by flat 25%, every 4 levels of int above 4 multiplies total chance by 1.1

I don't personally see the issue with disassemble recipes being RNG. None of them are necessarily critical for progression and the ones that are neat are found in relative abundance.

2024-08-01 23:34 UTC, Lamandus commented
Could someone help me with the code please?

2024-08-01 23:58 UTC, chaosvolt commented
> Could someone help me with the code please?

Something like this probably:
```C++
    const SkillLevelMap &char_skills = who.get_all_skills();
    float skill_bonus = ( 1.0f + char_skills.exceeds_recipe_requirements( dis ) ) * std::max( 1, 0.9f + ( who.int_cur * 0.025f ) );
    if( x_in_y( skill_bonus, 4.0 ) ) {
```

I'm not 100% on the feeding of int values to float-related stuff so it'd need testing.

2024-08-02 06:58 UTC, Lamandus commented
> > Could someone help me with the code please?
> 
> Something like this probably:
> 
> ```c++
>     const SkillLevelMap &char_skills = who.get_all_skills();
>     float skill_bonus = ( 1.0f + char_skills.exceeds_recipe_requirements( dis ) ) * std::max( 1, 0.9f + ( who.int_cur * 0.025f ) );
>     if( x_in_y( skill_bonus, 4.0 ) ) {
> ```
> 
> I'm not 100% on the feeding of int values to float-related stuff so it'd need testing.

1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,90): error C2672: 'std::max': no matching overloaded function found
1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,130): error C2780: '_Ty std::max(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\utility(51): message : see declaration of 'std::max'
1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,130): error C2784: '_Ty std::max(std::initializer_list<_Elem>,_Pr)': could not deduce template argument for 'std::initializer_list<_Elem>' from 'int'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\utility(48): message : see declaration of 'std::max'
1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,130): error C2782: 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': template parameter '_Ty' is ambiguous
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\utility(40): message : see declaration of 'std::max'
1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,130): message : could be 'float'
1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,130): message : or       'int'
1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,130): error C2784: 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': could not deduce template argument for 'const _Ty &' from 'float'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\utility(40): message : see declaration of 'std::max'
1>D:\GitHub\Cataclysm-BN\src\crafting.cpp(2281,130): error C2780: 'const _Ty &std::max(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 2 provided
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\utility(31): message : see declaration of 'std::max'

2024-08-02 08:00 UTC, scarf005 commented
@Lamandus the error happens because you're comparing between int and float. please cast on into another.

2024-08-02 08:00 UTC, scarf005 requested changes

2024-08-02 08:00 UTC, scarf005 commented on src/crafting.cpp
> +            float skill_bonus = ( 1.0f + char_skills.exceeds_recipe_requirements( dis ) ) * std::max( 1,
```suggestion
            float skill_bonus = ( 1.0f + char_skills.exceeds_recipe_requirements( dis ) ) * std::max( 1/0f,
```
the error happens because you're comparing between int and float. please cast it.

2024-08-02 13:41 UTC, Lamandus commented
it builds, thank you @scarf005

2024-08-02 13:48 UTC, Lamandus commented
![grafik](https://github.com/user-attachments/assets/8580a896-84c9-477e-ae0d-d5fa67400b53)
with lvl 10 electronics


![grafik](https://github.com/user-attachments/assets/eae93b0a-8481-4ee9-8f92-d3444fd8af55)

with lvl 2 electronics

2024-08-02 15:39 UTC, chaosvolt approved these changes

2024-08-02 15:46 UTC, merged