Added CheesyInnawoodFixes
cataclysmbnteam/Cataclysm-BN pull request #5315
Opened 2024-09-05 16:48 UTC by cheesealmighty

## Checklist

### Required

- [+ ] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [? ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [? ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [ ?] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

Okay, currently, innawoods content is limited to pre-industrial era, limiting player from accessing most of the content.
 This ports recipes that were made in the CDDA branch for the innawoods mod. Allows strip mining for obtaining most materials. 

## Describe the solution
Makes some recipes autolearn and adds few other recipes for already existing items. Also, adds a recipe for a makeshift transformer, which is basically copper wires wrapped around a steel bit. Also makes the gun recipes autolearned.

## Describe alternatives you've considered
None, currently.

## Testing
I've tested all the recipes in my world, it seems to be working fine.

## Additional context

2024-09-05 16:57 UTC, RoyalFox2140 requested changes
Need to add `"id_suffix"` first on duped recipes like bleach.

2024-09-05 16:58 UTC, RoyalFox2140 commented
Also we need to add a mod in semantics.

2024-09-05 21:10 UTC, chaosvolt commented on data/mods/CheesyInnaWoodsFixes/items/ammo_casing.json
> +    "description": "Alloy of %70 copper and %30 zinc, useful for creating bullet casings.",
```suggestion
    "description": "An alloy of 70% copper and 30% zinc, useful for creating bullet casings.",
```

2024-09-05 21:11 UTC, RoyalFox2140 approved these changes
Well its a little hard to review since it's so large but nothing stands out right now as needing fixing.

2024-09-06 06:51 UTC, Soadreqm commented
I personally feel that most of those recipes _shouldn't_ be autolearned. What's even the point of looting libraries for advanced crafting books, if every forest-dwelling hobo just knows how to craft everything of interest?

2024-09-06 06:59 UTC, scarf005 reviewed
low priority concerns and questions:

- should it be a separate mod? wouldn't it be better to apply the changes to innawoods mod directly?
- please properly fill in checkboxes sections using [github flavoured markdown](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists).

2024-09-06 07:03 UTC, cheesealmighty commented
> I personally feel that most of those recipes _shouldn't_ be autolearned. What's even the point of looting libraries for advanced crafting books, if every forest-dwelling hobo just knows how to craft everything of interest?

Well, yes, but there is a huge amount of content you have no access to in innawoods. The idea of this mod is to have a way to access those  content since no libraries spawn. And that's no fun.



> low priority concerns and questions:
> 
> * should it be a separate mod? wouldn't it be better to apply the changes innawoods mod  directly?
> * please properly fill in checkboxes sections using [github flavoured markdown](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists).

It probably shouldn't be a separate mod, but the idea was to test it out before merging it into the innawoods mod. I've been play testing in my own world, and I know it needs some tweaking and there are gaps. Like, you can craft car batteries but not storage batteries. I would appreciate the feedback in that regard.

2024-09-06 11:02 UTC, chaosvolt requested changes
Gwuh, an absolute ton of things that make no changes relative to vanilla or are otherwise redundant.

2024-09-06 11:02 UTC, chaosvolt commented on data/mods/CheesyInnaWoodsFixes/recipes/new/smelting_bn.json
> +    ]
Good lord three entire recipes that do the same thing as a single vanilla recipe, plus using hematite ore that the mod authors of Innawood stole straight out of Mining Mod (gonna bet 90% odds they didn't credit them either).
```suggestion
```

2024-09-06 13:44 UTC, RoyalFox2140 commented on data/mods/CheesyInnaWoodsFixes/recipes/new/smelting_bn.json
> +    ]
Remember to be nice :D

2024-09-06 13:48 UTC, RoyalFox2140 commented
As a mod I approved the recipe overwrites on the fair assumption they weren't autolearned or changed other stats like difficulty, I checked each overwrite but not to ensure they weren't fully identical.

2024-09-06 13:58 UTC, RoyalFox2140 commented
> I personally feel that most of those recipes _shouldn't_ be autolearned. What's even the point of looting libraries for advanced crafting books, if every forest-dwelling hobo just knows how to craft everything of interest?

So, something I want to do is more auto learn on recipes which is a factor on why I think skill gain is currently too fast, and why I also want to split science from cooking later. I think a lot of recipes bottlenecking you isn't very fun, example is glassblowing requires a specific book but has no use to the player unless they're a base builder.

2024-09-06 18:21 UTC, chaosvolt approved these changes
I...think it's good to go then. A lot of this is likely gonna need additional checking to ensure that all the added recipe overrides work as desired, in particular making sure that they're all identical with the vanilla recipe except for setting autolearn or swapping in relevant makeshift parts, but I think I got most of them.

2024-09-06 18:40 UTC, RoyalFox2140 approved these changes
Should be okay now. It's still hard to review something this large but we'll fix minor stuff in post.

2024-09-06 18:40 UTC, merged