feat: Weapons track what is killed with them
cataclysmbnteam/Cataclysm-BN pull request #5394
Opened 2024-09-21 21:30 UTC by Soadreqm

## Checklist

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

## Purpose of change
This was inspired by a similar feature in Dwarf Fortress _(fig.1)_, where a weapon can be examined to see a list of every creature killed by it. It allows the player to track the historic value of items in their forts, and personal value of items on their characters. If an otherwise mundane weapon is used to kill some legendary beast, or a large number of common beasts, that makes it more interesting than one that was never used.

Cataclysm already keeps track of player kills, but unless you're carefully documenting them by writing notes on your weapon, or writing notes on real life paper, there's no way to know how they were killed.

## Describe the solution
The existing `kill_tracker` class that's used to track player kills was modified to let it work without the event bus that normally updates it. Each item now has its own `kill_tracker`. When performing an attack, the weapon used in the attack is passed through the chain of damage functions, and if the attack results in a kill, it is recorded in the weapon's `kill_tracker`. The examine item menu has a new option _(fig.2)_ to show the item's kill list, similar to the old player kill list. 

This works the same both for ranged and melee weapons, as well as attacks performed by NPCs, _(fig.3)_ including the case where an NPC kills the player. _(fig.4)_

### Memory footprint
There were some concerns raised about this in the Discord. I don't think it's going to be an issue, but admittedly I don't really know anything about C++ memory management. Here are some numbers from the Visual Studio memory layout tool: 

All items everywhere have a new pointer for the `kill_tracker`, which means eight bytes on the 64-bit build.
The `kill_tracker` is only created when an item is used to kill something, and it has an overhead of 64 bytes, consisting of:
* 16 bytes inherited from `event_subscriber`, which aren't actually needed here
* 8 bytes for a single boolean, which really should take a single bit but apparently ends up taking 64 because the next chunk of data is offset to the start of the next 8-byte block
* 24 bytes for a map of mtype_id - int pairs, for monster kills
* 40 bytes for a vector of strings, for NPC kills

This is in addition to the data itself, which is essentially the same as what's already saved by the existing kill tracker. There are exceptions, since weapons can record kills by NPCs, and the main tracker can record kills without weapons. For the most part, though, we're looking at a single duplicate of every record, spread across a number of items.

## Describe alternatives you've considered
Discord feedback also suggested that kills should only be tracked for specific weapons (e.g. those marked as favourite) or special monsters (e.g. Jabberwocks). Personally, I think that it's better to record all items, and all kills. Any item can hypothetically be wielded as a weapon, and if I manage to e.g. kill a zombie with a carrot, I'd certainly want to have ingame proof. 
If other people want stricter limits, though, implementing them at this point should be fairly easy. 

Items that are `count_by_charges` (e.g. planks) can have their kills recorded as normal, but this record is lost when the item is combined into a stack. Normal stacking items (e.g. throwing knives) don't lose the record, but there's no easy way to find a specific throwing knife from the stack - you need to wield them one by one and examine every one. Changing the normal stacking behaviour wouldn't be a good idea, since it'd fill your inventory with individual throwing knives, and stop you from carrying planks. I believe both of these issues could still be fixed, but I'm not sure if it'd be worth it. As a workaround, writing a note on the item, renaming it or marking it as a favourite all prevent it from stacking.

The UI could be nicer. The current window is just copypasted from the achievements display, with the achievements and stats cut out. Also, I'd specifically like to display the total number of kills in the item examine menu, right next to the `K Kills` option, but that'd require further extensive changes. That text is pulled from a json file, you can't just write to it.

## Testing
* Killed monsters with melee weapons, guns and throwing weapons. Weapons had their kills recorded.
* Killed monsters with a shotgun using dragonbreath shells, which uses `hit_with_aoe()` instead of `deal_projectile_attack()`. That worked too.
* Watched an NPC kill monsters, and then killed that NPC. NPC's weapon had its kills recorded, as did the weapon used to kill the NPC.
* Committed suicide by NPC, then killed the NPC with a different character to examine the weapon. The weapon had the player kill recorded.
* Spawned a foam bat and gave myself hooves. Attacked a monster until a kick attack killed it. The foam bat did not get a kill.
* Killed a monster with a plank, and then dropped that plank on another plank on the ground. Repeated the test, but dropped the weapon plank first and then another fresh plank on top of it. Picked up planks one by one to break the stacks and examined them. None had any kills. So long as the kill tracker doesn't get duplicated it's fine IMO.
* Allowed monsters to kill me both with melee and ranged attacks, just to make sure I didn't horribly break anything while messing with the damage functions. Monsters were able to deal damage, game did not crash.

## Additional context
![df-2024-09-21-18-33-44](https://github.com/user-attachments/assets/367eda59-48de-4d2a-a9fc-f67f18c0aff8)
_fig.1: Adventurer beating wildlife to death with a dead crab_

![cata-2024-09-21-19-42-27](https://github.com/user-attachments/assets/d0d3e47e-179b-48d1-ab1f-a4c62243698e)
_fig.2: That "Kills" option only appears if the item actually has a kill list_

![cata-2024-09-21-16-43-16](https://github.com/user-attachments/assets/234d65da-ea23-4100-bbb6-f4528e65a99d)
_fig.3: This pistol was used by an NPC to help me fight the test monsters I summoned_

![cata-2024-09-21-17-34-06](https://github.com/user-attachments/assets/1b37dd37-0efb-412c-973b-d87fd91ac0bd)
_fig.4: Steven Barkley was me_

2024-09-21 22:10 UTC, KheirFerrum commented
This has been brought up in the Discord, so I'm just making sure to note down my issues with this here, which is mainly that I don't think we benefit from all items attempting to track all kills.

Memory issues aside, I don't see the benefit, it makes sense for tracking named/artifact kills and named/special monster deaths, but every item potentially tracking every death inflicted by it sounds very expensive and very costly for no good reason. Dwarf Fortress cares about this stuff because it attempts to simulate a history of civilizations, creatures, etc. Cataclysm has no need for such a thing, so having a plank remember every zombie it's squished seems problematic.

In terms of memory issues itself, while it's not our priority, people _do_ play this on their mobiles, so some way to disable the thing or restrict the memory it uses is going to be fairly helpful to allow those insane people to keep doing so. It's also a secondary reason as to me wanting a justification of why such a thing need be tracked.

> Discord feedback also suggested that kills should only be tracked for specific weapons (e.g. those marked as favourite) or special monsters (e.g. Jabberwocks). Personally, I think that it's better to record all items, and all kills. Any item can hypothetically be wielded as a weapon, and if I manage to e.g. kill a zombie with a carrot, I'd certainly want to have ingame proof.
If other people want stricter limits, though, implementing them at this point should be fairly easy.

Specifically for this, I don't see a reason why "proof" is necessary, bragging rights shouldn't really need this kind of tracking from our side.

2024-09-21 22:24 UTC, chaosvolt commented
Yeah, it's honestly been made pretty clear that we should avoid adding excess data for every item in the game unless it's for something nessecary.

If you can confirm how much extra data is stored for an item that has an empty kill feed, and that extra isn't too high for weapons not yet used to kill anything, then maybe it's reasonable.

Moreover, I'd want you to test what this does for stacking items like planks, scrap metal, ammo, etc.

2024-09-21 23:20 UTC, RoyalFox2140 commented
I really want to make sure the code and performance is reviewed extensively before this is merged. Also clang-tidy is failing for some reason.

2024-09-21 23:23 UTC, RoyalFox2140 commented
> In terms of memory issues itself, while it's not our priority, people _do_ play this on their mobiles, so some way to disable the thing or restrict the memory it uses is going to be fairly helpful to allow those insane people to keep doing so. It's also a secondary reason as to me wanting a justification of why such a thing need be tracked.

I've asked Oren to review this with the performance profiler now that the PR is live. It's not up to me to decide how much more data and memory should be used, but we need to know metrics here and make an informed decision.

2024-09-21 23:32 UTC, RoyalFox2140 reviewed
Just off the description here:
> The existing kill_tracker class that's used to track player kills was modified to let it work without the event bus that normally updates it

You've decided people can no longer disable this feature by ensuring the event bus doesn't track it. Is it really necessary to do this? 

![image](https://github.com/user-attachments/assets/6474327d-5dca-4ed8-b2e8-c87c3bec4623)

2024-09-21 23:36 UTC, chaosvolt commented
Unless, will turning event bus off just remove kill tracking, or does it outright break instead?

2024-09-22 06:52 UTC, Soadreqm commented
@RoyalFox2140 
>You've decided people can no longer disable this feature by ensuring the event bus doesn't track it. Is it really necessary to do this?

Yeah, no, that's definitely not how it should be. I added a check for whether ENABLE_EVENTS is on, and if it isn't, the weapon kill tracker will be disabled as well. It's technically not accurate, since I'm not actually using the event bus, but it seems reasonable that anyone turning that off would want this disabled as well.

It doesn't wipe existing weapon kills if the option is toggled midgame. I could add a check when saving or loading to quietly drop the data. Another option would be to disable displaying them, though that obviously wouldn't help performance.

2024-09-22 06:57 UTC, Soadreqm commented
@chaosvolt 
>If you can confirm how much extra data is stored for an item that has an empty kill feed, and that extra isn't too high for weapons not yet used to kill anything, then maybe it's reasonable.
>Moreover, I'd want you to test what this does for stacking items like planks, scrap metal, ammo, etc.

For weapons with an empty kill feed, it's just one pointer.

I did test planks, and it looks like the kill record is lost forever when they're stacked. Tried dropping a kill plank on a fresh plank and vice versa, after separating the stack again all planks were clean. If you can think of something else to try, I'll give it a shot. I think losing records is acceptable, but if there's some way to duplicate the record to hundreds of planks, that would definitely be a problem.

2024-09-22 07:32 UTC, Soadreqm commented
@KheirFerrum 
> In terms of memory issues itself, while it's not our priority, people _do_ play this on their mobiles, so some way to disable the thing or restrict the memory it uses is going to be fairly helpful to allow those insane people to keep doing so. It's also a secondary reason as to me wanting a justification of why such a thing need be tracked.

As for **why** it needs to be tracked, I think that's going to be somewhat subjective. I find this kind of information interesting, and I suspect there are others, since someone went to the trouble of creating the event system and the kill tracker in the first place. It's already tracking things like how many tiles you've walked, even though that probably isn't something most players particularly care about. Some people do want to know that, or know the exact date down to the second that they reached skill level 5 in electronics. **I** want to know how many monsters I've killed with a length of pipe. In both cases, it's not information that can be easily tracked outside the game, unless you're stopping every turn to take notes. Is it a problem to track it inside the game, so long as it's not obtrusive?

For practical considerations, so far I've made it respect the EVENTS_ENABLED game option. Do you think that would be a reasonable approach, or should there be a separate toggle for people who want achievements, but don't want this?

Also, do you think disabling the option midgame should wipe the data from the items? The current behaviour with the general kill tracker and achievements is that turning it off won't erase anything, it'll just stop recording new data.

2024-09-22 11:05 UTC, RoyalFox2140 commented
> I find this kind of information interesting,

It is interesting. I want to see the feature but there's a lot to consider due to the impact it will have on the codebase. 

> For practical considerations, so far I've made it respect the EVENTS_ENABLED game option. Do you think that would be a reasonable approach, or should there be a separate toggle for people who want achievements, but don't want this?

This depends entirely on how badly this affects Android users and if that will improve their performance. Currently turning off event bus breaks a lot of mods and features so I think we'd have to have a separate option if the performance is impactful enough for mobile.

> Also, do you think disabling the option midgame should wipe the data from the items? The current behaviour with the general kill tracker and achievements is that turning it off won't erase anything, it'll just stop recording new data.

I don't think it matters unless it slows down the reality bubble or the save times even after you've disabled kill tracking. We can cross the bridge when we get there.

2024-09-22 14:02 UTC, KheirFerrum commented
> @KheirFerrum
> 
> > In terms of memory issues itself, while it's not our priority, people _do_ play this on their mobiles, so some way to disable the thing or restrict the memory it uses is going to be fairly helpful to allow those insane people to keep doing so. It's also a secondary reason as to me wanting a justification of why such a thing need be tracked.
> 
> As for **why** it needs to be tracked, I think that's going to be somewhat subjective. I find this kind of information interesting, and I suspect there are others, since someone went to the trouble of creating the event system and the kill tracker in the first place. It's already tracking things like how many tiles you've walked, even though that probably isn't something most players particularly care about. Some people do want to know that, or know the exact date down to the second that they reached skill level 5 in electronics. **I** want to know how many monsters I've killed with a length of pipe. In both cases, it's not information that can be easily tracked outside the game, unless you're stopping every turn to take notes. Is it a problem to track it inside the game, so long as it's not obtrusive?

That's a cost that need be considered, under the hood or not, what I don't want is for us to add many little features that track trivia slowly eating up RAM/processing cumulatively just because "why not?". It removes margins that we may or may not need for other features with practical gameplay interactions, and I lean on the conservative end for that. This cost is one of the reasons a large number of legacy systems affect the player only, which we will need to expand at some point as they have tangible gameplay effects, like pain, scent, etc.

> For practical considerations, so far I've made it respect the EVENTS_ENABLED game option. Do you think that would be a reasonable approach, or should there be a separate toggle for people who want achievements, but don't want this?

This comes down to several points. From what I can see your disabling occurs at the level of adding to the list, which may be a little late depending on where and how this thing is called. I have yet to read in-depth on how you've altered the attack functions to feed the item to the kill_tracker, but if people turned the kill_tracker for items off to begin with, then the function shouldn't even need to feed the item to it for consideration.

Second, the event bus hooks into a lot of places, which is why it causes a fairly large amount of slowdown through it's various watchers, you are essentially creating a single watcher and event firing that happens every time something dies. I'd likely want this to get disabled separately, depending on the impact relative to the event bus, but this again comes down to how well your boolean cuts down on processing.

> Also, do you think disabling the option midgame should wipe the data from the items? The current behaviour with the general kill tracker and achievements is that turning it off won't erase anything, it'll just stop recording new data.

My suggestion would be yes, given that the option is meant to deal with perf issues, keeping the data essentially fills RAM with excess data that otherwise is pointless. You can make a big red warning about it clearing if you want, but my opinion is that it should clear it.

Also am I understanding that the game is storing NPCs as string names? ~~This is another part where I note the difference between DF and us, as DF actually cares about remembering NPCs and monsters after they have died, whereas we generally don't care~~

2024-09-22 15:14 UTC, RoyalFox2140 commented
> Also am I understanding that the game is storing NPCs as string names? ~This is another part where I note the difference between DF and us, as DF actually cares about remembering NPCs and monsters after they have died, whereas we generally don't care~

As the resident person who carries the Psychopath trait as a free trait in chargen I can safely say we already store the full name of NPC's on the kill feed even before this PR is merged. That's default behavior but it may not be noticeable if you haven't cleaned house sometimes like I have and you get 40 individual names in the feed. Just clarifying that.

2024-09-22 17:48 UTC, Coolthulhu requested changes
Might be worth the extra bytes and cycles, even if most players won't care.
I'd give it a try.

2024-09-22 17:48 UTC, Coolthulhu commented on src/ballistics.cpp
> +        Creature *origin, item *s_weapon, const vehicle *in_veh )
Naming: that `s_` is weird. I assume it means "source". It's better to fully type it out.

2024-09-22 17:48 UTC, Coolthulhu commented on src/creature.h
> +        virtual dealt_damage_instance deal_damage( Creature *source, bodypart_id bp,
Warnings need to be resolved here.

2024-09-22 17:48 UTC, Coolthulhu commented on src/ballistics.h
> +        Creature *origin = nullptr, item *s_weapon = nullptr, const vehicle *in_veh = nullptr );
Naming: I assume `s_` is for "source". Random abbreviations aren't good, it's better to have long names than potentially misleading ones.

2024-09-22 17:48 UTC, Coolthulhu commented on src/npc.cpp
> +    }*/
Forgotten unimplemented feature code

2024-09-22 18:26 UTC, Soadreqm commented on src/creature.h
> +        virtual dealt_damage_instance deal_damage( Creature *source, bodypart_id bp,
I'm not getting them locally, but I suspect they're happening because the override in `character` doesn't have explicit overloads.

2024-09-27 10:20 UTC, Coolthulhu approved these changes

2024-09-27 13:32 UTC, RoyalFox2140 commented
I am utterly unqualified to look over this code, so whenever it's in an official release I'll be sure to playtest it a lot and see how it affects the perf.

2024-09-28 21:32 UTC, chaosvolt approved these changes
1. Compiled and load-tested.
2. Beat a zombie to death with a rock. It's credited for the kill.
3. It still correctly stacks with other rocks, but loses kill info in the process.
4. Threw rocks at a zombie to kill it. No sign of kill feed.
5. Beat a zombie to death with the entire stack of rocks, it gets to count as having killed a zomnbie but this seems to be lost the instant I drop the rocks on the ground.
6. Finally spawned in a normal weapon, a cudgel, and beat a zombie to death with it. It gets credited for the kill and this persists even after I drop it and pick it back up.
7. Gave myself two cudgels, kill info vanishes when they're together in inventory but if I split them up again one of the cudgels still has the kill info.

This is as expected very janky when it comes to items you mix up with other items, but that seems to be basically unavoidable.

2024-09-28 22:08 UTC, merged

2024-10-04 23:09 UTC, Ignaramico commented
does this affect the normal kill count list?, if so, does it affects the mod "exp trough kills" (irrc the name)?

2024-10-04 23:31 UTC, RoyalFox2140 commented
> does this affect the normal kill count list?, if so, does it affects the mod "exp trough kills" (irrc the name)?

No. It's just it's own thing unless something was missed in testing. I had asked Coolthulhu personally check it to make sure it was as safe as possible to merge.

2024-10-05 07:28 UTC, Soadreqm commented
@Ignaramico
It doesn't (or at least it bloody well shouldn't). I reused the same `kill_list` class that's used for the normal kill list, but I added a check to make sure only the main list can grant XP.

I don't usually play with exp through kills on, though, so if you notice anything odd, please report it.