fix: Molotov Fix/Rework, make `turn_per_charge` less inconsistent.
cataclysmbnteam/Cataclysm-BN pull request #5480
Opened 2024-10-01 05:55 UTC by KheirFerrum

## Checklist

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

- fixes #5464 which was due to #5297 causing this to disappear really early as it quickly hits 0 charge.
- Aims to make `turns_per_charge` less inconsistent by having tool items keep track of how long they've been active since last consumption.

## Describe the solution

- Molotov behaviour is now changed in the following ways
  - Lighting a molotov now keeps it lighted for 5 turns, after which it's charge is fully consumed and it reverts back to an unlit molotov with 0 charges.
    - Unlit molotovs now use rags to reload, if you activate it and don't use it quickly enough, you'll have wasted a rag (which is common enough that I doubt this will penalize anyone)
  - Molotovs now need at least 1 charge to be lit.
  - Dropping a molotov no longer causes it to explode. Now if you for some reason need to set the ground around you ablaze you can just activate the molotov again and it will ask you if this is what you really want.

- Tool items with `turns_per_charge` now keep track of how long they have been active via `turns_active` variable.
  - If `turns_active` exceeds `turns_per_charge` the item consumes it's per turn charges and resets `turns_active.
  - Modified the foodperson helmet to keep track of this as well when telling you how much time is left on your shift.

## Describe alternatives you've considered

- Reworking the entire molotov iuse to make it more versatile for impact explosives.
  - I don't have time for this right now, so this will last as a stopgap measure that restores functionality until I have time to make it better than it was.

## Testing

- [x] Molotovs can be activated, and after exactly 5 turns revert into the unlit variant with 0 charges
  - [x] Molotovs cannot be activated without charges, and can be reloaded with rags.
  - [x] Molotovs explode when thrown, not when dropped, not when left on the floor, and not in your inventory.
  - [x] Activating a lit molotov asks you if you want to smash it on yourself, if you cancel, nothing happens, if you confirm it explodes it on your tile.
- [ ] Save and load remembers how long the molotov has already been active

## Additional context

2024-10-01 15:28 UTC, KheirFerrum commented
> 1. Compiled and load-tested.
> 2. Spawned in and activated a molotov.
> 3. Tossed it, it go fwoosh yaaay.
> 4. Spawned in rags and tested to make sure that changing them to ammo doesn't screw up their use actions.
> 5. Crafted a molotov. It still consumes a rag as a component in the recipe, but produces a molotov with 0/1 ammo in it so you need to waste a second rag loading it.

Looks like setting it to use tangible ammo makes it not be created with initial charges, will remove rags from the recipe.

2024-10-01 15:34 UTC, chaosvolt commented
Specifying `initial_charges` in the item wouldn't work?

2024-10-01 15:37 UTC, KheirFerrum commented
> Specifying `initial_charges` in the item wouldn't work?

It already has it to begin with. It just doesn't apply outside of debug spawning it it seems.

2024-10-01 15:43 UTC, chaosvolt commented
Ah right, damn. Guess that works but it feels real hacky having to load the rag manually after filling it, hmm. This is technically only mandated by it having `turns_per_charge` defined, right? Though I suppose without it, and combined with it no longer going off when dropped, the player could exploit an infinitely-burning molotov for light, bleh. :/

2024-10-01 16:14 UTC, KheirFerrum commented
> Ah right, damn. Guess that works but it feels real hacky having to load the rag manually after filling it, hmm. This is technically only mandated by it having `turns_per_charge` defined, right? Though I suppose without it, and combined with it no longer going off when dropped, the player could exploit an infinitely-burning molotov for light, bleh. :/

It's technically mandated by me making them reloadable with rags. If we went by the old behaviour, every time it went out it would refill it's charges and you could light it again.

2024-10-01 17:33 UTC, chaosvolt commented
Fair, I was wondering whether that'd technically be okay on the basis of the rag serving as a wick, but this would technically make the fuel infinite-use instead. This would only really matter if the player repeatedly lights a molotov and lets it burn out again and again until they start questioning why it hasn't run out of fuel by then, but that'd be a bit of a wacky scenario to begin with.

2024-10-01 17:39 UTC, KheirFerrum commented
> Fair, I was wondering whether that'd technically be okay on the basis of the rag serving as a wick, but this would technically make the fuel infinite-use instead. This would only really matter if the player repeatedly lights a molotov and lets it burn out again and again until they start questioning why it hasn't run out of fuel by then, but that'd be a bit of a wacky scenario to begin with.

To be fair another way we could do it is have it never burn out and only be "extinguished" by rain

2024-10-01 17:43 UTC, RoyalFox2140 commented
![image](https://github.com/user-attachments/assets/da6990d8-9c9b-4df9-982b-0f39e64d1d5b)
Huh.

2024-10-01 17:45 UTC, RoyalFox2140 approved these changes

2024-10-01 17:53 UTC, chaosvolt commented
I think it just burning out after a bit but being able to be re-lit without having to provide a fresh rag is probably acceptable, compared to having to manually stuff the rag in before use each time after making it. Like I said, it would only look weird if the player lights and extinguishes it multiple times, whereas the rag thing will look weird every time one's crafted.

2024-10-01 18:17 UTC, KheirFerrum commented
> I think it just burning out after a bit but being able to be re-lit without having to provide a fresh rag is probably acceptable, compared to having to manually stuff the rag in before use each time after making it. Like I said, it would only look weird if the player lights and extinguishes it multiple times, whereas the rag thing will look weird every time one's crafted.

I feel like the latter makes more sense than the former, though like... we could also just make it burn forever and have the activation effect allow you to manually extinguish it. I just feel that the behaviour where you can wait it out and relight it is very odd.

2024-10-01 18:33 UTC, chaosvolt commented
That would work I guess too? I just find it really weird having to craft a molotov and then basically "fuze" it manually afterward. It stands out as kinda weird when every other grenade-type item in the game is crafted as an all-in-one deal.

2024-10-01 18:36 UTC, KheirFerrum commented
> That would work I guess too? I just find it really weird having to craft a molotov and then basically "fuze" it manually afterward. It stands out as kinda weird when every other grenade-type item in the game is crafted as an all-in-one deal.

Okay. I also recalled that `WATER_EXTINGUISH` won't proc this charge renewal, which is a problem.

2024-10-01 18:37 UTC, scarf005 commented
maybe we could make molotov use oil as charge?

2024-10-01 18:37 UTC, KheirFerrum commented
> maybe we could make molotov use oil as charge?

Pretty sure it having an ammo type at all is what's causing it to spawn with no charges.

2024-10-01 18:40 UTC, scarf005 commented
> Pretty sure it having an ammo type at all is what's causing it to spawn with no charges, so changing that won't change the problem.

oh, i meant as a balance change.

2024-10-01 18:40 UTC, KheirFerrum commented
> > Pretty sure it having an ammo type at all is what's causing it to spawn with no charges, so changing that won't change the problem.
> 
> oh, i meant as a balance change.

Doesn't really change anything, you still use oil/incendiary in the crafting recipe.

2024-10-01 18:42 UTC, chaosvolt commented
I think it'd be fine in this case to go with it having charges but no ammotype (or even not having charges at all, so long as it won't cause any odd behavior if it reverts from a partially-depleted lit molotov with charges to an unlit molotov without charges), so that it's crafted in an actually ready-to-light state like it originally was, and if anything extinguishes it before it detonates have it revert back to being ready-to-light as if nothing happened. This should only really matter if the player basically changes their minds about throwing it (and right now we'd have to actually allow that since right now you replaced it with a suicide-bomber option), or if it gets doused.

2024-10-01 18:43 UTC, KheirFerrum commented
> I think it'd be fine in this case to go with it having charges but no ammotype (or even not having charges at all, so long as it won't cause any odd behavior if it reverts from a partially-depleted lit molotov with charges to an unlit molotov without charges), so that it's crafted in an actually ready-to-light state like it originally was, and if anything extinguishes it before it detonates have it revert back to being ready-to-light as if nothing happened. This should only really matter if the player basically changes their minds about throwing it (and right now we'd have to actually allow that since right now you replaced it with a suicide-bomber option), or if it gets doused.

I didn't "replace" the option with a suicide bomber option, that was _always_ how it worked, if you activated the lit molotov, it would explode, I just added a y/n query so the player doesn't die a stupid death.

2024-10-01 18:50 UTC, chaosvolt reviewed
These should be all the changes needed to make it do the "return to a lightable molotov if it goes out" thing, lemme know if I missed anything.

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/ammo_types.json
> +  },
```suggestion
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/generic.json
> +    "type": "AMMO",
```suggestion
    "type": "GENERIC",
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/generic.json
> +    "ammo_type": "rag",
```suggestion
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/tool/explosives.json
> +    "description": "A bottle of flammable liquid.  Reload it with rags to arm it, then use this item to light the rag.  You will, of course, need a lighter or matches in your inventory to do this.  A
```suggestion
    "description": "A bottle of flammable liquid with a rag inserted.  Use this item to light the rag.  You will, of course, need a lighter or matches in your inventory to do this.  After lighting it, throw it to cause fires.",
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/tool/explosives.json
> +      "target_ammo": "rag",
```suggestion
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/tool/explosives.json
> +    "ammo": [ "rag" ],
```suggestion
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/tool/explosives.json
> +      "need_charges": 1,
```suggestion
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/items/tool/explosives.json
> +    "ammo": [ "rag" ],
```suggestion
```

2024-10-01 18:50 UTC, chaosvolt commented on data/json/recipes/weapon/explosive.json
> +    "components": [ [ [ "bottle_glass", 1 ], [ "flask_glass", 1 ], [ "clay_canister", 1 ] ] ]
```suggestion
    "components": [ [ [ "rag", 1 ] ], [ [ "bottle_glass", 1 ], [ "flask_glass", 1 ], [ "clay_canister", 1 ] ] ]
```

2024-10-01 18:50 UTC, chaosvolt commented on data/mods/Item_Category_Overhaul/overwrite_scrap.json
> +    "type": "AMMO",
```suggestion
    "type": "GENERIC",
```

2024-10-01 18:52 UTC, KheirFerrum commented
> These should be all the changes needed to make it do the "return to a lightable molotov if it goes out" thing, lemme know if I missed anything.

There's still `iuse` code that needs to be done to make it revert properly when running out of charges and water_extinguish code. This just reverts it to the prior broken state. Give me a few minutes.

2024-10-01 18:53 UTC, chaosvolt commented
Ah, no worries then. I'm currently out and about on wifi so won't be able to compile-test the new changes until I get home, so take your time if needed. ^^

2024-10-01 19:14 UTC, RoyalFox2140 commented
So to be fair, I only tested spawning it, not crafting it. Why it spawns as 0/1 is beyond me.

2024-10-01 19:15 UTC, KheirFerrum commented
> So to be fair, I only tested spawning it, not crafting it. Why it spawns as 0/1 when crafted is beyond me.

Because it's been given an ammo type, there's no code to make it spawn with specific ammo and count, and it defaults against that in case you're making magazines and the like. Anyway, code's rewritten, updating the original PR. I'm annoyed, but hey, it works about right now

2024-10-01 19:25 UTC, RoyalFox2140 requested changes
![image](https://github.com/user-attachments/assets/7b18c6b6-f419-4001-a651-a27f6537b6f7)
I can't in good faith accept an infinite light source exploit by holding lit molotovs in my inventory indefinitely. Someone else can feel free to accept the PR if they don't see it as a big deal.

2024-10-01 19:53 UTC, chaosvolt commented
Hmm. I thought the idea was they'd burn out and revert back to an unlit molotov if you don't throw them quickly enough?

2024-10-01 19:55 UTC, chaosvolt commented on data/json/items/tool/explosives.json
> +      "target_ammo": "rag",
This one was resolved without being applied, will cause problems because it's trying to apply an ammotype that no longer exists.

2024-10-01 19:56 UTC, KheirFerrum commented on data/json/items/tool/explosives.json
> +      "target_ammo": "rag",
Technically it won't because it gives 0 charges, so gets skipped, but yeah, will be removed.

2024-10-01 20:04 UTC, KheirFerrum commented
> Hmm. I thought the idea was they'd burn out and revert back to an unlit molotov if you don't throw them quickly enough?

All three implementations have issues, some are under the hood, and some are overt.

Original (intended) implementation
- Behaviour: Item reverts after several turns, refilling it's charges to full again to allow reignition.
- Drawbacks: Code needs special handling as `revert()` preserves current charges, so both the `iuse` code and `WATER_EXTINGUISH` code must restore charges, and `WATER_EXTINGUISH` code must specifically target only items with `iuse::molotov_lit` or we get cigarettes that replenish themselves to full as long as you douse them in water before they are depleted.

Rag implementation
- Behaviour: Item reverts after several turns, consuming a rag to fuel it.
- Drawbacks: Recipe cannot produce molotov with charges, so players must manually reload them on craft.

New implementation
- Behaviour: Item doesn't revert unless in water or player extinguished, can essentially be toggled between both.
- Drawbacks: Infinite light source.

I don't like the first implementation because it's a lot of special case code handling for 1 specific iuse that needs to be careful about not treading on anything else's toes. And I can't just revert it to the original implementation and expect it to be fine because the original code as is doesn't revert at all when `WATER_EXTINGUISH` procs, invoking a non-existent transform that fails and leaves an inactive lit molotov. Adding revert means that it will revert into a molotov that has no charges.

2024-10-01 20:48 UTC, RoyalFox2140 commented
![image](https://github.com/user-attachments/assets/ae6afef1-4625-4d69-9fb6-51abee332214)

2024-10-01 20:48 UTC, RoyalFox2140 approved these changes
I mean, It works as intended and works under our old system of being relightable forever. It's not ideal but it's what we have right now.

2024-10-01 21:11 UTC, chaosvolt approved these changes
Hopefully is fine then, still out and about so can't compile-test weh

2024-10-02 03:21 UTC, chaosvolt commented
1. Compiled and load-tested.
2. Crafted a molotov.
3. Lit it, let it burn out, no odd behavior and I can re-light it without issue.
4. Lit it, tossed it, it go fwoosh. :D

2024-10-02 03:21 UTC, merged