fix: putrid heart is now consumed after use
cataclysmbnteam/Cataclysm-BN pull request #5493
Opened 2024-10-03 06:45 UTC by IllusionDX

## Checklist

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

## Purpose of change
Fixes #5481

## Describe the solution

Adjusts the use_item function in avatar_functions.cpp, so that it doesn't check if the item doesn't have an use AND is either food or med to consume it, instead it just checks if it's food or med.

## Describe alternatives you've considered

Adding a bunch of jank on Character::invoke_item.

## Testing

I tested with a bunch of items like the putrid heart, mutated leg, mutated arm, mutated fetus, and some unrelated items. It seems to work ok without breaking anything? 
Plus I think the only food or drink item that has an external use_action (meant to be used on another creature) is the pet food and that's already handled by the two cases above the line changed. Correct me if I'm wrong.

![cataclysm-bn-tiles_NFPLEKbhCa](https://github.com/user-attachments/assets/5f71f79d-8797-4bd1-94ec-af68b78ace3e)
![cataclysm-bn-tiles_NSOBTkVOcY](https://github.com/user-attachments/assets/51ce056c-350e-41e0-86ec-3bfb70f5841a)
![cataclysm-bn-tiles_qpICIShg9m](https://github.com/user-attachments/assets/ce28f835-b9e0-4c39-9a68-f1a7b00d5dd4)

2024-10-03 07:02 UTC, scarf005 commented on src/avatar_functions.cpp
> +                                     used.get_contained().is_medication() ) ) {
bit worried on implications on this, probably need to learn why it was like this first

2024-10-05 10:07 UTC, Soadreqm commented on src/avatar_functions.cpp
> +                                     used.get_contained().is_medication() ) ) {
It looks like it's there to catch a case where an item can be either 'a'pplied or 'e'aten, and is _meant_ to have a different effect depending on which one you do. I can't think of any items that would apply to, though. I tested this with the internal furnace CBM, and that's apparently handled elsewhere, because it still works normally.

2024-10-05 12:12 UTC, chaosvolt commented on src/avatar_functions.cpp
> +                                     used.get_contained().is_medication() ) ) {
Petfood is the only item I can recall that has different effects when applied vs eaten.

2024-10-08 21:19 UTC, RoyalFox2140 commented
How goes this PR? Any blockers to merge?

2024-10-08 22:10 UTC, chaosvolt commented
Only thing evidently is needing to test whether the code change commented on above causes any problems.

2024-10-17 14:14 UTC, chaosvolt requested changes
Sorry it took a while for me to remember to test this.

1. Compiled and load-tested.
2. Spawned in and tested using putrid heart, it mutates you as expected when eaten or when activated.
3. Tested dog food, it still works when activated or eaten.
4. Tested regular mutagen and serum, they work when consumed, but serum no longer works when activated.

So, this seems to have broken an item I wasn't expecting to be broken, but didn't affect the item I was expecting to break.

2025-03-17 16:51 UTC, chaosvolt commented
Closing as the issue it fixes has at some point already been fixed.

2025-03-17 16:51 UTC, closed without merging