feat(port,content): Winged zombies
cataclysmbnteam/Cataclysm-BN pull request #5586
Opened 2024-10-19 01:41 UTC by Zlorthishen

## Checklist

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

## Purpose of change
ports 
 - https://github.com/CleverRaven/Cataclysm-DDA/pull/43188

## Describe the solution

## Describe alternatives you've considered

## Testing

## Additional context

2024-10-23 01:23 UTC, chaosvolt reviewed
Looks aight, they no longer spawn next to the player which was if I recall what killed the port the first time.

These flags would be good to have to make it not make explosion noises and show a visual explosion effect though.

2024-10-23 01:23 UTC, chaosvolt commented on data/json/monster_special_attacks/spells.json
> +    "flags": [ "HOSTILE_SUMMON", "RANDOM_DAMAGE", "PERMANENT" ],
```suggestion
    "flags": [ "HOSTILE_SUMMON", "RANDOM_DAMAGE", "PERMANENT", "NO_EXPLOSION_VFX", "SILENT" ],
```

2024-10-23 01:23 UTC, chaosvolt commented on data/json/monster_special_attacks/spells.json
> +    "flags": [ "HOSTILE_SUMMON", "RANDOM_DAMAGE", "PERMANENT" ],
```suggestion
    "flags": [ "HOSTILE_SUMMON", "RANDOM_DAMAGE", "PERMANENT", "NO_EXPLOSION_VFX", "SILENT" ],
```

2024-10-23 01:23 UTC, chaosvolt commented on data/json/monster_special_attacks/spells.json
> +    "flags": [ "HOSTILE_SUMMON", "RANDOM_DAMAGE", "PERMANENT" ],
```suggestion
    "flags": [ "HOSTILE_SUMMON", "RANDOM_DAMAGE", "PERMANENT", "NO_EXPLOSION_VFX", "SILENT" ],
```

2024-10-23 01:23 UTC, chaosvolt commented on data/json/monster_special_attacks/spells.json
> +    "flags": [ "LOUD", "RANDOM_DAMAGE" ],
Random damage isn't needed when it's 250 for min and max.
```suggestion
    "flags": [ "NO_EXPLOSION_VFX", "SILENT" ],
```

2024-10-23 01:38 UTC, chaosvolt approved these changes

2024-10-23 02:02 UTC, chaosvolt commented
Wait, is it intentional that they can't actually fly? o.O

2024-10-23 02:19 UTC, chaosvolt reviewed
So, some issues with this I spotted a bit belatedly:
1. Winged zombies and garghouls can't fly, only flesh raptors can. I guess that makes sense if you're being realismic, but a side effect of that is that winged zombies and garghouls don't really have any reason to exist. But funny thing about that...
2. That's the neat part, they don't! Crawlers were given pupas as evolutions so those will spawn, but batwing zombies and garghouls don't have any spawns or evolution connections.

I'd say give winged zombies monstergroup inclusions with a `starts` delay of about 500, since they're potentially bigger and beefier than flesh raptors that have a half-life of 14 (which should work out to 336 hours), but in exchange add `FLIES` to them and garghouls, and adjust descriptions where needed.

2024-10-23 16:24 UTC, chaosvolt approved these changes

2024-10-24 08:59 UTC, NappingOcean commented
I think you forgot the monsters that evolve into `mon_zombie_pupa`. Maybe `mon_zombie_fat`?

2024-10-24 11:12 UTC, chaosvolt commented
Oh yeah, didn't notice that earlier, hecc.

2024-10-24 11:24 UTC, chaosvolt requested changes
Things I once again didn't spot last time:
1. `GROUP_ZOMBIE_RAPTOR_UPGRADES` is unused. I assume it's meant to be an evolution for any flesh raptors that spawn? If so you'd want to change the default, I doubt it will like a recursive evolution. Alternatively you could give it as an evolution to pupas to allow them to burst off-map over time, and this would make the existing default monster make more sense (as then it'd mean pupas that spawn later on get replaced with a wide variety of raptors).
2. `GROUP_ZOMBIE_SHADY_UPGRADES` is unimplemented. I assume it's meant to be used as an evolution for shady zombies? If so again, default is already `mon_zombie_shady` so you'd likely want to tweak that.
3. As noted, `mon_zombie_pupa_decoy` and `mon_zombie_pupa` don't spawn. Placing them in `GROUP_ZOMBIE_FAT` may be reasonable.

2024-10-25 22:09 UTC, chaosvolt approved these changes
![image](https://github.com/user-attachments/assets/6dfaa951-b27b-429d-a10e-fa7c645e79ef)

2024-10-25 22:47 UTC, merged