feat(content): Add light switch
cataclysmbnteam/Cataclysm-BN pull request #5626
Opened 2024-10-29 01:40 UTC by Skas8825

## Checklist

### Required

- [ ] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [ ] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

 

## Purpose of change
Build of my previous PR where i added ceiling lamps, since a player probably will use multiples ceiling lamps to light a large area turning them off/on one at a time is tedious.

## Describe the solution
Add a furniture called light switch that turns off/on all the ceiling lamps in a overmap terrain, also turn's off/on other light switches on the overmap terrain giving the possibility of having multiple switches to control the lights. Since i needed to add code the function's will probably be quite wacky cus i suck at C++, suggestions or corrections to this are welcome!!

## Describe alternatives you've considered
Add other light sources like the standing lamp, but figured a player may want to have a standing lamp separated from the switches.

## Additional context

https://github.com/user-attachments/assets/ce6a2b38-bf20-4798-a1b2-92e05d42af3e

2024-11-02 16:11 UTC, chaosvolt reviewed
Spelling goes nyooom

2024-11-02 16:11 UTC, chaosvolt commented on data/json/construction.json
> +    "group": "build_ligth_switch",
```suggestion
    "id": "constr_f_light_switch",
    "group": "build_light_switch",
```

2024-11-02 16:11 UTC, chaosvolt commented on data/json/construction_group.json
> +    "id": "build_ligth_switch",
```suggestion
    "id": "build_light_switch",
```

2024-11-02 16:11 UTC, chaosvolt commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "name": "ligth switch (off)",
```suggestion
    "name": "light switch (off)",
```

2024-11-02 16:11 UTC, chaosvolt commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "name": "ligth switch (on)",
```suggestion
    "name": "light switch (on)",
```

2024-11-02 17:20 UTC, KheirFerrum submitted a review, later dismissed
Add to your PR solution section what you've added to the tiles. The addition of the `find_furnitures_in_omt` should also be documented, but I'll likely change that to `find_furnitures_in_submap` later.

2024-11-02 17:20 UTC, KheirFerrum commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "flags": [ "TRANSPARENT", "EASY_DECONSTRUCT", "L_OFF" ],
You should be able to use `"extend": { "flags": [ "L_OFF" ] },` here and for the other changes in your json. See the fridge in the same file. Extend and delete will be more effective if we ever add/remove flags from the base, abstract item this copies from.

2024-11-02 17:20 UTC, KheirFerrum commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "flags": [ "EASY_DECONSTRUCT", "L_OFF" ],
So if I'm reading this correctly toggling a light switch will also toggle other light switches in the same overmap?

2024-11-02 17:20 UTC, KheirFerrum commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "prompt": "Switch on the lights.",
Remove unused prompts, I'd prefer no "just in case" and either it not being there or "the code craps itself if a prompt is not written"

2024-11-02 17:20 UTC, KheirFerrum commented on src/iexamine.cpp
> +void iexamine::toggle_lights( player &p, const tripoint &examp )
As the player is unused, you should not feed the function the player variable. See `iexamine::none` for an example.

2024-11-02 19:39 UTC, Skas8825 commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "flags": [ "TRANSPARENT", "EASY_DECONSTRUCT", "L_OFF" ],
Thanks, didn't know this one existed.

2024-11-02 19:39 UTC, Skas8825 commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "flags": [ "EASY_DECONSTRUCT", "L_OFF" ],
Yep, that was my intention.

2024-11-02 20:34 UTC, KheirFerrum commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "extend": { "flags": [ "L_OFF" ] },
Should probably remove this, only have the OFF and ON flags on on and off variants.

2024-11-02 20:34 UTC, KheirFerrum commented on data/json/furniture_and_terrain/furniture-appliances.json
> +    "extend": { "flags": [ "L_ON" ] },
Shouldn't this be `L_OFF`?

2024-11-02 20:34 UTC, KheirFerrum commented on data/json/furniture_and_terrain/furniture-appliances.json
>      "transforms_into": "f_olight_nopower",
Minor comment for whoever merged the ceiling lights. This breaks convention, should be `f_olight_off` not `f_olight_nopower`. Someone is going to need to PR the change soon, and unfortunately migration doesn't cover it so congrats we're breaking saves.

2024-11-02 20:37 UTC, Skas8825 commented on data/json/furniture_and_terrain/furniture-appliances.json
>      "transforms_into": "f_olight_nopower",
They are different, i copied how the standing lamp worked when i made them, the off one is when it's swicthed off and the nopower one is when there it's no power in the grid.

2024-11-03 01:54 UTC, scarf005 requested changes
looks great, tho there's some code nitpicks here and there. also please check the checklist on PR body and clang-tidy warnings (you can ignore the ones in `Unchanged files with check annotations`)

2024-11-03 01:54 UTC, scarf005 commented on src/map.h
> +        std::list<tripoint> find_furnitures_with_flag_in_omt( const tripoint &p, const std::string &flag );
```suggestion
        std::vector<tripoint> find_furnitures_with_flag_in_omt( const tripoint &p, const std::string &flag );
```
would be better to use vector in most cases since lists are often less performant due to cache locality

2024-11-03 01:54 UTC, scarf005 commented on gfx/MSX++UnDeadPeopleEdition/normal_furniture.png
minor nitpick, but it seems to be that both switches in `switch (off)` and `switch (on)` is facing up; perhaps we could edit the sprite so that the switch `switch (on)` faces down, making it more distinct?

2024-11-03 01:54 UTC, scarf005 commented on src/iexamine.cpp
> +    };
```suggestion
    const auto flag = here.has_flag_furn( flag, examp ) ? "L_OFF" : "L_ON";
```
avoid mutation where possible because it makes code harder to read

2024-11-03 01:54 UTC, scarf005 commented on src/iexamine.cpp
> +        g->m.furn_set( light_loc, g->m.get_furn_transforms_into( light_loc ) );
```suggestion
        here.furn_set( light_loc, here.get_furn_transforms_into( light_loc ) );
```

the map instance is already obtained via `here`; avoid using the `g`ame god object.

2024-11-03 01:54 UTC, scarf005 commented on src/iexamine.cpp
> +    std::string message = g->m.furn( examp ).obj().message;
```suggestion
```
this is only used in last line; might be better to inline it.

2024-11-03 01:54 UTC, scarf005 commented on src/iexamine.cpp
> +    add_msg( _( message ) );
```suggestion
    add_msg( _( map.furn( examp ).obj().message ) );
```
after inlining:

2024-11-03 01:54 UTC, scarf005 commented on src/iexamine.cpp
> +    std:: string flag = "L_OFF";
```suggestion
```
avoid declaring variable then mutating it; check below review comment for details.

2024-11-03 01:54 UTC, scarf005 commented on src/iexamine.cpp
> +
```suggestion
```
nitpick (doesn't affect approval): empty line added by mistake?

2024-11-03 01:54 UTC, scarf005 commented on src/map.cpp
> +#include "construction.h"
```suggestion
```
duplicate headers by accident?

2024-11-03 02:02 UTC, Skas8825 commented on gfx/MSX++UnDeadPeopleEdition/normal_furniture.png
It's indeed the same sprite with different color, i don't have skills in pixel art so i reused the ones that are in the terrain category in the UDP tileset.

2024-11-03 03:21 UTC, Skas8825 commented on src/iexamine.cpp
> +    };
This line gives me the error `a variable declared with an auto type specifier cannot appear in its own initializer	` in Visual Studio.

2024-11-03 03:24 UTC, scarf005 commented on src/iexamine.cpp
> +    };
my mistake, it should have been `"L_OFF"`. also we can see why mutation is not often desired: it's easy to make little mistakes like this.

2024-11-03 03:28 UTC, Skas8825 commented on src/iexamine.cpp
> +    };
Alright thank you

2024-11-03 04:31 UTC, Skas8825 commented
> looks great, tho there's some code nitpicks here and there. also please check the checklist on PR body and clang-tidy warnings (you can ignore the ones in `Unchanged files with check annotations`)

I'm not gonna lie, i'm not really sure if the clang-tidy warnings are the one in the checks tab of github and what to do with them srry.

2024-11-05 17:46 UTC, Skas8825 commented on data/json/furniture_and_terrain/furniture-appliances.json
>      "transforms_into": "f_olight_nopower",
I wonder if it's better to change that error in this pull request or change it another time?

2024-11-14 02:09 UTC, KheirFerrum commented on data/json/furniture_and_terrain/furniture-appliances.json
>      "transforms_into": "f_olight_nopower",
I'd do it separately, this PR is burdened enough as is.

2024-11-14 02:12 UTC, scarf005 approved these changes
LGTM, @chaosvolt could you playtest a bit just to be extra sure?

2024-11-14 02:54 UTC, KheirFerrum commented on gfx/MSX++UnDeadPeopleEdition/normal_furniture.png
Suggestion: Take the off light switch, rotate it 180 degrees and reflect it 180 degrees. Most of the time the tile is too small for fine details so it shouldn't be too incongruent.

2024-11-14 02:59 UTC, KheirFerrum commented
I'm good with most of the code, especially since scarf directed the clean up. I have a suggestion for the light switch tile that will not require great skill at art.

2024-11-14 03:07 UTC, Skas8825 commented on gfx/MSX++UnDeadPeopleEdition/normal_furniture.png
I tried that and while it looks a bit weird it's still an improvement, will update the branch in a bit.

2024-11-14 03:38 UTC, scarf005 submitted a review, later dismissed

2024-11-14 03:38 UTC, scarf005 commented on gfx/MSX++UnDeadPeopleEdition/normal_furniture.png
...oh, also it might be better to move the sprite to [external tileset](https://docs.cataclysmbn.org/en/mod/json/reference/graphics/external_tileset/); while we haven't done it for a long time `gfx/MSX++UnDeadPeopleEdition/` is (supposed to be) [auto-generated](https://github.com/Theawesomeboophis/UndeadPeopleTileset) so it might get overwritten when it happens.

2024-11-14 04:26 UTC, chaosvolt commented
Moved the new sprites so that they won't run afoul of merge conflict issues.

2024-11-14 04:29 UTC, scarf005 approved these changes

2024-11-14 05:30 UTC, merged