feat(port): Implement `GLOBALLY_UNIQUE`
cataclysmbnteam/Cataclysm-BN pull request #5723
Opened 2024-11-16 02:06 UTC by Zlorthishen

## Checklist

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

- [x] This PR ports commits from DDA or other cataclysm forks.
  - [x] I have attributed original authors in the commit messages adding [`Co-Authored-By`](https://docs.github.com/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in the commit message.
  - [x] I have linked the URL of original PR(s) in the description.
- [x] This is a C++ PR that modifies JSON loading or behavior.
  - [x] I have documented the changes in the appropriate location in the `doc/` folder.
  - [x] If documentation for this feature does not exist, please write it or at least note its lack in PR description.

-->

## Purpose of change
ports dda change
 - https://github.com/CleverRaven/Cataclysm-DDA/pull/59328

## Describe the solution

## Describe alternatives you've considered

## Testing

## Additional context

2024-11-16 07:16 UTC, scarf005 reviewed
i get evac center needing to be unique because of unique npcs it spawns, but may i ask why military bases and aircraft carrier need be globally unique?

2024-11-16 07:37 UTC, RoyalFox2140 commented
> i get evac center needing to be unique n because of unique npcs it spawns, but may i ask why military bases and aircraft carrier need be globally unique?

Generally speaking I'm ok with adding more specific military locations and tying them into quests than just having a single generic military base.

If we want to go with players being able to access military loot sustainably we can add national guard armories and an airbase, plus garrisons.

The carrier is a bit of a weird one as finding several carriers in lakes would be more of a stretch than finding one.

2024-11-16 15:47 UTC, Zlorthishen commented
> i get evac center needing to be unique because of unique npcs it spawns, but may i ask why military bases and aircraft carrier need be globally unique?

those were just from the original dda pr, but there are probably a few other locations that could be Globally Unique
 - Tacoma Ranch
 - Isherwood Farm
 - The Necropolis

2024-11-17 03:53 UTC, scarf005 submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/2f76fa84-311f-48af-bc83-12603ce99a21)

LGTM

2024-11-17 16:44 UTC, chaosvolt requested changes
1. Compiled and load-tested.
2. Spawned in the aircraft carrier scenario twice, second time it fails to find a starting location:
![image](https://github.com/user-attachments/assets/6578784e-fef5-4aa7-9ea3-e13b09ec2f8c)

This is on default world settings and is exactly why we haven't ported this PR in all this time.

2024-11-17 17:04 UTC, chaosvolt commented
Testing in build `2024-11-14`: 
1. Success
2. Success
3. Success
4. Success
5. Success
6. Success
7. Success
8. Success
9. Success
10. Success

Testing in compiled PR:
1. Success
2. Failure
3. CRASHES
4. Success
5. Success
6. Success
7. Success
8. Success
9. Success
10. Success

Both tests done with default world settings. Only having it fail to generate once is arguably not fatal to this PR since the sample size is low enough and the carrier scenario is suspected to do this occasionally even without this PR, but the crash is definitely concerning.
![image](https://github.com/user-attachments/assets/72bb5560-bb15-4af5-9143-95ae56cfa5e9)

2024-11-17 17:22 UTC, chaosvolt commented
I've yet to get it to crash again to try and grab more info, but I did just get four failures to generate in a row.

2024-11-17 17:23 UTC, KheirFerrum requested changes

2024-11-17 17:23 UTC, KheirFerrum commented on src/overmap.cpp
> +            const overmap_special_placement_constraints &constraints = iter.special_details->get_constraints();
Where do these variables come into play? Remove, or incorporate them into the code. Check the `Files Changed` tab to check for these variables.

It shouldn't really even have passed tests with unused variables. Did we disable that?

2024-11-17 23:54 UTC, scarf005 commented on src/overmap.cpp
> +            const overmap_special_placement_constraints &constraints = iter.special_details->get_constraints();
> It shouldn't really even have passed tests with unused variables. Did we disable that?

lint for unused variables exists but it only emits warning because it often crashed on unrelated existing issues

2024-12-05 00:44 UTC, scarf005 commented on src/overmap.cpp
> +            const overmap_special_placement_constraints &constraints = iter.special_details->get_constraints();
speaking of "unrelated", should make it error again since #5548 is merged and there probably won't be unrelated changes anymore

2024-12-30 01:23 UTC, scarf005 commented
> 1. Compiled and load-tested.
> 
>     2. Spawned in the aircraft carrier scenario twice, second time it fails to find a starting location:
>        ![image](https://private-user-images.githubusercontent.com/11582235/386978747-6578784e-fef5-4aa7-9ea3-e13b09ec2f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MjEzMDUsIm5iZiI6MTczNTUyMTAwNSwicGF0aCI6Ii8xMTU4MjIzNS8zODY5Nzg3NDctNjU3ODc4NGUtZmVmNS00YWE3LTllYTMtZTEzYjA5ZWMyZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDAxMTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDg2MDkyODk0M2U1ZDNmODdjMTE0NjQwYzlkMmZjMmI0NzAzOTJhMGRkODFkMzljY2ZhYjY5ZWZiOTM3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HvRp1eOGboClZwRralsAKb4NRb1ToS1gmwiSMhOdVcM)
> 
> 
> This is on default world settings and is exactly why we haven't ported this PR in all this time.

is this issue resolved?

2025-01-04 04:44 UTC, Zlorthishen commented
> 
> is this issue resolved?
I just tried the aircraft carrier scenario ten times and it never gave me that error.

2025-01-04 05:14 UTC, Zlorthishen commented on src/overmap.cpp
> +            const overmap_special_placement_constraints &constraints = iter.special_details->get_constraints();
i removed the variable `constraints` and it still compiles

2025-01-07 02:35 UTC, scarf005 commented on src/overmapbuffer.cpp
> +    return placed_unique_specials.find( id ) != placed_unique_specials.end();
https://en.cppreference.com/w/cpp/container/unordered_set/contains
```suggestion
    return placed_unique_specials.contains( id );
```

2025-01-07 19:57 UTC, chaosvolt approved these changes
Basics of it look good and no longer having constant issues with the starting location, but at some point we may want to figure out how to fix mission target placement.
![image](https://github.com/user-attachments/assets/9a8eecff-8664-4f7a-b93d-b29c36cbfee5)

2025-01-07 23:27 UTC, chaosvolt commented
Should now be mitigated with: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5900

2025-01-08 00:06 UTC, RoyalFox2140 approved these changes

2025-01-08 00:10 UTC, merged