feat: More electric motor recipes
cataclysmbnteam/Cataclysm-BN pull request #5805
Opened 2024-12-13 18:58 UTC by Berehenia

Add recipes for the electric motor, large electric motor, enhanced electric motor, and super electric motor

## Checklist

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

## Purpose of change

Electric motors above small tier are not craftable, you can only find them by sheer luck most of the time. Adding recipes to them that are roughly based on their disassembled amounts (and a bit more) would make it less obnoxious for the players. Not sure about balancing the super motor at 7 but yeah, that's up in the air. 

## Describe the solution

## Describe alternatives you've considered

## Testing

## Additional context

2024-12-13 21:20 UTC, chaosvolt commented
Enhanced electric motor is made of superalloy, so swapping the steel for allow sheets might be a good idea.

2024-12-13 22:25 UTC, karxi commented
If the enhanced motor is made of superalloy, the super motor definitely should be.
Mechanics seems reasonable (though probably at a lower skill requirement than installing one) given the increased size and particular purpose of the large, enhanced, and super engines.

I think pure Electronics and Fabrication is still fine for normal ones, but enhanced motors are valuable and especially useful.
Super motors are virtually unheard of—they're extremely specialized equipment used only in electric racing cars and atomic helicopters—so a recipe to make them should probably be top-tier/endgame skills.

2024-12-13 22:30 UTC, RoyalFox2140 commented
Yeah only Super/Enhanced needs Mechanics, primarily due to how insane they are in vehicles, lower skill is also ok, since it relies on electronics.

2024-12-13 23:00 UTC, karxi commented
The times for these could probably use adjustment too. An hour is not very long for (again) making an engine that can power a small helicopter. *There are characters that might only ever **need** one or two super engines.* They should be time-consuming and resource intensive (particularly since, again, endgame) to make.
It'd likely also be wise to raise the skill it takes to learn the recipes according to how hard they are; 2 across the board is very low.

2024-12-14 01:29 UTC, Berehenia commented
Hi, just woke up
Skills can be jacked up, time can be jacked up as well but I don't know what's appropriate, so here's a suggestion :

5 both for large, 8hr crafting
6 elec 6 fab for enhanced, 10 hour crafting 
8 elec 8 fab for super, 15 hour crafting

Super, even if it is complex wouldn't be more complex than most cbms, right? 

The enhanced motor, even if it's superalloy base, does not give any when it's disassembled, so I didnt put any in the recipe, so it's up to others whether we swap out it's material or it's crafting recipe

2024-12-14 03:05 UTC, Berehenia commented
Discussion held at
https://discord.com/channels/830879262763909202/830916451517857894/1317326459391705140

2024-12-14 19:24 UTC, chaosvolt commented
> The enhanced motor, even if it's superalloy base, does not give any when it's disassembled, so I didnt put any in the recipe, so it's up to others whether we swap out it's material or it's crafting recipe

Weird, I couldn't find an uncraft for it. o.O

2024-12-19 02:57 UTC, karxi requested changes
I fixed my errors with the lumps of steel, as well as the ``soldering_standard`` counts. I've tried all of these ingame, so if you choose to use them, they do work as-is.

I hope this is satisfactory!

2024-12-19 02:57 UTC, karxi commented on data/json/recipes/electronic/components.json
> +  },
```suggestion
  {
    "type": "recipe",
    "result": "motor",
    "category": "CC_ELECTRONIC",
    "subcategory": "CSC_ELECTRONIC_PARTS",
    "skill_used": "electronics",
    "difficulty": 3,
    "skills_required": [ "fabrication", 2 ],
    "time": "120 m",
    "reversible": true,
    "decomp_learn": 3,
    "book_learn": [ [ "manual_electronics", 3 ], [ "mag_electronics", 3 ], [ "manual_mechanics", 3 ] ],
    "using": [ [ "soldering_standard", 40 ], [ "steel_standard", 5 ] ],
    "qualities": [
      { "id": "HAMMER", "level": 1 },
      { "id": "SAW_M_FINE", "level": 1 },
      { "id": "SAW_M", "level": 1 },
      { "id": "SCREW", "level": 1 }
    ],
    "components": [
      [ [ "e_scrap", 5 ] ],
      [ [ "power_supply", 1 ] ],
      [ [ "amplifier", 2 ] ],
      [ [ "bearing", 10 ] ],
      [ [ "cable", 20 ] ]
    ]
  },
```
Lowered the skill_used, per your requests. Updated everything else per Discord talks.

2024-12-19 02:57 UTC, karxi commented on data/json/recipes/electronic/components.json
> +  },
```suggestion
  {
    "type": "recipe",
    "result": "motor_large",
    "category": "CC_ELECTRONIC",
    "subcategory": "CSC_ELECTRONIC_PARTS",
    "skill_used": "electronics",
    "difficulty": 5,
    "skills_required": [ [ "fabrication", 2 ], [ "mechanics", 4 ] ],
    "time": "300 m",
    "reversible": true,
    "decomp_learn": 4,
    "book_learn": [ [ "textbook_fabrication", 4 ], [ "manual_electronics", 4 ], [ "mag_electronics", 4 ], [ "manual_mechanics", 4 ] ],
    "using": [ [ "soldering_standard", 50 ], [ "steel_standard", 15 ] ],
    "qualities": [
      { "id": "HAMMER", "level": 1 },
      { "id": "SAW_M_FINE", "level": 1 },
      { "id": "SAW_M", "level": 1 },
      { "id": "SCREW", "level": 1 }
    ],
    "components": [
      [ [ "e_scrap", 5 ] ],
      [ [ "power_supply", 2 ] ],
      [ [ "amplifier", 4 ] ],
      [ [ "bearing", 40 ] ],
      [ [ "cable", 30 ] ],
      [ [ "motor_oil", 500 ] ]
    ]
  },
```
Per suggestions on Discord. I've lowered the motor oil requirements; now they only take a plastic bottle of it, which isn't hard to find. (Disassembling other engines is also an easy way to acquire that.)

2024-12-19 02:57 UTC, karxi commented on data/json/recipes/electronic/components.json
> +  },
```suggestion
  {
    "type": "recipe",
    "result": "motor_enhanced",
    "category": "CC_ELECTRONIC",
    "subcategory": "CSC_ELECTRONIC_PARTS",
    "skill_used": "electronics",
    "difficulty": 6,
    "skills_required": [ [ "fabrication", 4 ], [ "mechanics", 5 ] ],
    "time": "480 m",
    "reversible": true,
    "decomp_learn": 6,
    "book_learn": [ [ "reference_fabrication1", 5 ], [ "recipe_lab_elec", 5 ] ],
    "using": [ [ "soldering_standard", 75 ], [ "steel_standard", 20 ], [ "welding_standard", 10 ] ],
    "qualities": [
      { "id": "HAMMER", "level": 3 },
      { "id": "SAW_M_FINE", "level": 1 },
      { "id": "SCREW_FINE", "level": 1 },
      { "id": "WRENCH_FINE", "level": 1 },
      { "id": "SAW_M", "level": 1 },
      { "id": "SCREW", "level": 1 }
    ],
    "components": [
      [ [ "e_scrap", 10 ] ],
      [ [ "circuit", 4 ] ],
      [ [ "processor", 1 ] ],
      [ [ "power_supply", 3 ] ],
      [ [ "amplifier", 4 ] ],
      [ [ "bearing", 50 ] ],
      [ [ "cable", 90 ], [ "carbon_fiber_filament", 30 ] ],
      [ [ "motor_oil", 750 ] ],
      [ [ "alloy_sheet", 10 ] ]
    ]
  },
```
More Discord chat stuff. Difficulty is mostly the same, learning the recipe (from books) is easier. Learning it from disassembly is harder.

2024-12-19 02:57 UTC, karxi commented on data/json/recipes/electronic/components.json
> +  },
```suggestion
  {
    "type": "recipe",
    "result": "motor_super",
    "category": "CC_ELECTRONIC",
    "subcategory": "CSC_ELECTRONIC_PARTS",
    "skill_used": "electronics",
    "difficulty": 8,
    "skills_required": [ [ "fabrication", 6 ], [ "mechanics", 7 ] ],
    "time": "12 h",
    "reversible": true,
    "decomp_learn": 8,
    "book_learn": [ [ "recipe_lab_elec", 8 ] ],
    "using": [ [ "soldering_standard", 100 ], [ "steel_standard", 60 ], [ "welding_standard", 10 ] ],
    "qualities": [
      { "id": "HAMMER", "level": 3 },
      { "id": "SAW_M_FINE", "level": 1 },
      { "id": "SAW_M", "level": 1 },
      { "id": "SCREW_FINE", "level": 1 },
      { "id": "WRENCH_FINE", "level": 1 },
      { "id": "SCREW", "level": 1 }
    ],
    "components": [
      [ [ "e_scrap", 20 ] ],
      [ [ "circuit", 6 ] ],
      [ [ "processor", 2 ] ],
      [ [ "self_monitoring_module", 1 ] ],
      [ [ "power_supply", 4 ] ],
      [ [ "amplifier", 6 ] ],
      [ [ "bearing", 60 ] ],
      [ [ "motor_oil", 1000 ] ],
      [ [ "carbon_fiber_filament", 75 ] ],
      [ [ "alloy_sheet", 15 ] ]
    ]
  },
```
Super motors made significantly more resource-intensive (in rarity and quantity). They're not *nightmarish*, but ideally players have to scrap combustion engines and visit dangerous locales to make super motors.

2024-12-19 23:12 UTC, RoyalFox2140 approved these changes
It looks good but I need opinion from @chaosvolt 

The motor oil is a weird stand in for lubricant but I don't think we gain enough modeling a new item for just electric motors.

2024-12-20 02:14 UTC, chaosvolt approved these changes
Just from a quick look over them they seem okay, far as I can tell. Difficulty could potentially be bumped up a bit but they aren't too bad I don't think.

2024-12-20 04:17 UTC, chaosvolt reviewed
Some possible balance tweaks one could make though.

2024-12-20 04:17 UTC, chaosvolt commented on data/json/recipes/electronic/components.json
> +    "difficulty": 6,
```suggestion
    "difficulty": 7,
```

2024-12-20 04:17 UTC, chaosvolt commented on data/json/recipes/electronic/components.json
> +    "difficulty": 5,
```suggestion
    "difficulty": 6,
```

2024-12-20 04:17 UTC, chaosvolt commented on data/json/recipes/electronic/components.json
> +    "difficulty": 3,
```suggestion
    "difficulty": 5,
```

2024-12-20 04:17 UTC, chaosvolt commented on data/json/recipes/electronic/components.json
> +    "using": [ [ "soldering_standard", 75 ], [ "steel_standard", 20 ], [ "welding_standard", 10 ] ],
Maybe less steel and more superalloy?
```suggestion
    "using": [ [ "soldering_standard", 75 ], [ "welding_standard", 10 ] ],
```

2024-12-20 04:17 UTC, chaosvolt commented on data/json/recipes/electronic/components.json
> +      [ [ "alloy_sheet", 10 ] ]
```suggestion
      [ [ "alloy_sheet", 20 ] ]
```

2024-12-20 04:17 UTC, chaosvolt commented on data/json/recipes/electronic/components.json
> +      [ [ "alloy_sheet", 15 ] ]
This one isn't superalloy, the robotics components and carbon fiber already seems reasonable a component requirement.
```suggestion
      [ [ "carbon_fiber_filament", 75 ] ]
```

2024-12-20 17:05 UTC, Coolthulhu commented on data/json/recipes/electronic/components.json
> +    "difficulty": 3,
@chaosvolt why 5? What are some close recipes to compare it to?

Do note that difficulty 4+ allows grinding 2 skill levels, making this recipe a candidate for electronics grinding meta.

2024-12-20 18:35 UTC, chaosvolt commented on data/json/recipes/electronic/components.json
> +    "difficulty": 3,
Main thought was making them all in a row, but this may not be a good idea I suppose. I'll leave it for others to ponder I guess.

2024-12-21 17:44 UTC, chaosvolt commented
Eh, the above suggestions have been mused upon on he discord and objected to abit, plus Coolthulhu's mention that the proposed increase in difficulty may be a bit much, so is probably fine as-is instead.

2024-12-21 17:44 UTC, merged

2024-12-24 18:09 UTC, Ker-Nes commented
Given how a generator and an electric motor are in many ways basically the same thing operating in opposite directions, should we also have a recipe for the 7.5kW Generator? Might, among other things, make fueled power a bit more common by not depending on finding one or only being able to use vehicle alternators instead.

Also, maybe having more size of generators too?