feat(content,port): AGGRO_CHARACTER flag for enemies
cataclysmbnteam/Cataclysm-BN pull request #5846
Opened 2024-12-28 05:14 UTC by shmakota

## Checklist

### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

please remove sections irrelevant to this PR.

- [X] This PR ports commits from DDA or other cataclysm forks.
  - [X] I have attributed original authors in the commit messages adding [`Co-Authored-By`](https://docs.github.com/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in the commit message.
  - [X] I have linked the URL of original PR(s) in the description.
- [X] This is a C++ PR that modifies JSON loading or behavior.
  - [X] I have documented the changes in the appropriate location in the `doc/` folder.
 

## Purpose of change

ports change
https://github.com/CleverRaven/Cataclysm-DDA/pull/59795

> Add a (rudimentary) selection to monster hostility, optionally filtering out characters until a character actually trips an anger trigger.

Additionally, to allow for the creation of enemies with high aggression that wont attack player until triggered by a flag, which otherwise always would. Enemies which do not have `AGGRO_CHARACTER` set to false should behave the same as they did before. Monsters that have this tag, when fighting, should now focus on whatever enemy they were already fighting and redirect their anger to the player less often.

> 

## Describe the solution

> Add `aggro_character` (default true) to `monster` and `mtype`. `false` means the monster will be passive towards characters.
> Add some logic to anger triggers to allow flipping `aggro_character` when a character trips the trigger: attacking/killing a friendly critter, hurting the monster and threatening offspring will always do so, the other triggers will have a random chance for each time they trigger
> Add a lot of debugmode messages to aggro changes
> Add a chance to reset the `aggro_character` when the monster reached its baseline anger level.

## Describe alternatives you've considered

## Testing

- Spawned a 5x5 grid of moose to fight a 5x5 grid of zombie dogs. They fought and the moose eventually started fleeing once enough friends died. They seem to behave exactly the same as they did before the change.

- Spawned bee, beaver, and giant jumping spider. All seem to behave the same as before.

- Created a civilian monster that has high aggression and a high melee attack. Spawned it in a city, and it fought zombies until dying but did not target the player. The civilian will not be included in the PR.

- Changed "mongrel" to have 99 aggression. Mongrel instantly attacks player. When `aggro_character` is set to false, mongrel no longer attacks player, however follows the player around very closely for a long time. I don't think this following behavior is a result of this change, but rather how aggression already worked.

- I spawned a group of civilians with 100 aggression in a city. They fought the zombies around until the zombies died. The civilians then attacked me. A group of civilians with 50 aggression do not attack. This is odd, as the DDA equivalent does not seem to have this issue. This should be fixed.
- I spawned a group of civilians with 100 aggression in a field. Saved and reloaded. Civilians are now aggressive, and won't give up on killing the player. A group spawned with 50 aggression quickly loses interest and goes back to neutral and the expected behavior. This is probably related to the issue above.

As you can see, there is still some unexpected behavior that needs to be sorted out before being merged. These issues most likely wont affect the current player experience as (i think) there are no monsters that would get aggro_character = false and need 100 aggression for some reason, but would prevent a 1:1 port of certain monsters from DDA (namely the civilians) and should be fixed anyways.

## Additional context

We probably need to apply this to more monsters as well, as I only ported what DDA animals had aggro_character set to false.

https://github.com/CleverRaven/Cataclysm-DDA/issues/59565 is also relevant to DDA's version of this change

2025-01-03 22:57 UTC, shmakota commented
the aggression issues may be mitigated by this DDA PR:
https://github.com/CleverRaven/Cataclysm-DDA/pull/60352
i will test soon if this helps

2025-01-04 00:18 UTC, shmakota commented
the save/load aggro behavior should be fixed by this PR:
https://github.com/CleverRaven/Cataclysm-DDA/pull/70938
will test and update this comment once implemented

2025-01-05 19:34 UTC, RobbieNeko reviewed
Noticed a questionable line in the docs. Not that it'll affect compile-testing though, so I'll get on that

2025-01-05 19:34 UTC, RobbieNeko commented on doc/src/content/docs/en/mod/json/reference/json_flags.md
> +- `HURT` The monster is hurt. Always triggers character aggro. Triggers character aggro `<anger>%`
This line seems a bit confusing, given it says that it "always triggers character aggro" but then immediately afterwards instead says it triggers a percentage of the time?

2025-01-05 19:36 UTC, shmakota commented on doc/src/content/docs/en/mod/json/reference/json_flags.md
> +- `HURT` The monster is hurt. Always triggers character aggro. Triggers character aggro `<anger>%`
Ah yep, this was most likely an accident when copying over the documentation changes. It should be always triggers aggro, and not percentage.

2025-01-05 19:56 UTC, OrenAudeles requested changes
Haven't compiled / tested yet but it looks to be good.
- It's usually better to handle cheap to check conditions first. `monster::sees`, unless it's specifically the player character, can be expensive to test.
- Avoiding code repetition is usually a good thing

2025-01-05 19:56 UTC, OrenAudeles commented on src/mattack_actors.cpp
> +        if( !target || !z.sees( *target ) || ( !target->is_monster() && !z.aggro_character ) ) {
`z.sees( *target )` will be the slowest test, so it would be better to rearrange the conditions so it is at the end.
`if( !target || ( !target->is_monster() && !z.aggro_character ) || !z.sees( *target ) ) {`

2025-01-05 19:56 UTC, OrenAudeles commented on src/monmove.cpp
> +                    if( x_in_y( anger, 100 ) ) {
Since this bit of code is repeated a lot it might be good to separate it out to its own function so there is less code repetition:
```cpp
void monster::trigger_character_aggro( const char *reason ) {
    add_msg( m_debug, "%s's character aggro is triggered by %s", get_name(), reason );
    aggro_character = true;
}

void monster::trigger_character_aggro_chance( int chance, const char *reason ) { // eg. reason = "mating season"
    if( x_in_y( chance, 100 ) {
        trigger_character_aggro( reason );
    }
}

// Then call using
// - for anger chance based triggering
trigger_character_aggro_chance( anger, "the reason" );
// - for guaranteed triggering when we are forcing it
trigger_character_aggro( "the reason" );
```

2025-01-05 20:09 UTC, RobbieNeko reviewed
It builds, the moose test works and I made chipmunks incredibly angry. They attacked me, I set the aggro_character to false, they no-longer attacked me. Overall, once the concerns are addressed, looks good to me!

2025-01-05 20:59 UTC, shmakota commented on src/monmove.cpp
> +                    if( x_in_y( anger, 100 ) ) {
Thank you for the suggestions, definitely a good idea to separate into a different function. They have all been implemented now. :)

2025-01-05 21:02 UTC, RobbieNeko approved these changes
Now to just wait for the tests to finish before merging ^-^

2025-01-05 21:12 UTC, OrenAudeles approved these changes

2025-01-05 22:01 UTC, merged