Migration of the Necro Boomer from DDA
cataclysmbnteam/Cataclysm-BN pull request #709
Opened 2021-07-25 07:06 UTC by ZhamelSeh

#### Summary
SUMMARY: [Content] "Migration of the Necro Boomer from DDA."

#### Purpose of change
Migration of the Necro Boomer from DDA

#### Describe the solution
Chanted:
DDA, DDA, send Necro Boomer on over. 

#### Describe alternatives you've considered
Being lame and not port it over.

#### Testing
Copied over code from DDA and built C:BN on Pop!_OS 20.04 LTS  x64 (Ubuntu based) with the changes.
Loaded test world. Teleported to FEMA camp. Killed all mobs. Loaded Necro Boomer. Killed Necro Boomer. Watched in horror as mobs resurrected and some of them evolved. Realized this could be a mistake. Laughed like Dr. Evil. 

#### Additional context
None yet.

2021-08-03 08:42 UTC, Coolthulhu requested changes

2021-08-03 08:42 UTC, Coolthulhu commented on src/mondeath.cpp
> +            if( !corpse.is_corpse() ) {
Needs a check if it's a revivable zombie corpse.

We can't have necro boomers bring normal living stuff back to unzombified life.
Bringing pulped corpses back to life might be interesting, but it would have to be properly evaluated as a game feature first. So this will need to have revivability check copied from necromancer's revive ability.

Instantly zombifying zombifiable corpses might be cool.
If you want to try it, you can copy the corpse zombification code from `item::process_corpse` and apply it to corpses with non-null `corpse.corpse->zombify_into` (double `corpse` - one for variable here, other for `item::corpse`).
But it's optional, you can just avoid non-zombie corpses.

2021-08-03 08:42 UTC, Coolthulhu commented on src/mondeath.cpp
> +        if( mon != nullptr && one_in( 10 ) ) {
This also needs a zombie check.
We can't have dying necro boomers make puppies grow up or impregnate giant cockroaches.

2021-08-09 03:35 UTC, ZhamelSeh commented
OK, I'll take a look this weekend.

2021-09-16 06:14 UTC, Lamandus commented
> OK, I'll take a look this weekend.

are you still working on this?

2021-09-26 01:37 UTC, ZhamelSeh commented
I'm going to try and finish it up this coming weekend, have been crazy busy at work preparing for next month.

2022-02-05 13:24 UTC, Coolthulhu commented
Closing as stale.

2022-02-05 13:24 UTC, closed without merging