Adds new examine actions: notify and transform.
cataclysmbnteam/Cataclysm-BN pull request #716
Opened 2021-07-26 01:29 UTC by Kaylakaze

#### Summary
SUMMARY: [Mods] "Adds new examine actions: notify and transform"

#### Purpose of change
This is to provide modders with more functionality. A lot can be accomplished with just the ability to transform an in-world object and the notify action is just to allow the modder to provide feedback to the user.
Fixes #711 

#### Describe the solution
Two new examine-actions are available to modders: notify and transform.

- Notify: When the object is examined, a popup will be shown with the contents of the object's message property.

- Transform: When the object is examined, it changes into the object specified by its transforms_into property. If the new object has a message property, it is displayed in a popup, like the notify action.

#### Testing
I created a mod that used each examine action and verified that it worked as expected. As the code is very basic and only adds to the existing code instead of 

#### Additional context
This is the lamp I used to test the transform action (I also used it to test notify, but removed that code to test transform):
`{
        "type": "furniture",
        "id": "f_floor_lamp_on",
        "name": "floor lamp",
        "symbol": "T",
        "looks_like": "f_floor_lamp",
        "description": "A tall standing lamp, meant to plug into a wall and light up a room.",
        "color": "white",
        "examine_action": "transform",
        "transforms_into": "f_floor_lamp",
        "move_cost_mod": 2,
        "light_emitted": 160,
        "required_str": 1,
        "flags": [ "TRANSPARENT", "PLACE_ITEM", "EASY_DECONSTRUCT", "USES_GRID_POWER" ],
        "deconstruct": {
          "items": [
            { "item": "cable", "charges": [ 1, 2 ] },
            { "item": "amplifier", "count": [ 1, 4 ] },
            { "item": "light_bulb", "count": [ 1, 4 ] },
            { "item": "steel_lump", "count": 1 },
            { "item": "pipe", "count": 1 }
          ]
        },
        "bash": {
          "str_min": 12,
          "str_max": 40,
          "sound": "metal screeching!",
          "sound_fail": "bonk!",
          "items": [
            { "item": "scrap", "count": [ 1, 2 ] },
            { "item": "cable", "charges": [ 0, 1 ] },
            { "item": "e_scrap", "count": [ 0, 1 ] },
            { "item": "glass_shard", "count": [ 0, 8 ] },
            { "item": "pipe", "count": [ 0, 1 ] }
          ]
        }
    },
    {
        "type": "furniture",
        "id": "f_floor_lamp",
        "name": "floor lamp",
        "symbol": "T",
        "looks_like": "f_rack_coat",
        "description": "A tall standing lamp, meant to plug into a wall and light up a room.",
        "color": "light_gray",
        "move_cost_mod": 2,
        "required_str": 1,
        "examine_action": "transform",
        "transforms_into": "f_floor_lamp_on",
        "flags": [ "TRANSPARENT", "PLACE_ITEM", "EASY_DECONSTRUCT" ],
        "deconstruct": {
          "items": [
            { "item": "cable", "charges": [ 1, 2 ] },
            { "item": "amplifier", "count": [ 1, 4 ] },
            { "item": "light_bulb", "count": [ 1, 4 ] },
            { "item": "steel_lump", "count": 1 },
            { "item": "pipe", "count": 1 }
          ]
        },
        "bash": {
          "str_min": 12,
          "str_max": 40,
          "sound": "metal screeching!",
          "sound_fail": "bonk!",
          "items": [
            { "item": "scrap", "count": [ 1, 2 ] },
            { "item": "cable", "charges": [ 0, 1 ] },
            { "item": "e_scrap", "count": [ 0, 1 ] },
            { "item": "glass_shard", "count": [ 0, 8 ] },
            { "item": "pipe", "count": [ 0, 1 ] }
          ]
        }
    }`

2021-07-26 01:42 UTC, chaosvolt commented
Haven't thought of a vanilla use for notify aside from as a quick way to grok description for stuff that doesn't already have an examine action, but some potential vanilla uses for transform:
1. If it can be set to optionally spawn items on transform, I'd be able to replace the hacky-looking "flag on the ground next to a column" flag spawns with flagpoles as an explicit furniture, with said pole having the player take the flag down as a one-way transformation.
2. If the right `active` function for powered lights is written then that'd combine with this to make grid-powered lights the player can turn on or off a thing. If I'm looking at how this works correctly, it SHOULD hopefully be able to rig it such that a power-consuming `active` function will only perform its function when power is available, so there wouldn't even be a need to hack in any sorta auto-transforming stuff. It'd just have the active lamp give off light if there's power, and not give off light if power's out (as lamps don't automatically turn themselves off when out of power anyway).

I could see if I can make idea two a thing, that might compliment this addition...

2021-07-26 01:46 UTC, chaosvolt commented
Smol side note, the JSON example provided in the OP lacks a transform message, it seems?

2021-07-26 02:03 UTC, Kaylakaze commented
> Smol side note, the JSON example provided in the OP lacks a transform message, it seems?

That is correct. I did test it with one, but in the final, I just wanted a lamp that turned on and off.

2021-07-26 02:17 UTC, chaosvolt commented
What's the default message if one is absent?

2021-07-26 02:20 UTC, Kaylakaze commented
For transform, if there isn't one, the popup never triggers. For notify, if there's no message, you get a tiny empty popup box.

2021-07-26 06:09 UTC, Coolthulhu commented on src/iexamine.cpp
> +    if ( message.length() > 0 ) {
`if( !message.empty() ) {`

2021-07-26 06:14 UTC, Coolthulhu commented on src/iexamine.cpp
> +    std::string message = g->m.has_furn( pos ) ? g->m.furn( pos ).obj().message : g->m.ter( pos ).obj().message;
Would probably be better to put the message declaration to the start of the function and just fill it in in the `if/else` above.
Consider the case where furniture exists, but transforms into "lack of furniture": in this case message for terrain below will be displayed.

2021-07-26 06:14 UTC, Coolthulhu commented on src/iexamine.cpp
> +    popup( _( message ) );
Popups are a bit obnoxious if you have to see them often. They are mostly useful for stuff that you have to stop and think about.
`add_msg` may be better.

2021-07-26 06:22 UTC, Coolthulhu commented
> That is correct. I did test it with one, but in the final, I just wanted a lamp that turned on and off.

Could you add it to a file? For example, a new file `data/json/furniture_and_terrain/furniture-testing.json`.
Having a testable example in the repo is pretty vital. Without it, someone may remove the functionality, because it looks unused.

2021-07-26 06:29 UTC, Coolthulhu commented
Astyle check is failing because you have used different spacing in `if`s and newlines around `else`.
I'm not sure what IDE are you using, but if it's one of the popular ones, it should have support for `astylerc`. Alternatively, manually setting it to put spaces in `if`s like `if( x )` and to keep `} else {` as one line could be enough.

2021-07-26 08:37 UTC, Kaylakaze commented on src/iexamine.cpp
> +    popup( _( message ) );
Well, I primarily added them there so the modder has the option. For example, if there was a tape recorder that they modded in that, when examined, told the account of a survivor in a few paragraphs. You wouldn't want to try reading that in the message log. I don't know what some modder may decide to do with it, but it's about giving them options to be creative.

2021-07-26 12:11 UTC, Coolthulhu commented on data/json/furniture_and_terrain/terrain-zztesting.json
> +        "description": "This is a standalone computer terminal.  It doesn't seem to be working.  It's the broken screen and shattered circuit boards that's telling you that.",
"It's" -> "Its"
"It's" is a contraction of "It is".

2021-07-26 12:12 UTC, Coolthulhu commented on data/json/furniture_and_terrain/furniture-zztesting.json
> -        "message": "Click off",
The message should be there and the notify action should also have its own message somewhere, it's just that they should be done using `add_msg` instead of popups.

2021-07-26 12:16 UTC, Coolthulhu commented on data/json/furniture_and_terrain/furniture-zztesting.json
> +        "id": "f_floor_lamp_on",
Instead of redefining the whole lamp, it would be better to use `"copy-from"`.
That is, specify just the `type`, `id`, then add
```
"copy-from": "f_floor_lamp"
```
And after that, only specify things that differ from the thing you're copying from.
This makes it much less likely that someone updates only one of the two by accident or that someone updates them in a different way.

2021-07-26 12:17 UTC, Coolthulhu commented on data/json/furniture_and_terrain/terrain-zztesting.json
> +        "id": "t_console_broken_test",
Same here: if it's identical to broken console except for its new examine action and message, it would be best done with `copy-from`.

2021-07-26 15:35 UTC, Kaylakaze commented on data/json/furniture_and_terrain/terrain-zztesting.json
> +        "id": "t_console_broken_test",
Strangely, copy-from still requires "color" and "symbol" parameters or the system will throw an error.

2021-07-26 16:25 UTC, Kaylakaze commented on data/json/furniture_and_terrain/terrain-zztesting.json
> +        "id": "t_console_broken_test",
It turns out that "copy-from" still requires "symbol" and "color" or else it'll error.

2021-07-26 16:27 UTC, Kaylakaze commented on src/iexamine.cpp
> +    popup( _( message ) );
The whole purpose of "notify" is to allow modders to be able to create a popup, which they can't currently do in any other way. I did update "transform" to use add_msg for its message capabilities because that makes sense.

2021-07-26 16:29 UTC, Kaylakaze commented on src/iexamine.cpp
> +    popup( _( message ) );
I'm planning to port over DDA's new(er?) enhanced version of examine_action which can take an object instead of a string, which allows all sorts of options to be provided to the action function without having to expand the furn or ter objects (as I had to do to add the message property). That will allow for some incredible modding capabilities.

2021-07-31 13:47 UTC, Coolthulhu requested changes

2021-07-31 13:47 UTC, Coolthulhu commented on src/iexamine.cpp
> +void iexamine::transform( player &p, const tripoint &pos )
The `p` parameter isn't used. Same in `notify`.
If you aren't using a parameter, remove its name, but keep its type.
```suggestion
void iexamine::transform( player &, const tripoint &pos )
```

2021-07-31 13:47 UTC, Coolthulhu commented on src/iexamine.cpp
> +void iexamine::notify( player &p, const tripoint &pos )
```suggestion
void iexamine::notify( player &, const tripoint &pos )
```

2021-08-01 22:56 UTC, Kaylakaze commented
I have officially reached "Fuck it"

2021-08-02 06:39 UTC, Coolthulhu commented
> I have officially reached "Fuck it"

It's just a json error. Run it through https://dev.narc.ro/cataclysm/format.html and it should work.

2021-08-03 05:54 UTC, Coolthulhu approved these changes

2021-08-03 08:22 UTC, merged